model_list:
  - model_name: deepseek-v4-flash
    litellm_params:
      model: anthropic/deepseek-v4-flash
      api_key: os.environ/DEEPSEEK_ANTHROPIC_API_KEY
      api_base: https://api.deepseek.com/anthropic

  - model_name: deepseek-v4-pro
    litellm_params:
      model: anthropic/deepseek-v4-pro
      api_key: os.environ/DEEPSEEK_ANTHROPIC_API_KEY
      api_base: https://api.deepseek.com/anthropic

  - model_name: sonnet-4-6
    litellm_params:
      model: openai/claude-sonnet-4-6
      api_base: os.environ/OHMYGPT_API_BASE
      api_key: os.environ/OHMYGPT_API_KEY

  - model_name: opus-4-6
    litellm_params:
      model: openai/claude-opus-4-6
      api_base: os.environ/OHMYGPT_API_BASE
      api_key: os.environ/OHMYGPT_API_KEY

  - model_name: claude-haiku-4-5
    litellm_params:
      model: openai/claude-haiku-4-5
      api_base: os.environ/OHMYGPT_API_BASE
      api_key: os.environ/OHMYGPT_API_KEY

litellm_settings:
  drop_params: true
  add_streaming_chunk_size: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  disable_ui_auth: true
