@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module Dependency Overview

component "cn.haolab.problem.fjsp.model\n134 types" as M_cn_haolab_problem_fjsp_model
component "com.evolsoft.bayesian\n26 types" as M_com_evolsoft_bayesian
component "com.evolsoft.core\n367 types" as M_com_evolsoft_core
component "com.evolsoft.ec.chart\n25 types" as M_com_evolsoft_ec_chart
component "com.evolsoft.ec.diagram\n13 types" as M_com_evolsoft_ec_diagram
component "com.evolsoft.ec.eda\n6 types" as M_com_evolsoft_ec_eda
component "com.evolsoft.ec.ga.tool\n21 types" as M_com_evolsoft_ec_ga_tool
component "com.evolsoft.ec.msga.tool\n17 types" as M_com_evolsoft_ec_msga_tool
component "com.evolsoft.ec.pbil\n61 types" as M_com_evolsoft_ec_pbil
component "com.evolsoft.ec.pbil.testSuite\n11 types" as M_com_evolsoft_ec_pbil_testSuite
component "com.evolsoft.ec.problem.rcpsp\n51 types" as M_com_evolsoft_ec_problem_rcpsp
component "com.evolsoft.ec.problem.rcpsp.individualService\n22 types" as M_com_evolsoft_ec_problem_rcpsp_individualService
component "com.evolsoft.ec.problem.rcpsp.template\n1 types" as M_com_evolsoft_ec_problem_rcpsp_template
component "com.evolsoft.ec.pso\n29 types" as M_com_evolsoft_ec_pso
component "com.evolsoft.ec.resource\n5 types" as M_com_evolsoft_ec_resource
component "com.evolsoft.ec.runtime\n777 types" as M_com_evolsoft_ec_runtime
component "com.evolsoft.ec.sa\n28 types" as M_com_evolsoft_ec_sa
component "com.evolsoft.ec.tool.mail\n3 types" as M_com_evolsoft_ec_tool_mail
component "com.evolsoft.ec.toolbox.GanttChart\n68 types" as M_com_evolsoft_ec_toolbox_GanttChart
component "com.evolsoft.ec.toolbox.mrf\n27 types" as M_com_evolsoft_ec_toolbox_mrf
component "com.evolsoft.ec.toolbox.notation\n23 types" as M_com_evolsoft_ec_toolbox_notation
component "com.evolsoft.ec.toolbox.policyTree\n25 types" as M_com_evolsoft_ec_toolbox_policyTree
component "com.evolsoft.ec.toolbox.styles\n12 types" as M_com_evolsoft_ec_toolbox_styles
component "com.evolsoft.ec.ui\n100 types" as M_com_evolsoft_ec_ui
component "com.evolsoft.ec.ui.EditorEx\n4 types" as M_com_evolsoft_ec_ui_EditorEx
component "com.evolsoft.ec.ui.control\n8 types" as M_com_evolsoft_ec_ui_control
component "com.evolsoft.ec.ui.simulation\n25 types" as M_com_evolsoft_ec_ui_simulation
component "com.evolsoft.ec.uiExtension\n19 types" as M_com_evolsoft_ec_uiExtension
component "com.evolsoft.fjsp2.individualServiceBase\n23 types" as M_com_evolsoft_fjsp2_individualServiceBase
component "com.evolsoft.problem.fjsp2.adapter\n30 types" as M_com_evolsoft_problem_fjsp2_adapter
component "com.evolsoft.problem.fjsp2.adaptrerBase\n18 types" as M_com_evolsoft_problem_fjsp2_adaptrerBase
component "com.evolsoft.problem.fjsp2.ecTemplate\n1 types" as M_com_evolsoft_problem_fjsp2_ecTemplate
component "com.evolsoft.problem.fjsp2.individualService\n19 types" as M_com_evolsoft_problem_fjsp2_individualService
component "com.evolsoft.problem.fjsp2.model\n139 types" as M_com_evolsoft_problem_fjsp2_model
component "com.evolsoft.problem.fjsp2.psoInvidualService\n8 types" as M_com_evolsoft_problem_fjsp2_psoInvidualService
component "com.evosoft.assmnt\n13 types" as M_com_evosoft_assmnt
component "ec.evolsoft.ec.solutionViewer\n5 types" as M_ec_evolsoft_ec_solutionViewer
component "org.jfreechart_v1_0_13\n1 types" as M_org_jfreechart_v1_0_13
component "xstream_v1_3_1\n1 types" as M_xstream_v1_3_1

M_com_evolsoft_ec_runtime ..> M_com_evolsoft_core : 241
M_com_evolsoft_ec_ui ..> M_com_evolsoft_ec_runtime : 44
M_com_evolsoft_ec_ga_tool ..> M_com_evolsoft_ec_runtime : 20
M_com_evolsoft_ec_msga_tool ..> M_com_evolsoft_ec_runtime : 20
M_com_evolsoft_ec_problem_rcpsp ..> M_com_evolsoft_core : 20
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_ec_runtime : 19
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_fjsp2_individualServiceBase : 19
M_com_evolsoft_problem_fjsp2_adapter ..> M_com_evolsoft_ec_runtime : 18
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_ec_runtime : 17
M_com_evolsoft_ec_ui ..> M_com_evolsoft_core : 17
M_com_evolsoft_problem_fjsp2_adaptrerBase ..> M_com_evolsoft_ec_runtime : 17
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_ec_problem_rcpsp : 16
M_com_evolsoft_ec_pso ..> M_com_evolsoft_ec_runtime : 15
M_com_evolsoft_problem_fjsp2_adapter ..> M_com_evolsoft_ec_toolbox_GanttChart : 13
M_com_evolsoft_problem_fjsp2_adaptrerBase ..> M_com_evolsoft_ec_toolbox_GanttChart : 13
M_com_evolsoft_ec_sa ..> M_com_evolsoft_ec_runtime : 12
M_com_evolsoft_ec_toolbox_mrf ..> M_com_evolsoft_core : 12
M_cn_haolab_problem_fjsp_model ..> M_com_evolsoft_core : 11
M_com_evolsoft_fjsp2_individualServiceBase ..> M_com_evolsoft_ec_runtime : 11
M_com_evolsoft_problem_fjsp2_psoInvidualService ..> M_com_evolsoft_ec_pso : 11
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_ec_pbil : 10
M_com_evolsoft_ec_toolbox_GanttChart ..> M_com_evolsoft_ec_runtime : 10
M_com_evolsoft_problem_fjsp2_model ..> M_com_evolsoft_core : 9
M_com_evolsoft_ec_eda ..> M_com_evolsoft_ec_runtime : 8
M_com_evolsoft_ec_msga_tool ..> M_com_evolsoft_core : 8
M_com_evolsoft_ec_toolbox_mrf ..> M_com_evolsoft_ec_runtime : 8
M_com_evolsoft_problem_fjsp2_adapter ..> M_com_evolsoft_core : 8
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_ec_runtime : 8
M_com_evolsoft_ec_chart ..> M_com_evolsoft_core : 7
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_ec_toolbox_styles : 7
M_com_evolsoft_ec_uiExtension ..> M_com_evolsoft_ec_runtime : 7
M_com_evolsoft_problem_fjsp2_psoInvidualService ..> M_com_evolsoft_ec_runtime : 7
M_com_evolsoft_ec_pbil_testSuite ..> M_com_evolsoft_ec_pbil : 6
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_fjsp2_individualServiceBase : 6
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_problem_fjsp2_model : 6
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_ec_eda : 5
M_com_evolsoft_ec_problem_rcpsp ..> M_com_evolsoft_ec_runtime : 5
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_ec_pbil : 5
M_com_evolsoft_problem_fjsp2_psoInvidualService ..> M_com_evolsoft_fjsp2_individualServiceBase : 5
M_com_evosoft_assmnt ..> M_com_evolsoft_ec_runtime : 5
M_com_evolsoft_ec_chart ..> M_com_evolsoft_ec_runtime : 4
M_com_evolsoft_ec_toolbox_GanttChart ..> M_com_evolsoft_ec_toolbox_styles : 4
M_com_evolsoft_fjsp2_individualServiceBase ..> M_com_evolsoft_ec_toolbox_GanttChart : 4
M_com_evosoft_assmnt ..> M_com_evolsoft_core : 4
M_com_evolsoft_bayesian ..> M_com_evolsoft_core : 3
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_ec_ui_control : 3
M_com_evolsoft_ec_problem_rcpsp_individualService ..> M_com_evolsoft_core : 3
M_com_evolsoft_ec_toolbox_GanttChart ..> M_com_evolsoft_core : 3
M_com_evolsoft_ec_toolbox_policyTree ..> M_com_evolsoft_ec_toolbox_styles : 3
M_com_evolsoft_ec_ui_EditorEx ..> M_com_evolsoft_ec_toolbox_GanttChart : 3
M_com_evolsoft_fjsp2_individualServiceBase ..> M_com_evolsoft_ec_toolbox_mrf : 3
M_com_evolsoft_fjsp2_individualServiceBase ..> M_com_evolsoft_problem_fjsp2_model : 3
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_core : 3
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_ec_toolbox_mrf : 3
M_ec_evolsoft_ec_solutionViewer ..> M_com_evolsoft_core : 3
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_ec_toolbox_notation : 2
M_com_evolsoft_ec_pbil_testSuite ..> M_com_evolsoft_ec_toolbox_styles : 2
M_com_evolsoft_ec_pbil_testSuite ..> M_com_evolsoft_ec_ui_control : 2
M_com_evolsoft_ec_problem_rcpsp ..> M_com_evolsoft_ec_toolbox_GanttChart : 2
M_com_evolsoft_ec_toolbox_policyTree ..> M_com_evolsoft_ec_toolbox_notation : 2
M_com_evolsoft_ec_uiExtension ..> M_com_evolsoft_ec_ui : 2
M_com_evolsoft_fjsp2_individualServiceBase ..> M_com_evolsoft_ec_pbil : 2
M_com_evolsoft_problem_fjsp2_adapter ..> M_com_evolsoft_problem_fjsp2_model : 2
M_com_evolsoft_problem_fjsp2_adaptrerBase ..> M_com_evolsoft_core : 2
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_problem_fjsp2_adapter : 2
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_problem_fjsp2_model : 2
M_com_evolsoft_problem_fjsp2_model ..> M_com_evolsoft_ec_runtime : 2
M_com_evolsoft_ec_pbil ..> M_com_evolsoft_core : 1
M_com_evolsoft_ec_pbil_testSuite ..> M_com_evolsoft_ec_runtime : 1
M_com_evolsoft_ec_problem_rcpsp ..> M_com_evolsoft_problem_fjsp2_model : 1
M_com_evolsoft_ec_toolbox_GanttChart ..> M_com_evolsoft_ec_ui_control : 1
M_com_evolsoft_problem_fjsp2_adaptrerBase ..> M_com_evolsoft_problem_fjsp2_adapter : 1
M_com_evolsoft_problem_fjsp2_individualService ..> M_com_evolsoft_problem_fjsp2_adaptrerBase : 1
@enduml
