@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: cn.haolab.problem.fjsp.model

interface "CostControlProvider" as C_com_evolsoft_problem_decision_CostControlProvider
enum "CostMode" as C_com_evolsoft_problem_decision_CostMode
interface "DecisionAttributes" as C_com_evolsoft_problem_decision_DecisionAttributes
interface "DecisionBase" as C_com_evolsoft_problem_decision_DecisionBase
interface "DecisionContext" as C_com_evolsoft_problem_decision_DecisionContext
interface "DecisionFactory" as C_com_evolsoft_problem_decision_DecisionFactory
interface "DecisionPolicy" as C_com_evolsoft_problem_decision_DecisionPolicy
interface "DisassembleAction" as C_com_evolsoft_problem_decision_DisassembleAction
interface "IDecisionGeneValueFactory" as C_com_evolsoft_problem_decision_IDecisionGeneValueFactory
interface "IFJSP2Solution" as C_com_evolsoft_problem_decision_IFJSP2Solution
interface "IGeneValue" as C_com_evolsoft_problem_decision_IGeneValue
interface "IOperationDecisionItem" as C_com_evolsoft_problem_decision_IOperationDecisionItem
interface "JobStatus" as C_com_evolsoft_problem_decision_JobStatus
interface "MachineDecision" as C_com_evolsoft_problem_decision_MachineDecision
interface "MachineDecisionPolicy" as C_com_evolsoft_problem_decision_MachineDecisionPolicy
interface "MachineSeizer" as C_com_evolsoft_problem_decision_MachineSeizer
interface "MachineStatus" as C_com_evolsoft_problem_decision_MachineStatus
interface "MachineStatusManager" as C_com_evolsoft_problem_decision_MachineStatusManager
interface "MachineStorage" as C_com_evolsoft_problem_decision_MachineStorage
interface "OperationDecision" as C_com_evolsoft_problem_decision_OperationDecision
interface "OperationDecisionFactory" as C_com_evolsoft_problem_decision_OperationDecisionFactory
interface "OperationDecisionPolicy" as C_com_evolsoft_problem_decision_OperationDecisionPolicy
interface "ProductDecision" as C_com_evolsoft_problem_decision_ProductDecision
interface "ResDecisionPolicy" as C_com_evolsoft_problem_decision_ResDecisionPolicy
class "ResourceBox" as C_com_evolsoft_problem_decision_ResourceBox
interface "ResourceDecision" as C_com_evolsoft_problem_decision_ResourceDecision
interface "ResourceDecisionList" as C_com_evolsoft_problem_decision_ResourceDecisionList
interface "ResourceDecisionSummary" as C_com_evolsoft_problem_decision_ResourceDecisionSummary
interface "ResourceSeizer" as C_com_evolsoft_problem_decision_ResourceSeizer
interface "ResourceStatus" as C_com_evolsoft_problem_decision_ResourceStatus
interface "ResourceStatusManager" as C_com_evolsoft_problem_decision_ResourceStatusManager
interface "ResourceStorage" as C_com_evolsoft_problem_decision_ResourceStorage
interface "ResourceStorageDecision" as C_com_evolsoft_problem_decision_ResourceStorageDecision
interface "StatusBase" as C_com_evolsoft_problem_decision_StatusBase
enum "StatusFlag" as C_com_evolsoft_problem_decision_StatusFlag
interface "Storage" as C_com_evolsoft_problem_decision_Storage
class "Assignment" as C_com_evolsoft_problem_decision_analysis_Assignment
class "CPInsertableTimeWindow" as C_com_evolsoft_problem_decision_analysis_CPInsertableTimeWindow
class "CriticalPath" as C_com_evolsoft_problem_decision_analysis_CriticalPath
interface "IAssignment" as C_com_evolsoft_problem_decision_analysis_IAssignment
class "OperationMovingTabuList" as C_com_evolsoft_problem_decision_analysis_OperationMovingTabuList
class "PointF" as C_com_evolsoft_problem_decision_analysis_PointF
class "RemovingItem" as C_com_evolsoft_problem_decision_analysis_RemovingItem
class "CostControlProviderImpl" as C_com_evolsoft_problem_decision_impl_CostControlProviderImpl
class "DecisionBaseImpl" as C_com_evolsoft_problem_decision_impl_DecisionBaseImpl
class "DecisionContextImpl" as C_com_evolsoft_problem_decision_impl_DecisionContextImpl
class "DecisionFactoryImpl" as C_com_evolsoft_problem_decision_impl_DecisionFactoryImpl
class "DecisionPolicyImpl" as C_com_evolsoft_problem_decision_impl_DecisionPolicyImpl
class "DisassembleActionImpl" as C_com_evolsoft_problem_decision_impl_DisassembleActionImpl
class "FJSP2Solution" as C_com_evolsoft_problem_decision_impl_FJSP2Solution
class "FatalErrorException" as C_com_evolsoft_problem_decision_impl_FatalErrorException
class "Header" as C_com_evolsoft_problem_decision_impl_Header
class "IdleSpanList" as C_com_evolsoft_problem_decision_impl_IdleSpanList
class "Idlespan" as C_com_evolsoft_problem_decision_impl_Idlespan
class "JobStatusImpl" as C_com_evolsoft_problem_decision_impl_JobStatusImpl
enum "LinkType" as C_com_evolsoft_problem_decision_impl_LinkType
class "MachineDecisionImpl" as C_com_evolsoft_problem_decision_impl_MachineDecisionImpl
class "MachineDecisionPolicyImpl" as C_com_evolsoft_problem_decision_impl_MachineDecisionPolicyImpl
class "MachineSeizerImpl" as C_com_evolsoft_problem_decision_impl_MachineSeizerImpl
class "MachineStatusImpl" as C_com_evolsoft_problem_decision_impl_MachineStatusImpl
class "MachineStatusManagerImpl" as C_com_evolsoft_problem_decision_impl_MachineStatusManagerImpl
class "MachineStorageImpl" as C_com_evolsoft_problem_decision_impl_MachineStorageImpl
class "Node" as C_com_evolsoft_problem_decision_impl_Node
class "NotSupportableException" as C_com_evolsoft_problem_decision_impl_NotSupportableException
class "OperationDecisionDummy" as C_com_evolsoft_problem_decision_impl_OperationDecisionDummy
class "OperationDecisionHeader" as C_com_evolsoft_problem_decision_impl_OperationDecisionHeader
class "OperationDecisionImpl" as C_com_evolsoft_problem_decision_impl_OperationDecisionImpl
class "OperationDecisionItem" as C_com_evolsoft_problem_decision_impl_OperationDecisionItem
class "OperationDecisionLinkedList" as C_com_evolsoft_problem_decision_impl_OperationDecisionLinkedList
class "OperationDecisionPolicyImpl" as C_com_evolsoft_problem_decision_impl_OperationDecisionPolicyImpl
class "OperationDecisionTailer" as C_com_evolsoft_problem_decision_impl_OperationDecisionTailer
class "ProductDecisionImpl" as C_com_evolsoft_problem_decision_impl_ProductDecisionImpl
class "ResDecisionEntry" as C_com_evolsoft_problem_decision_impl_ResDecisionEntry
class "ResourceDecisionImpl" as C_com_evolsoft_problem_decision_impl_ResourceDecisionImpl
class "ResourceDecisionListImpl" as C_com_evolsoft_problem_decision_impl_ResourceDecisionListImpl
class "ResourceDecisionManager" as C_com_evolsoft_problem_decision_impl_ResourceDecisionManager
interface "ResourceDecisionSnapshot" as C_com_evolsoft_problem_decision_impl_ResourceDecisionSnapshot
class "ResourceDecsionSummaryImpl" as C_com_evolsoft_problem_decision_impl_ResourceDecsionSummaryImpl
class "ResourceSeizerImpl" as C_com_evolsoft_problem_decision_impl_ResourceSeizerImpl
class "ResourceStatusImpl" as C_com_evolsoft_problem_decision_impl_ResourceStatusImpl
class "ResourceStatusManagerImpl" as C_com_evolsoft_problem_decision_impl_ResourceStatusManagerImpl
class "ResourceStorageDecisionImpl" as C_com_evolsoft_problem_decision_impl_ResourceStorageDecisionImpl
class "ResourceStorageImpl" as C_com_evolsoft_problem_decision_impl_ResourceStorageImpl
class "SequencePoint" as C_com_evolsoft_problem_decision_impl_SequencePoint
class "StatusBaseImpl" as C_com_evolsoft_problem_decision_impl_StatusBaseImpl
class "StatusErrorException" as C_com_evolsoft_problem_decision_impl_StatusErrorException
class "StorageImpl" as C_com_evolsoft_problem_decision_impl_StorageImpl
class "Tail" as C_com_evolsoft_problem_decision_impl_Tail
class "initSequence" as C_com_evolsoft_problem_decision_initSequence
interface "AbstractResource" as C_com_evolsoft_problem_fjsp_FJSPModel_AbstractResource
interface "ConstrainRelation" as C_com_evolsoft_problem_fjsp_FJSPModel_ConstrainRelation
interface "FJSPModel" as C_com_evolsoft_problem_fjsp_FJSPModel_FJSPModel
interface "FJSPModelFactory" as C_com_evolsoft_problem_fjsp_FJSPModel_FJSPModelFactory
interface "FJSPModelPackage" as C_com_evolsoft_problem_fjsp_FJSPModel_FJSPModelPackage
class "FJSPSolutionXMLConverter" as C_com_evolsoft_problem_fjsp_FJSPModel_FJSPSolutionXMLConverter
interface "IFJSP2ModelProvider" as C_com_evolsoft_problem_fjsp_FJSPModel_IFJSP2ModelProvider
interface "Identifying" as C_com_evolsoft_problem_fjsp_FJSPModel_Identifying
interface "Machine" as C_com_evolsoft_problem_fjsp_FJSPModel_Machine
interface "MachineItem" as C_com_evolsoft_problem_fjsp_FJSPModel_MachineItem
interface "MachineManager" as C_com_evolsoft_problem_fjsp_FJSPModel_MachineManager
interface "MachiningConfiguration" as C_com_evolsoft_problem_fjsp_FJSPModel_MachiningConfiguration
interface "ManufactureFactory" as C_com_evolsoft_problem_fjsp_FJSPModel_ManufactureFactory
interface "Operation" as C_com_evolsoft_problem_fjsp_FJSPModel_Operation
interface "Product" as C_com_evolsoft_problem_fjsp_FJSPModel_Product
interface "ProductCategory" as C_com_evolsoft_problem_fjsp_FJSPModel_ProductCategory
enum "RelationType" as C_com_evolsoft_problem_fjsp_FJSPModel_RelationType
interface "Resource" as C_com_evolsoft_problem_fjsp_FJSPModel_Resource
interface "ResourceCategory" as C_com_evolsoft_problem_fjsp_FJSPModel_ResourceCategory
interface "ResourceConstrain" as C_com_evolsoft_problem_fjsp_FJSPModel_ResourceConstrain
interface "ResourceItem" as C_com_evolsoft_problem_fjsp_FJSPModel_ResourceItem
interface "ResourceManager" as C_com_evolsoft_problem_fjsp_FJSPModel_ResourceManager
class "FJSP2DataProvider" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSP2DataProvider
class "FJSPCSVReader" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSPCSVReader
interface "IFJSP2DataProvider" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IFJSP2DataProvider
class "IdentifiyingIndeices" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IdentifiyingIndeices
class "AbstractResourceImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_AbstractResourceImpl
class "FJSPModelFactoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelFactoryImpl
class "FJSPModelImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelImpl
class "IdentifyingImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_IdentifyingImpl
class "MachineImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineImpl
class "MachineItemImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineItemImpl
class "MachineManagerImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineManagerImpl
class "MachiningConfigurationImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachiningConfigurationImpl
class "ManufactureFactoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ManufactureFactoryImpl
class "OperationImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_OperationImpl
class "ProductCategoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductCategoryImpl
class "ProductImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductImpl
class "ResourceCategoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceCategoryImpl
class "ResourceConstrainImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceConstrainImpl
class "ResourceImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceImpl
class "ResourceItemImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceItemImpl
class "ResourceManagerImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceManagerImpl
class "FJSPDecoder" as C_com_evolsoft_problem_fjsp_decoding_FJSPDecoder
class "ProductRouteVisitor" as C_com_evolsoft_problem_fjsp_decoding_ProductRouteVisitor

C_com_evolsoft_problem_decision_DecisionContext <|.. C_com_evolsoft_problem_decision_impl_DecisionContextImpl
C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IFJSP2DataProvider <|.. C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSP2DataProvider
C_com_evolsoft_problem_decision_impl_DecisionBaseImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_impl_DecisionPolicyImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_impl_MachineSeizerImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_impl_MachineStatusManagerImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_impl_ResourceSeizerImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_impl_ResourceStatusManagerImpl --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_decision_initSequence --> C_com_evolsoft_problem_decision_DecisionContext
C_com_evolsoft_problem_fjsp_FJSPModel_impl_ManufactureFactoryImpl --> C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IdentifiyingIndeices
C_com_evolsoft_problem_fjsp_decoding_FJSPDecoder --> C_com_evolsoft_problem_decision_DecisionContext
@enduml
