@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.ui

class "ECPlatformUI" as C_com_evolsoft_ec_ui_ECPlatformUI
class "ECUIImages" as C_com_evolsoft_ec_ui_ECUIImages
class "ECUIPlugIn" as C_com_evolsoft_ec_ui_ECUIPlugIn
class "FillWidthLayout" as C_com_evolsoft_ec_ui_FillWidthLayout
interface "LineChart" as C_com_evolsoft_ec_ui_chart_LineChart
interface "LineChart" as C_com_evolsoft_ec_ui_chart_copy_LineChart
class "ECConfigurationEditor" as C_com_evolsoft_ec_ui_configEditor_ECConfigurationEditor
class "ECExperimentSettingPage" as C_com_evolsoft_ec_ui_configEditor_ECExperimentSettingPage
class "ECFormpageBase" as C_com_evolsoft_ec_ui_configEditor_ECFormpageBase
class "ECOperatorPage" as C_com_evolsoft_ec_ui_configEditor_ECOperatorPage
class "OpenSolutionEditorAction" as C_com_evolsoft_ec_ui_configEditor_OpenSolutionEditorAction
class "OverviewPage" as C_com_evolsoft_ec_ui_configEditor_OverviewPage
class "ProfilePage" as C_com_evolsoft_ec_ui_configEditor_ProfilePage
class "RunAction" as C_com_evolsoft_ec_ui_configEditor_RunAction
class "SimpleDocumentProvider" as C_com_evolsoft_ec_ui_configEditor_SimpleDocumentProvider
class "SolutionDescriptorInput" as C_com_evolsoft_ec_ui_configEditor_SolutionDescriptorInput
interface "that" as C_com_evolsoft_ec_ui_configEditor_that
class "CheckAllAction" as C_com_evolsoft_ec_ui_editor_actions_CheckAllAction
class "EnableAction" as C_com_evolsoft_ec_ui_editor_actions_EnableAction
class "ShowParetoAction" as C_com_evolsoft_ec_ui_editor_actions_ShowParetoAction
class "ECAppContentProviderBase" as C_com_evolsoft_ec_ui_explorer_ECAppContentProviderBase
class "ECAppExploerContentProvider" as C_com_evolsoft_ec_ui_explorer_ECAppExploerContentProvider
class "ECAppExplorer" as C_com_evolsoft_ec_ui_explorer_ECAppExplorer
class "OpenMonitorViewHandler" as C_com_evolsoft_ec_ui_explorer_OpenMonitorViewHandler
class "SampleHandler" as C_com_evolsoft_ec_ui_handlers_SampleHandler
class "AbstractECStubViewPage" as C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage
class "DashboradPage" as C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
class "ECTextEditor" as C_com_evolsoft_ec_ui_monitorEditor_ECTextEditor
class "GeneValueTracePage" as C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
class "GeneValueViewerSorter" as C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
interface "IECApplicationMonitorProvider" as C_com_evolsoft_ec_ui_monitorEditor_IECApplicationMonitorProvider
class "MonitorEditor" as C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor
class "MonitorPartInput" as C_com_evolsoft_ec_ui_monitorEditor_MonitorPartInput
class "RunAction" as C_com_evolsoft_ec_ui_monitorEditor_RunAction
class "TreeViewEx" as C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx
class "AgeColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_AgeColumnLabelProvider
class "BenchmarkContentProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
class "BenchmarkLabelViewProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkLabelViewProvider
class "ECAppContentProviderBase" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppContentProviderBase
class "ECAppPartitionContentProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
class "FitnessColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_FitnessColumnLabelProvider
class "GeneValueColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_GeneValueColumnLabelProvider
class "ObjectiveColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ObjectiveColumnLabelProvider
class "SequenceColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_SequenceColumnLabelProvider
enum "SortItemType" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_SortItemType
interface "that" as C_com_evolsoft_ec_ui_monitorEditor_that
class "BenchmarkSorter" as C_com_evolsoft_ec_ui_page_BenchmarkSorter
class "DecisionItemFilterDialog" as C_com_evolsoft_ec_ui_page_DecisionItemFilterDialog
class "DecisionValueDialog" as C_com_evolsoft_ec_ui_page_DecisionValueDialog
class "ECActionSection" as C_com_evolsoft_ec_ui_page_ECActionSection
class "ECApplicationPageBase" as C_com_evolsoft_ec_ui_page_ECApplicationPageBase
class "GeneValueViewFilter" as C_com_evolsoft_ec_ui_page_GeneValueViewFilter
interface "IECApplicationView" as C_com_evolsoft_ec_ui_page_IECApplicationView
interface "IFreezable" as C_com_evolsoft_ec_ui_page_IFreezable
class "MasterContentProvider" as C_com_evolsoft_ec_ui_page_MasterContentProvider
class "MasterLabelProvider" as C_com_evolsoft_ec_ui_page_MasterLabelProvider
class "MonitorBasePage" as C_com_evolsoft_ec_ui_page_MonitorBasePage
class "MonitorItemViewPage" as C_com_evolsoft_ec_ui_page_MonitorItemViewPage
class "PBDataDaigramPage" as C_com_evolsoft_ec_ui_page_PBDataDaigramPage
class "SolutionDescriptorBlock" as C_com_evolsoft_ec_ui_page_SolutionDescriptorBlock
class "SolutionDialog" as C_com_evolsoft_ec_ui_page_SolutionDialog
class "SpeciesSelectionAction" as C_com_evolsoft_ec_ui_page_SpeciesSelectionAction
class "ECExtensionAction" as C_com_evolsoft_ec_ui_page_actions_ECExtensionAction
class "ObjectiveViewSection" as C_com_evolsoft_ec_ui_page_control_ObjectiveViewSection
class "ECConfigurationPerspectiveFactory" as C_com_evolsoft_ec_ui_preferences_ECConfigurationPerspectiveFactory
class "ECExperimentPerspective" as C_com_evolsoft_ec_ui_preferences_ECExperimentPerspective
class "ExperimentDBPerferencePage" as C_com_evolsoft_ec_ui_preferences_ExperimentDBPerferencePage
class "MonitorPreferencePage" as C_com_evolsoft_ec_ui_preferences_MonitorPreferencePage
class "ProfilePerferencePage" as C_com_evolsoft_ec_ui_preferences_ProfilePerferencePage
class "ECSolutionExplorer" as C_com_evolsoft_ec_ui_view_ECSolutionExplorer
interface "IFigureExporter" as C_com_evolsoft_ec_ui_view_IFigureExporter
interface "PluginResourceProvider" as C_com_evolsoft_ec_ui_view_PluginResourceProvider
class "ResourceManager" as C_com_evolsoft_ec_ui_view_ResourceManager
class "ResultExporter" as C_com_evolsoft_ec_ui_view_ResultExporter
class "RunnerSetting" as C_com_evolsoft_ec_ui_view_RunnerSetting
class "SWTResourceManager" as C_com_evolsoft_ec_ui_view_SWTResourceManager
class "SolutionConfigLabelProvider" as C_com_evolsoft_ec_ui_view_SolutionConfigLabelProvider
class "TreeObject" as C_com_evolsoft_ec_ui_view_TreeObject
class "TreeParent" as C_com_evolsoft_ec_ui_view_TreeParent
class "ViewContentProvider" as C_com_evolsoft_ec_ui_view_ViewContentProvider
class "ShowParetoCommand" as C_com_evolsoft_ec_ui_view_actions_ShowParetoCommand
class "TraceObjectiveAction" as C_com_evolsoft_ec_ui_view_actions_TraceObjectiveAction
class "ContentProvider" as C_com_evolsoft_ec_ui_wizards_ContentProvider
class "ECConatinerPage" as C_com_evolsoft_ec_ui_wizards_ECConatinerPage
class "ECExperimentPage" as C_com_evolsoft_ec_ui_wizards_ECExperimentPage
class "ECProjectSetting" as C_com_evolsoft_ec_ui_wizards_ECProjectSetting
class "ECSettingWizardPage" as C_com_evolsoft_ec_ui_wizards_ECSettingWizardPage
class "ECTemplateWizardPage" as C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
interface "IECNewWizard" as C_com_evolsoft_ec_ui_wizards_IECNewWizard
class "NewApproachWizard" as C_com_evolsoft_ec_ui_wizards_NewApproachWizard
class "NewECProjectWizard" as C_com_evolsoft_ec_ui_wizards_NewECProjectWizard
class "ObjectiveCustomPage" as C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
class "TableLabelProvider" as C_com_evolsoft_ec_ui_wizards_TableLabelProvider
class "ECTemplateContentProvider" as C_com_evolsoft_ec_ui_wizards_provider_ECTemplateContentProvider
class "ECTemplateLabelProvider" as C_com_evolsoft_ec_ui_wizards_provider_ECTemplateLabelProvider
class "SolutionCategoryItem" as C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
class "SolutionTemplateItem" as C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem
interface "PluginResourceProvider (com.evolsoft.ec.ui)" as C_org_eclipse_wb_swt_PluginResourceProvider__dup4
class "ResourceManager (com.evolsoft.ec.ui)" as C_org_eclipse_wb_swt_ResourceManager__dup4
class "SWTResourceManager (com.evolsoft.ec.ui)" as C_org_eclipse_wb_swt_SWTResourceManager__dup4

C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_ECExperimentSettingPage
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_OverviewPage
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_ProfilePage
C_com_evolsoft_ec_ui_explorer_ECAppContentProviderBase <|-- C_com_evolsoft_ec_ui_explorer_ECAppExploerContentProvider
C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage <|-- C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage <|-- C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppContentProviderBase <|-- C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
C_com_evolsoft_ec_ui_page_IFreezable <|-- C_com_evolsoft_ec_ui_page_IECApplicationView
C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage <|-- C_com_evolsoft_ec_ui_page_MonitorBasePage
C_com_evolsoft_ec_ui_view_SWTResourceManager <|-- C_com_evolsoft_ec_ui_view_ResourceManager
C_com_evolsoft_ec_ui_view_TreeObject <|-- C_com_evolsoft_ec_ui_view_TreeParent
C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem <|-- C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
C_com_evolsoft_ec_ui_page_IFreezable <|.. C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage
C_com_evolsoft_ec_ui_page_IFreezable <|.. C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_page_IFreezable <|.. C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_page_IECApplicationView <|.. C_com_evolsoft_ec_ui_page_ECApplicationPageBase
C_com_evolsoft_ec_ui_page_IFreezable <|.. C_com_evolsoft_ec_ui_page_MonitorItemViewPage
C_com_evolsoft_ec_ui_page_IFreezable <|.. C_com_evolsoft_ec_ui_page_PBDataDaigramPage
C_com_evolsoft_ec_ui_wizards_IECNewWizard <|.. C_com_evolsoft_ec_ui_wizards_NewApproachWizard
C_com_evolsoft_ec_ui_configEditor_ECConfigurationEditor --> C_com_evolsoft_ec_ui_configEditor_RunAction
C_com_evolsoft_ec_ui_configEditor_ECExperimentSettingPage --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase --> C_com_evolsoft_ec_ui_configEditor_SolutionDescriptorInput
C_com_evolsoft_ec_ui_configEditor_ECOperatorPage --> C_com_evolsoft_ec_ui_page_SolutionDescriptorBlock
C_com_evolsoft_ec_ui_configEditor_OverviewPage --> C_com_evolsoft_ec_ui_editor_actions_CheckAllAction
C_com_evolsoft_ec_ui_configEditor_that --> C_com_evolsoft_ec_ui_configEditor_RunAction
C_com_evolsoft_ec_ui_explorer_ECAppExplorer --> C_com_evolsoft_ec_ui_explorer_ECAppExploerContentProvider
C_com_evolsoft_ec_ui_monitorEditor_DashboradPage --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_DashboradPage --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
C_com_evolsoft_ec_ui_monitorEditor_DashboradPage --> C_com_evolsoft_ec_ui_page_SpeciesSelectionAction
C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage --> C_com_evolsoft_ec_ui_page_GeneValueViewFilter
C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage --> C_com_evolsoft_ec_ui_page_actions_ECExtensionAction
C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_SortItemType
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_configEditor_ProfilePage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_RunAction
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_page_MonitorItemViewPage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_page_PBDataDaigramPage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_configEditor_ProfilePage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_page_MonitorItemViewPage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_page_PBDataDaigramPage
C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx --> C_com_evolsoft_ec_ui_page_SpeciesSelectionAction
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_configEditor_ProfilePage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_RunAction
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_page_MonitorItemViewPage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_page_PBDataDaigramPage
C_com_evolsoft_ec_ui_page_DecisionItemFilterDialog --> C_com_evolsoft_ec_ui_page_GeneValueViewFilter
C_com_evolsoft_ec_ui_page_actions_ECExtensionAction --> C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor
C_com_evolsoft_ec_ui_view_ECSolutionExplorer --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_view_ECSolutionExplorer --> C_com_evolsoft_ec_ui_view_RunnerSetting
C_com_evolsoft_ec_ui_view_ECSolutionExplorer --> C_com_evolsoft_ec_ui_view_TreeParent
C_com_evolsoft_ec_ui_view_ResourceManager --> C_com_evolsoft_ec_ui_view_PluginResourceProvider
C_com_evolsoft_ec_ui_view_SolutionConfigLabelProvider --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_view_SolutionConfigLabelProvider --> C_com_evolsoft_ec_ui_view_RunnerSetting
C_com_evolsoft_ec_ui_view_SolutionConfigLabelProvider --> C_com_evolsoft_ec_ui_view_TreeParent
C_com_evolsoft_ec_ui_view_TreeObject --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_view_TreeObject --> C_com_evolsoft_ec_ui_view_RunnerSetting
C_com_evolsoft_ec_ui_view_TreeObject --> C_com_evolsoft_ec_ui_view_TreeParent
C_com_evolsoft_ec_ui_view_TreeParent --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_view_TreeParent --> C_com_evolsoft_ec_ui_view_RunnerSetting
C_com_evolsoft_ec_ui_view_ViewContentProvider --> C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
C_com_evolsoft_ec_ui_view_ViewContentProvider --> C_com_evolsoft_ec_ui_view_RunnerSetting
C_com_evolsoft_ec_ui_view_ViewContentProvider --> C_com_evolsoft_ec_ui_view_TreeParent
C_com_evolsoft_ec_ui_wizards_ContentProvider --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECConatinerPage --> C_com_evolsoft_ec_ui_wizards_IECNewWizard
C_com_evolsoft_ec_ui_wizards_ECExperimentPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECSettingWizardPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage --> C_com_evolsoft_ec_ui_wizards_provider_ECTemplateContentProvider
C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage --> C_com_evolsoft_ec_ui_wizards_provider_ECTemplateLabelProvider
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECConatinerPage
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage --> C_com_evolsoft_ec_ui_wizards_ContentProvider
C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_TableLabelProvider --> C_com_evolsoft_ec_ui_wizards_ContentProvider
C_com_evolsoft_ec_ui_wizards_TableLabelProvider --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_provider_ECTemplateContentProvider --> C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem --> C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
@enduml
