@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.pbil

interface "IPBILAdapter" as C_com_evolsoft_ec_pbil_IPBILAdapter
interface "IPBILECStrategy" as C_com_evolsoft_ec_pbil_IPBILECStrategy
class "PBILECStrategy" as C_com_evolsoft_ec_pbil_PBILECStrategy
class "PBILPlugin" as C_com_evolsoft_ec_pbil_PBILPlugin
class "PBFigureVectorsDataProvider" as C_com_evolsoft_ec_pbil_chartView_PBFigureVectorsDataProvider
class "PBMatrixFigureLabelProvider" as C_com_evolsoft_ec_pbil_chartView_PBMatrixFigureLabelProvider
class "PBMatrixMonitorView" as C_com_evolsoft_ec_pbil_chartView_PBMatrixMonitorView
interface "IPMFArcFigure" as C_com_evolsoft_ec_pbil_chartView_figures_IPMFArcFigure
interface "IPMFMatrixFigure" as C_com_evolsoft_ec_pbil_chartView_figures_IPMFMatrixFigure
class "PMFArcFigure" as C_com_evolsoft_ec_pbil_chartView_figures_PMFArcFigure
class "PMFFigureUtils" as C_com_evolsoft_ec_pbil_chartView_figures_PMFFigureUtils
class "PMFMatrixFigure" as C_com_evolsoft_ec_pbil_chartView_figures_PMFMatrixFigure
interface "PMFProfile" as C_com_evolsoft_ec_pbil_chartView_figures_PMFProfile
class "PMFTreeFigure" as C_com_evolsoft_ec_pbil_chartView_figures_PMFTreeFigure
interface "IPBILCFGFactory" as C_com_evolsoft_ec_pbil_configuration_IPBILCFGFactory
interface "IPBILCFGPackage" as C_com_evolsoft_ec_pbil_configuration_IPBILCFGPackage
interface "IPBILConfiguration" as C_com_evolsoft_ec_pbil_configuration_IPBILConfiguration
interface "IPBILConfigurationLoader" as C_com_evolsoft_ec_pbil_configuration_IPBILConfigurationLoader
interface "Literals" as C_com_evolsoft_ec_pbil_configuration_Literals
class "PBILCFGFactory" as C_com_evolsoft_ec_pbil_configuration_impl_PBILCFGFactory
class "PBILCFGPackage" as C_com_evolsoft_ec_pbil_configuration_impl_PBILCFGPackage
class "PBILConfiguration" as C_com_evolsoft_ec_pbil_configuration_impl_PBILConfiguration
class "PBILConfigurationLoader" as C_com_evolsoft_ec_pbil_configuration_impl_PBILConfigurationLoader
class "PBILCFGAdapterFactory" as C_com_evolsoft_ec_pbil_configuration_util_PBILCFGAdapterFactory
class "PBILCFGSwitch" as C_com_evolsoft_ec_pbil_configuration_util_PBILCFGSwitch
class "PBMatrixModelRoot" as C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot
class "PBMatrixTraceModel" as C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
class "PBProbabilityCDFList" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
class "PBProbabilityCDFVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector
class "PBProbabilityPMFList" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
class "PBProbabilityPMFVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
class "PBProbabilityVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector
class "CopyOfProbabilityMatrixBase" as C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase
interface "IMatrixMonitorItem" as C_com_evolsoft_ec_pbil_probability_IMatrixMonitorItem
interface "IProbabilityMatrix" as C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
class "JointProbabilityState" as C_com_evolsoft_ec_pbil_probability_JointProbabilityState
class "MatrixItemInfo" as C_com_evolsoft_ec_pbil_probability_MatrixItemInfo
class "MatrixMonitorItem" as C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem
class "ProbabilityHeader" as C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
class "ProbabilityItem" as C_com_evolsoft_ec_pbil_probability_ProbabilityItem
class "ProbabilityMatrix" as C_com_evolsoft_ec_pbil_probability_ProbabilityMatrix
class "ProbabilityMatrixBase" as C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase
class "ProbabilityVector" as C_com_evolsoft_ec_pbil_probability_ProbabilityVector
class "ProbabilityVectors" as C_com_evolsoft_ec_pbil_probability_ProbabilityVectors
class "ProbalityMatrixArray" as C_com_evolsoft_ec_pbil_probability_ProbalityMatrixArray
class "ECPBILOptimizator" as C_com_evolsoft_ec_pbil_runtime_ECPBILOptimizator
interface "IMarginalProbability" as C_com_evolsoft_ec_pbil_runtime_IMarginalProbability
interface "IPBILOptimizator" as C_com_evolsoft_ec_pbil_runtime_IPBILOptimizator
interface "IPBILOptimizatorDelegate" as C_com_evolsoft_ec_pbil_runtime_IPBILOptimizatorDelegate
class "MarginalProbability" as C_com_evolsoft_ec_pbil_runtime_MarginalProbability
class "PBILGeneItem" as C_com_evolsoft_ec_pbil_runtime_PBILGeneItem
class "PBILIndividualService" as C_com_evolsoft_ec_pbil_runtime_PBILIndividualService
class "HistgramRender" as C_com_evolsoft_ec_pbil_treeViewer_HistgramRender
class "PBMatrixDataProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixDataProvider
class "PBMatrixLabelProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixLabelProvider
class "PBMatrixTestViewer" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer
class "PBMatrixTraceItem" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTraceItem
class "PBMatrixViewer" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer
class "PBVectorsDataProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider
class "ProbabilityMatrixViewPart" as C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart
class "PropertyTipper" as C_com_evolsoft_ec_pbil_treeViewer_PropertyTipper

C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector <|-- C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector <|-- C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
C_com_evolsoft_ec_pbil_probability_ProbabilityItem <|-- C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase <|-- C_com_evolsoft_ec_pbil_probability_ProbabilityMatrix
C_com_evolsoft_ec_pbil_IPBILECStrategy <|.. C_com_evolsoft_ec_pbil_PBILECStrategy
C_com_evolsoft_ec_pbil_chartView_figures_IPMFArcFigure <|.. C_com_evolsoft_ec_pbil_chartView_figures_PMFArcFigure
C_com_evolsoft_ec_pbil_chartView_figures_IPMFMatrixFigure <|.. C_com_evolsoft_ec_pbil_chartView_figures_PMFMatrixFigure
C_com_evolsoft_ec_pbil_configuration_IPBILCFGFactory <|.. C_com_evolsoft_ec_pbil_configuration_impl_PBILCFGFactory
C_com_evolsoft_ec_pbil_configuration_IPBILCFGPackage <|.. C_com_evolsoft_ec_pbil_configuration_impl_PBILCFGPackage
C_com_evolsoft_ec_pbil_configuration_IPBILConfiguration <|.. C_com_evolsoft_ec_pbil_configuration_impl_PBILConfiguration
C_com_evolsoft_ec_pbil_configuration_IPBILConfigurationLoader <|.. C_com_evolsoft_ec_pbil_configuration_impl_PBILConfigurationLoader
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase
C_com_evolsoft_ec_pbil_probability_IMatrixMonitorItem <|.. C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_ProbabilityVectors
C_com_evolsoft_ec_pbil_runtime_IPBILOptimizator <|.. C_com_evolsoft_ec_pbil_runtime_ECPBILOptimizator
C_com_evolsoft_ec_pbil_runtime_IMarginalProbability <|.. C_com_evolsoft_ec_pbil_runtime_MarginalProbability
C_com_evolsoft_ec_pbil_chartView_PBFigureVectorsDataProvider --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot
C_com_evolsoft_ec_pbil_chartView_PBFigureVectorsDataProvider --> C_com_evolsoft_ec_pbil_probability_MatrixItemInfo
C_com_evolsoft_ec_pbil_chartView_PBMatrixMonitorView --> C_com_evolsoft_ec_pbil_chartView_PBFigureVectorsDataProvider
C_com_evolsoft_ec_pbil_chartView_PBMatrixMonitorView --> C_com_evolsoft_ec_pbil_chartView_PBMatrixFigureLabelProvider
C_com_evolsoft_ec_pbil_chartView_figures_PMFArcFigure --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
C_com_evolsoft_ec_pbil_chartView_figures_PMFMatrixFigure --> C_com_evolsoft_ec_pbil_chartView_figures_PMFArcFigure
C_com_evolsoft_ec_pbil_chartView_figures_PMFMatrixFigure --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
C_com_evolsoft_ec_pbil_chartView_figures_PMFTreeFigure --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot
C_com_evolsoft_ec_pbil_configuration_util_PBILCFGAdapterFactory --> C_com_evolsoft_ec_pbil_configuration_IPBILCFGPackage
C_com_evolsoft_ec_pbil_configuration_util_PBILCFGSwitch --> C_com_evolsoft_ec_pbil_configuration_IPBILCFGPackage
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot --> C_com_evolsoft_ec_pbil_probability_MatrixItemInfo
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel --> C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_MatrixItemInfo --> C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem --> C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_ProbabilityVector --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityVector --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_ProbabilityVectors --> C_com_evolsoft_ec_pbil_probability_ProbabilityVector
C_com_evolsoft_ec_pbil_treeViewer_HistgramRender --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixDataProvider --> C_com_evolsoft_ec_pbil_probability_ProbalityMatrixArray
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer --> C_com_evolsoft_ec_pbil_probability_ProbabilityMatrix
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer --> C_com_evolsoft_ec_pbil_probability_ProbalityMatrixArray
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer --> C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTraceItem
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer --> C_com_evolsoft_ec_pbil_treeViewer_HistgramRender
C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot
C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider --> C_com_evolsoft_ec_pbil_probability_MatrixItemInfo
C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart --> C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer
C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart --> C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider
@enduml
