@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.ga.tool

class "OneCutCopyCrossover" as C_com_evolsoft_ec_crossover_OneCutCopyCrossover
class "OneCutCrossover" as C_com_evolsoft_ec_crossover_OneCutCrossover
class "SyntopicTwoCutCrossover" as C_com_evolsoft_ec_crossover_SyntopicTwoCutCrossover
class "TwoCutCrossover" as C_com_evolsoft_ec_crossover_TwoCutCrossover
class "OperationBasedCrossover" as C_com_evolsoft_ec_ecoperation_jsp_OperationBasedCrossover
class "SectionSwapMutation" as C_com_evolsoft_ec_ecoperation_jsp_SectionSwapMutation
class "SwapComparer" as C_com_evolsoft_ec_ecoperation_jsp_SwapComparer
class "SwapMutation4Partition" as C_com_evolsoft_ec_ecoperation_jsp_SwapMutation4Partition
class "Verfier" as C_com_evolsoft_ec_ecoperation_jsp_Verfier
class "ArithmeticalCrossover" as C_com_evolsoft_ec_runtime_ecoperation_ArithmeticalCrossover
class "PartialMapCrossover" as C_com_evolsoft_ec_runtime_ecoperation_PartialMapCrossover
class "PolynomialMutation" as C_com_evolsoft_ec_runtime_ecoperation_PolynomialMutation
class "RandomKeyGeneMutation" as C_com_evolsoft_ec_runtime_ecoperation_RandomKeyGeneMutation
class "SimulatedBinaryCrossover" as C_com_evolsoft_ec_runtime_ecoperation_SimulatedBinaryCrossover
class "TwoCutCrossover" as C_com_evolsoft_ec_runtime_ecoperation_TwoCutCrossover
class "UniformCrossover" as C_com_evolsoft_ec_runtime_ecoperation_UniformCrossover
class "oneCutCrossover" as C_com_evolsoft_ec_runtime_ecoperation_oneCutCrossover
class "ECToolPlugin" as C_com_evolsoft_ec_tool_ECToolPlugin
class "EmigrationAction" as C_com_evolsoft_ec_tool_EmigrationAction
class "FlipMutation" as C_com_evolsoft_ec_tool_FlipMutation
class "InsertMutation" as C_com_evolsoft_ec_tool_InsertMutation

C_com_evolsoft_ec_crossover_OneCutCrossover <|-- C_com_evolsoft_ec_crossover_OneCutCopyCrossover
@enduml
