@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.pbil.testSuite

class "Activator" as C_com_evolsoft_ec_pbil_testsuite_Activator
class "TestMarginalProbability" as C_com_evolsoft_ec_pbil_testsuite_TestMarginalProbability
class "TestProbabilityMatrix" as C_com_evolsoft_ec_pbil_testsuite_TestProbabilityMatrix
class "TestProbabilityVector" as C_com_evolsoft_ec_pbil_testsuite_TestProbabilityVector
class "HistgramLableProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_HistgramLableProviderEx
class "PBMatrixDataProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixDataProviderEx
class "PBMatrixLabelProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixLabelProviderEx
class "PBMatrixTestViewerEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTestViewerEx
class "PBMatrixTraceItemEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx
class "PBMatrixViewerEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixViewerEx
class "StyleOwnerDrawLabelProvider" as C_com_evolsoft_ec_pbil_viewer_refine_StyleOwnerDrawLabelProvider

C_com_evolsoft_ec_pbil_viewer_refine_StyleOwnerDrawLabelProvider <|-- C_com_evolsoft_ec_pbil_viewer_refine_HistgramLableProviderEx
C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTestViewerEx --> C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx
C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx --> C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixViewerEx
@enduml
