@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.problem.fjsp2.psoInvidualService

class "FJSPPSORealIndividualService" as C_FJSPPSORealIndividualService
class "Activator" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_Activator
class "CCPSOGroup" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_CCPSOGroup
class "CCParticle" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_CCParticle
class "CCParticleStatus" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_CCParticleStatus
class "FJSPPSORealIndividualService" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_FJSPPSORealIndividualService
class "PSOParticleDimension" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_PSOParticleDimension
class "PSOSectionLayout" as C_com_evolsoft_problem_fjsp2_psoinvidualservice_PSOSectionLayout

C_FJSPPSORealIndividualService --> C_com_evolsoft_problem_fjsp2_psoinvidualservice_PSOSectionLayout
C_com_evolsoft_problem_fjsp2_psoinvidualservice_FJSPPSORealIndividualService --> C_com_evolsoft_problem_fjsp2_psoinvidualservice_CCPSOGroup
C_com_evolsoft_problem_fjsp2_psoinvidualservice_FJSPPSORealIndividualService --> C_com_evolsoft_problem_fjsp2_psoinvidualservice_PSOSectionLayout
@enduml
