@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.uiExtension

class "Activator" as C_com_evolsoft_ec_uiextension_Activator
class "AbstractExperimentDataAction" as C_com_evolsoft_ec_uiextension_experimentActions_AbstractExperimentDataAction
class "ExportBestSolutionAction" as C_com_evolsoft_ec_uiextension_experimentActions_ExportBestSolutionAction
class "SendMailAction" as C_com_evolsoft_ec_uiextension_experimentActions_SendMailAction
class "ApproachSortOption" as C_com_evolsoft_ec_uiextension_figureActions_ApproachSortOption
class "CopyOfDrawBoxPlot" as C_com_evolsoft_ec_uiextension_figureActions_CopyOfDrawBoxPlot
class "CovergencePlottingAction" as C_com_evolsoft_ec_uiextension_figureActions_CovergencePlottingAction
class "DrawBoxPlot" as C_com_evolsoft_ec_uiextension_figureActions_DrawBoxPlot
class "ExperimentActionDelegateBase" as C_com_evolsoft_ec_uiextension_figureActions_ExperimentActionDelegateBase
class "ExperimentDataProvider" as C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
class "ExperimentDialog" as C_com_evolsoft_ec_uiextension_figureActions_ExperimentDialog
class "ExportRunningTimeAction" as C_com_evolsoft_ec_uiextension_figureActions_ExportRunningTimeAction
class "FigureExporter" as C_com_evolsoft_ec_uiextension_figureActions_FigureExporter
class "MFileWriter" as C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
class "ObjectiveDataProvider" as C_com_evolsoft_ec_uiextension_figureActions_ObjectiveDataProvider
class "ObjectiveDataProvider (com.evolsoft.ec.uiExtension)" as C_com_evolsoft_ec_uiextension_figureActions_ObjectiveDataProvider__dup2
class "StatisticActionDelegate" as C_com_evolsoft_ec_uiextension_figureActions_StatisticActionDelegate
class "ViewerLabelProvider" as C_com_evolsoft_ec_uiextension_figureActions_ViewerLabelProvider
class "ViewerLabelProvider (com.evolsoft.ec.uiExtension)" as C_com_evolsoft_ec_uiextension_figureActions_ViewerLabelProvider__dup2

C_com_evolsoft_ec_uiextension_experimentActions_AbstractExperimentDataAction <|-- C_com_evolsoft_ec_uiextension_experimentActions_ExportBestSolutionAction
C_com_evolsoft_ec_uiextension_figureActions_ExperimentActionDelegateBase <|-- C_com_evolsoft_ec_uiextension_figureActions_CovergencePlottingAction
C_com_evolsoft_ec_uiextension_figureActions_ExperimentActionDelegateBase <|-- C_com_evolsoft_ec_uiextension_figureActions_DrawBoxPlot
C_com_evolsoft_ec_uiextension_figureActions_ExperimentActionDelegateBase <|-- C_com_evolsoft_ec_uiextension_figureActions_ExportRunningTimeAction
C_com_evolsoft_ec_uiextension_figureActions_ExperimentActionDelegateBase <|-- C_com_evolsoft_ec_uiextension_figureActions_StatisticActionDelegate
C_com_evolsoft_ec_uiextension_figureActions_CopyOfDrawBoxPlot --> C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
C_com_evolsoft_ec_uiextension_figureActions_CovergencePlottingAction --> C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
C_com_evolsoft_ec_uiextension_figureActions_DrawBoxPlot --> C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
C_com_evolsoft_ec_uiextension_figureActions_ExperimentDialog --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
C_com_evolsoft_ec_uiextension_figureActions_ExportRunningTimeAction --> C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
C_com_evolsoft_ec_uiextension_figureActions_FigureExporter --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
C_com_evolsoft_ec_uiextension_figureActions_ObjectiveDataProvider --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
C_com_evolsoft_ec_uiextension_figureActions_ObjectiveDataProvider__dup2 --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
C_com_evolsoft_ec_uiextension_figureActions_StatisticActionDelegate --> C_com_evolsoft_ec_uiextension_figureActions_MFileWriter
C_com_evolsoft_ec_uiextension_figureActions_ViewerLabelProvider --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
C_com_evolsoft_ec_uiextension_figureActions_ViewerLabelProvider__dup2 --> C_com_evolsoft_ec_uiextension_figureActions_ExperimentDataProvider
@enduml
