@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.msga.tool

class "AbstractMultipleOBJFitnessService" as C_com_evolsoft_ec_msga_AbstractMultipleOBJFitnessService
class "AWAArchiveFitnessActionService" as C_com_evolsoft_ec_msga_awa_AWAArchiveFitnessActionService
class "IAWAArchiveFitnessService" as C_com_evolsoft_ec_msga_awa_IAWAArchiveFitnessService
class "IAWGAFitnessService" as C_com_evolsoft_ec_msga_awa_IAWGAFitnessService
class "GPSIFFFitnessService" as C_com_evolsoft_ec_msga_gpsiff_GPSIFFFitnessService
class "IndividualStatus" as C_com_evolsoft_ec_msga_nsga_IndividualStatus
class "MultipleOBJFitnessService" as C_com_evolsoft_ec_msga_nsga_MultipleOBJFitnessService
class "NSGAFitnessValue" as C_com_evolsoft_ec_msga_nsga_NSGAFitnessValue
class "NSGAIIFitnessService" as C_com_evolsoft_ec_msga_nsga_NSGAIIFitnessService
class "NSGAIISorter" as C_com_evolsoft_ec_msga_nsga_NSGAIISorter
class "RankingSegment" as C_com_evolsoft_ec_msga_nsga_RankingSegment
interface "ISPEA2Sorter" as C_com_evolsoft_ec_msga_spea_ISPEA2Sorter
class "IndividualStatus" as C_com_evolsoft_ec_msga_spea_IndividualStatus
class "SPEA2FitnessService" as C_com_evolsoft_ec_msga_spea_SPEA2FitnessService
class "SPEA2Sorter" as C_com_evolsoft_ec_msga_spea_SPEA2Sorter
class "SPEAFitnessValue" as C_com_evolsoft_ec_msga_spea_SPEAFitnessValue
class "ECMultiObjectivePlugin" as C_com_evolsoft_ec_msga_tool_ECMultiObjectivePlugin

C_com_evolsoft_ec_msga_awa_IAWGAFitnessService <|-- C_com_evolsoft_ec_msga_awa_IAWAArchiveFitnessService
C_com_evolsoft_ec_msga_nsga_MultipleOBJFitnessService <|-- C_com_evolsoft_ec_msga_gpsiff_GPSIFFFitnessService
C_com_evolsoft_ec_msga_nsga_MultipleOBJFitnessService <|-- C_com_evolsoft_ec_msga_spea_SPEA2FitnessService
C_com_evolsoft_ec_msga_spea_ISPEA2Sorter <|.. C_com_evolsoft_ec_msga_spea_SPEA2Sorter
C_com_evolsoft_ec_msga_nsga_IndividualStatus --> C_com_evolsoft_ec_msga_nsga_NSGAIISorter
C_com_evolsoft_ec_msga_nsga_NSGAIIFitnessService --> C_com_evolsoft_ec_msga_nsga_NSGAIISorter
C_com_evolsoft_ec_msga_nsga_NSGAIISorter --> C_com_evolsoft_ec_msga_nsga_IndividualStatus
C_com_evolsoft_ec_msga_nsga_RankingSegment --> C_com_evolsoft_ec_msga_nsga_IndividualStatus
C_com_evolsoft_ec_msga_nsga_RankingSegment --> C_com_evolsoft_ec_msga_nsga_NSGAIISorter
C_com_evolsoft_ec_msga_spea_SPEA2Sorter --> C_com_evolsoft_ec_msga_spea_IndividualStatus
@enduml
