@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.toolbox.notation

class "AbstractZestEntityContentProvider" as C_com_evolsoft_ec_toolbox_notation_AbstractZestEntityContentProvider
class "AbstractZestFigureProvider" as C_com_evolsoft_ec_toolbox_notation_AbstractZestFigureProvider
class "AbstractZestStyleFigureProvider" as C_com_evolsoft_ec_toolbox_notation_AbstractZestStyleFigureProvider
class "NotationPlugin" as C_com_evolsoft_ec_toolbox_notation_NotationPlugin
class "CompartmentFigure" as C_com_evolsoft_ec_toolbox_notation_figure_CompartmentFigure
class "CompartmentFigureBorder" as C_com_evolsoft_ec_toolbox_notation_figure_CompartmentFigureBorder
class "DragTracker" as C_com_evolsoft_ec_toolbox_notation_figure_DragTracker
class "Frame" as C_com_evolsoft_ec_toolbox_notation_figure_Frame
class "InternalFrameBorder" as C_com_evolsoft_ec_toolbox_notation_figure_InternalFrameBorder
class "ScrollFramePanel" as C_com_evolsoft_ec_toolbox_notation_figure_ScrollFramePanel
class "AnimatingLayer" as C_com_evolsoft_ec_toolbox_notation_figure_tree_AnimatingLayer
class "Animation" as C_com_evolsoft_ec_toolbox_notation_figure_tree_Animation
class "BranchLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout
class "FoldedPageBorder" as C_com_evolsoft_ec_toolbox_notation_figure_tree_FoldedPageBorder
class "HangingLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout
class "NormalLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout
class "PageNode" as C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
class "PlusMinus" as C_com_evolsoft_ec_toolbox_notation_figure_tree_PlusMinus
class "TreeBranch" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
class "TreeFigure" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure
class "TreeLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeLayout
class "TreeRoot" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot
class "TestUtils" as C_tester_TestUtils

C_com_evolsoft_ec_toolbox_notation_figure_Frame <|-- C_com_evolsoft_ec_toolbox_notation_figure_ScrollFramePanel
C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout
C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot
C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure --> C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot --> C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
@enduml
