@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.individualservice

interface "IIndivdualServiceReferenceDescriptor" as C_com_evolsoft_ec_configuration_individualservice_IIndivdualServiceReferenceDescriptor
interface "IIndividualServiceDescriptorSpec" as C_com_evolsoft_ec_configuration_individualservice_IIndividualServiceDescriptorSpec
interface "IIndividualServiceProviderDescriptor" as C_com_evolsoft_ec_configuration_individualservice_IIndividualServiceProviderDescriptor
class "IndivdualServiceReferenceDescriptor" as C_com_evolsoft_ec_configuration_individualservice_IndivdualServiceReferenceDescriptor
class "IndividualServiceAdvisor" as C_com_evolsoft_ec_configuration_individualservice_IndividualServiceAdvisor
class "IndividualServiceManager" as C_com_evolsoft_ec_configuration_individualservice_IndividualServiceManager
class "IndividualServiceProviderDescriptor" as C_com_evolsoft_ec_configuration_individualservice_IndividualServiceProviderDescriptor

C_com_evolsoft_ec_configuration_individualservice_IIndivdualServiceReferenceDescriptor <|.. C_com_evolsoft_ec_configuration_individualservice_IndivdualServiceReferenceDescriptor
C_com_evolsoft_ec_configuration_individualservice_IIndividualServiceProviderDescriptor <|.. C_com_evolsoft_ec_configuration_individualservice_IndividualServiceProviderDescriptor
C_com_evolsoft_ec_configuration_individualservice_IndividualServiceAdvisor --> C_com_evolsoft_ec_configuration_individualservice_IIndividualServiceProviderDescriptor
@enduml
