@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.wizards

class "ContentProvider" as C_com_evolsoft_ec_ui_wizards_ContentProvider
class "ECConatinerPage" as C_com_evolsoft_ec_ui_wizards_ECConatinerPage
class "ECExperimentPage" as C_com_evolsoft_ec_ui_wizards_ECExperimentPage
class "ECProjectSetting" as C_com_evolsoft_ec_ui_wizards_ECProjectSetting
class "ECSettingWizardPage" as C_com_evolsoft_ec_ui_wizards_ECSettingWizardPage
class "ECTemplateWizardPage" as C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
interface "IECNewWizard" as C_com_evolsoft_ec_ui_wizards_IECNewWizard
class "NewApproachWizard" as C_com_evolsoft_ec_ui_wizards_NewApproachWizard
class "NewECProjectWizard" as C_com_evolsoft_ec_ui_wizards_NewECProjectWizard
class "ObjectiveCustomPage" as C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
class "TableLabelProvider" as C_com_evolsoft_ec_ui_wizards_TableLabelProvider

C_com_evolsoft_ec_ui_wizards_IECNewWizard <|.. C_com_evolsoft_ec_ui_wizards_NewApproachWizard
C_com_evolsoft_ec_ui_wizards_ContentProvider --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECConatinerPage --> C_com_evolsoft_ec_ui_wizards_IECNewWizard
C_com_evolsoft_ec_ui_wizards_ECExperimentPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECSettingWizardPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECConatinerPage
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
C_com_evolsoft_ec_ui_wizards_NewApproachWizard --> C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ECTemplateWizardPage
C_com_evolsoft_ec_ui_wizards_NewECProjectWizard --> C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage
C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage --> C_com_evolsoft_ec_ui_wizards_ContentProvider
C_com_evolsoft_ec_ui_wizards_ObjectiveCustomPage --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
C_com_evolsoft_ec_ui_wizards_TableLabelProvider --> C_com_evolsoft_ec_ui_wizards_ContentProvider
C_com_evolsoft_ec_ui_wizards_TableLabelProvider --> C_com_evolsoft_ec_ui_wizards_ECProjectSetting
@enduml
