@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.sa.configuration

interface "ISACFGFactory" as C_com_evolsoft_ec_sa_configuration_ISACFGFactory
interface "ISACFGPackage" as C_com_evolsoft_ec_sa_configuration_ISACFGPackage
interface "ISAConfiguration" as C_com_evolsoft_ec_sa_configuration_ISAConfiguration
interface "ISAConfigurationLoader" as C_com_evolsoft_ec_sa_configuration_ISAConfigurationLoader
interface "Literals" as C_com_evolsoft_ec_sa_configuration_Literals

@enduml
