@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.ganttChart.impl

class "GTDetailRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl
class "GTGroupImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl
class "GTItemImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl
class "GTItemProxy" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemProxy
class "GTMarkerImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarkerImpl
class "GTMarktableRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl
class "GTRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl
class "GTRulerImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl
class "GTSubGroupImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl
class "GanttChartFactoryImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartFactoryImpl
class "GanttChartModelImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl
class "GanttChartPackageImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartPackageImpl
class "GanttChartableImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl

C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl
@enduml
