@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.fitnessService

class "AWAFitnessActionService" as C_com_evolsoft_ec_runtime_fitnessService_AWAFitnessActionService
class "ECFitnessActionBase" as C_com_evolsoft_ec_runtime_fitnessService_ECFitnessActionBase
class "FitnessActionDescriptor" as C_com_evolsoft_ec_runtime_fitnessService_FitnessActionDescriptor
class "FitnessFunction" as C_com_evolsoft_ec_runtime_fitnessService_FitnessFunction
class "FitnessService" as C_com_evolsoft_ec_runtime_fitnessService_FitnessService
class "FitnessServiceEventArgs" as C_com_evolsoft_ec_runtime_fitnessService_FitnessServiceEventArgs
class "FitnessValue" as C_com_evolsoft_ec_runtime_fitnessService_FitnessValue
class "FitnessValueBase" as C_com_evolsoft_ec_runtime_fitnessService_FitnessValueBase
interface "IFitnessFunction" as C_com_evolsoft_ec_runtime_fitnessService_IFitnessFunction
interface "IFitnessMonitor" as C_com_evolsoft_ec_runtime_fitnessService_IFitnessMonitor
interface "IFitnessService" as C_com_evolsoft_ec_runtime_fitnessService_IFitnessService
interface "IFitnessValue" as C_com_evolsoft_ec_runtime_fitnessService_IFitnessValue
class "IndividualFitnessComparator" as C_com_evolsoft_ec_runtime_fitnessService_IndividualFitnessComparator

C_com_evolsoft_ec_runtime_fitnessService_ECFitnessActionBase <|-- C_com_evolsoft_ec_runtime_fitnessService_AWAFitnessActionService
C_com_evolsoft_ec_runtime_fitnessService_FitnessValueBase <|-- C_com_evolsoft_ec_runtime_fitnessService_FitnessValue
C_com_evolsoft_ec_runtime_fitnessService_IFitnessService <|.. C_com_evolsoft_ec_runtime_fitnessService_ECFitnessActionBase
C_com_evolsoft_ec_runtime_fitnessService_IFitnessFunction <|.. C_com_evolsoft_ec_runtime_fitnessService_FitnessFunction
C_com_evolsoft_ec_runtime_fitnessService_IFitnessValue <|.. C_com_evolsoft_ec_runtime_fitnessService_FitnessValue
C_com_evolsoft_ec_runtime_fitnessService_IFitnessValue <|.. C_com_evolsoft_ec_runtime_fitnessService_FitnessValueBase
C_com_evolsoft_ec_runtime_fitnessService_ECFitnessActionBase --> C_com_evolsoft_ec_runtime_fitnessService_FitnessFunction
C_com_evolsoft_ec_runtime_fitnessService_ECFitnessActionBase --> C_com_evolsoft_ec_runtime_fitnessService_IFitnessValue
C_com_evolsoft_ec_runtime_fitnessService_FitnessFunction --> C_com_evolsoft_ec_runtime_fitnessService_IndividualFitnessComparator
@enduml
