@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor.impl

class "ECRTMonitorFactory" as C_com_evolsoft_ec_runtime_monitor_impl_ECRTMonitorFactory
class "ECRTMonitorPackage" as C_com_evolsoft_ec_runtime_monitor_impl_ECRTMonitorPackage
class "FitnessMonitorItem" as C_com_evolsoft_ec_runtime_monitor_impl_FitnessMonitorItem
class "MonitorActionManager" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorActionManager
class "MonitorContext" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorContext
class "MonitorHub" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorHub
class "MonitorItem" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorItem
class "MonitorItemManager" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorItemManager
class "MonitorListener" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorListener
class "MonitorServiceItemFactory" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorServiceItemFactory
class "MonitorTrigger" as C_com_evolsoft_ec_runtime_monitor_impl_MonitorTrigger
class "MontiorChangedEventArgs" as C_com_evolsoft_ec_runtime_monitor_impl_MontiorChangedEventArgs
class "ObjectiveMonitorItem" as C_com_evolsoft_ec_runtime_monitor_impl_ObjectiveMonitorItem
class "ParetoItem" as C_com_evolsoft_ec_runtime_monitor_impl_ParetoItem
class "ParetoMonitorItem" as C_com_evolsoft_ec_runtime_monitor_impl_ParetoMonitorItem
class "PeriodMonitorPointProvider" as C_com_evolsoft_ec_runtime_monitor_impl_PeriodMonitorPointProvider
class "StatisticMonitorItem" as C_com_evolsoft_ec_runtime_monitor_impl_StatisticMonitorItem

C_com_evolsoft_ec_runtime_monitor_impl_StatisticMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_impl_FitnessMonitorItem
C_com_evolsoft_ec_runtime_monitor_impl_StatisticMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_impl_ObjectiveMonitorItem
C_com_evolsoft_ec_runtime_monitor_impl_MonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_impl_ParetoMonitorItem
C_com_evolsoft_ec_runtime_monitor_impl_MonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_impl_StatisticMonitorItem
C_com_evolsoft_ec_runtime_monitor_impl_MonitorContext --> C_com_evolsoft_ec_runtime_monitor_impl_ObjectiveMonitorItem
C_com_evolsoft_ec_runtime_monitor_impl_MonitorContext --> C_com_evolsoft_ec_runtime_monitor_impl_ParetoMonitorItem
@enduml
