@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.configEditor

class "ECConfigurationEditor" as C_com_evolsoft_ec_ui_configEditor_ECConfigurationEditor
class "ECExperimentSettingPage" as C_com_evolsoft_ec_ui_configEditor_ECExperimentSettingPage
class "ECFormpageBase" as C_com_evolsoft_ec_ui_configEditor_ECFormpageBase
class "ECOperatorPage" as C_com_evolsoft_ec_ui_configEditor_ECOperatorPage
class "OpenSolutionEditorAction" as C_com_evolsoft_ec_ui_configEditor_OpenSolutionEditorAction
class "OverviewPage" as C_com_evolsoft_ec_ui_configEditor_OverviewPage
class "ProfilePage" as C_com_evolsoft_ec_ui_configEditor_ProfilePage
class "RunAction" as C_com_evolsoft_ec_ui_configEditor_RunAction
class "SimpleDocumentProvider" as C_com_evolsoft_ec_ui_configEditor_SimpleDocumentProvider
class "SolutionDescriptorInput" as C_com_evolsoft_ec_ui_configEditor_SolutionDescriptorInput
interface "that" as C_com_evolsoft_ec_ui_configEditor_that

C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_ECExperimentSettingPage
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_OverviewPage
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase <|-- C_com_evolsoft_ec_ui_configEditor_ProfilePage
C_com_evolsoft_ec_ui_configEditor_ECConfigurationEditor --> C_com_evolsoft_ec_ui_configEditor_RunAction
C_com_evolsoft_ec_ui_configEditor_ECFormpageBase --> C_com_evolsoft_ec_ui_configEditor_SolutionDescriptorInput
C_com_evolsoft_ec_ui_configEditor_that --> C_com_evolsoft_ec_ui_configEditor_RunAction
@enduml
