@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.problem.rcpsp.model.decision

class "FJSPSolutionChartProvider" as C_com_evolsoft_ec_problem_rcpsp_model_decision_FJSPSolutionChartProvider
interface "IRCPSPSolutionCollection" as C_com_evolsoft_ec_problem_rcpsp_model_decision_IRCPSPSolutionCollection
class "ProjectResourceSeizer" as C_com_evolsoft_ec_problem_rcpsp_model_decision_ProjectResourceSeizer
class "ProjectSeizer" as C_com_evolsoft_ec_problem_rcpsp_model_decision_ProjectSeizer
class "RCPActivityDecision" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPActivityDecision
class "RCPEPPScheduleItem" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPEPPScheduleItem
class "RCPSPAssignment" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPSPAssignment
class "RCPSPScheduling" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPSPScheduling
class "RCPSPSolutionCollection" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPSPSolutionCollection
class "RCPSProjectDecision" as C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPSProjectDecision

C_com_evolsoft_ec_problem_rcpsp_model_decision_IRCPSPSolutionCollection <|.. C_com_evolsoft_ec_problem_rcpsp_model_decision_RCPSPSolutionCollection
@enduml
