@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.solution

class "ECApplicationDescriptorBase" as C_com_evolsoft_ec_configuration_solution_ECApplicationDescriptorBase
class "ECClusterDescriptor" as C_com_evolsoft_ec_configuration_solution_ECClusterDescriptor
class "ECClusterDescriptorConventer" as C_com_evolsoft_ec_configuration_solution_ECClusterDescriptorConventer
class "ECClusterSolutionService" as C_com_evolsoft_ec_configuration_solution_ECClusterSolutionService
class "ECConfigurationElementHandler" as C_com_evolsoft_ec_configuration_solution_ECConfigurationElementHandler
class "ECDescriptorConventerBase" as C_com_evolsoft_ec_configuration_solution_ECDescriptorConventerBase
class "ECSolutionDescriptorBase" as C_com_evolsoft_ec_configuration_solution_ECSolutionDescriptorBase
class "ECSolutionService" as C_com_evolsoft_ec_configuration_solution_ECSolutionService
class "ECSpeciesDescriptor" as C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptor
class "ECSpeciesDescriptorConventer" as C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptorConventer
interface "IBatchable" as C_com_evolsoft_ec_configuration_solution_IBatchable
interface "ICategorySupportable" as C_com_evolsoft_ec_configuration_solution_ICategorySupportable
interface "ICheckable" as C_com_evolsoft_ec_configuration_solution_ICheckable
interface "IECApplicationDescriptorDesc" as C_com_evolsoft_ec_configuration_solution_IECApplicationDescriptorDesc
interface "IECClusterDescriptor" as C_com_evolsoft_ec_configuration_solution_IECClusterDescriptor
interface "IECClusterDescriptorDesc" as C_com_evolsoft_ec_configuration_solution_IECClusterDescriptorDesc
interface "IECSolutionDescritable" as C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable
interface "IECSpeciesSolutionDescriptor" as C_com_evolsoft_ec_configuration_solution_IECSpeciesSolutionDescriptor
interface "IECSpeciesSolutionDescriptorSpec" as C_com_evolsoft_ec_configuration_solution_IECSpeciesSolutionDescriptorSpec
class "SolutionCategory" as C_com_evolsoft_ec_configuration_solution_SolutionCategory
class "SolutionCategoryManager" as C_com_evolsoft_ec_configuration_solution_SolutionCategoryManager
class "SolutionDescriptorReader" as C_com_evolsoft_ec_configuration_solution_SolutionDescriptorReader

C_com_evolsoft_ec_configuration_solution_ECApplicationDescriptorBase <|-- C_com_evolsoft_ec_configuration_solution_ECClusterDescriptor
C_com_evolsoft_ec_configuration_solution_ECDescriptorConventerBase <|-- C_com_evolsoft_ec_configuration_solution_ECClusterDescriptorConventer
C_com_evolsoft_ec_configuration_solution_ECApplicationDescriptorBase <|-- C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptor
C_com_evolsoft_ec_configuration_solution_ECDescriptorConventerBase <|-- C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptorConventer
C_com_evolsoft_ec_configuration_solution_IBatchable <|-- C_com_evolsoft_ec_configuration_solution_IECClusterDescriptor
C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable <|-- C_com_evolsoft_ec_configuration_solution_IECClusterDescriptor
C_com_evolsoft_ec_configuration_solution_IECApplicationDescriptorDesc <|-- C_com_evolsoft_ec_configuration_solution_IECClusterDescriptorDesc
C_com_evolsoft_ec_configuration_solution_IBatchable <|-- C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable
C_com_evolsoft_ec_configuration_solution_ICategorySupportable <|-- C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable
C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable <|-- C_com_evolsoft_ec_configuration_solution_IECSpeciesSolutionDescriptor
C_com_evolsoft_ec_configuration_solution_IECApplicationDescriptorDesc <|-- C_com_evolsoft_ec_configuration_solution_IECSpeciesSolutionDescriptorSpec
C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable <|.. C_com_evolsoft_ec_configuration_solution_ECApplicationDescriptorBase
C_com_evolsoft_ec_configuration_solution_IECClusterDescriptor <|.. C_com_evolsoft_ec_configuration_solution_ECClusterDescriptor
C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable <|.. C_com_evolsoft_ec_configuration_solution_ECSolutionDescriptorBase
C_com_evolsoft_ec_configuration_solution_IECSpeciesSolutionDescriptor <|.. C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptor
C_com_evolsoft_ec_configuration_solution_ECApplicationDescriptorBase --> C_com_evolsoft_ec_configuration_solution_SolutionCategory
C_com_evolsoft_ec_configuration_solution_ECClusterDescriptor --> C_com_evolsoft_ec_configuration_solution_ECSpeciesDescriptor
C_com_evolsoft_ec_configuration_solution_SolutionDescriptorReader --> C_com_evolsoft_ec_configuration_solution_IECSolutionDescritable
@enduml
