@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime

class "ActivationResult" as C_com_evolsoft_core_runtime_ActivationResult
interface "ComparisonFlag" as C_com_evolsoft_core_runtime_ComparisonFlag
class "ComponentDisposedException" as C_com_evolsoft_core_runtime_ComponentDisposedException
enum "ComponentStatus" as C_com_evolsoft_core_runtime_ComponentStatus
interface "ECConst" as C_com_evolsoft_core_runtime_ECConst
class "ECCore" as C_com_evolsoft_core_runtime_ECCore
class "ECCoreRuntimeException" as C_com_evolsoft_core_runtime_ECCoreRuntimeException
class "ECFramework" as C_com_evolsoft_core_runtime_ECFramework
interface "ECSettableItem" as C_com_evolsoft_core_runtime_ECSettableItem
class "ECSetting" as C_com_evolsoft_core_runtime_ECSetting
class "ECTraceableItem" as C_com_evolsoft_core_runtime_ECTraceableItem
class "EventListeners" as C_com_evolsoft_core_runtime_EventListeners
interface "IAbstractActiveObjectBase" as C_com_evolsoft_core_runtime_IAbstractActiveObjectBase
interface "IActiveObject" as C_com_evolsoft_core_runtime_IActiveObject
interface "ICloneable" as C_com_evolsoft_core_runtime_ICloneable
interface "IComponentbase" as C_com_evolsoft_core_runtime_IComponentbase
interface "IConfigurable" as C_com_evolsoft_core_runtime_IConfigurable
interface "ICoreRuntimeFactory" as C_com_evolsoft_core_runtime_ICoreRuntimeFactory
interface "ICoreRuntimePackage" as C_com_evolsoft_core_runtime_ICoreRuntimePackage
interface "IECTraceableItem" as C_com_evolsoft_core_runtime_IECTraceableItem
interface "IIdentifiableObject" as C_com_evolsoft_core_runtime_IIdentifiableObject
interface "IQuantitativeValue" as C_com_evolsoft_core_runtime_IQuantitativeValue
interface "ISolutionContext" as C_com_evolsoft_core_runtime_ISolutionContext
interface "IVersion" as C_com_evolsoft_core_runtime_IVersion
interface "Literals" as C_com_evolsoft_core_runtime_Literals
class "NoActiveException" as C_com_evolsoft_core_runtime_NoActiveException
class "NotImplementedException" as C_com_evolsoft_core_runtime_NotImplementedException
class "ParameterErrorException" as C_com_evolsoft_core_runtime_ParameterErrorException
class "preferencesECPerferencePage" as C_com_evolsoft_core_runtime_preferencesECPerferencePage

C_com_evolsoft_core_runtime_IActiveObject <|-- C_com_evolsoft_core_runtime_IAbstractActiveObjectBase
C_com_evolsoft_core_runtime_IIdentifiableObject <|-- C_com_evolsoft_core_runtime_IAbstractActiveObjectBase
C_com_evolsoft_core_runtime_IIdentifiableObject <|-- C_com_evolsoft_core_runtime_IActiveObject
C_com_evolsoft_core_runtime_IAbstractActiveObjectBase <|-- C_com_evolsoft_core_runtime_IComponentbase
C_com_evolsoft_core_runtime_IActiveObject <|-- C_com_evolsoft_core_runtime_ISolutionContext
C_com_evolsoft_core_runtime_IECTraceableItem <|.. C_com_evolsoft_core_runtime_ECTraceableItem
@enduml
