@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.msga

class "AbstractMultipleOBJFitnessService" as C_com_evolsoft_ec_msga_AbstractMultipleOBJFitnessService

@enduml
