@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.strategy

interface "IDefaultStrategyLoader" as C_com_evolsoft_ec_configuration_strategy_IDefaultStrategyLoader
interface "IECCFGStrategyFactory" as C_com_evolsoft_ec_configuration_strategy_IECCFGStrategyFactory
interface "IECCFGStrategyPackage" as C_com_evolsoft_ec_configuration_strategy_IECCFGStrategyPackage
interface "IECStrategyConfiguration" as C_com_evolsoft_ec_configuration_strategy_IECStrategyConfiguration
interface "IECStrategyConfigurationLoader" as C_com_evolsoft_ec_configuration_strategy_IECStrategyConfigurationLoader
interface "IECStrategyDescriptor" as C_com_evolsoft_ec_configuration_strategy_IECStrategyDescriptor
interface "IECStrategyRefDescriptor" as C_com_evolsoft_ec_configuration_strategy_IECStrategyRefDescriptor
interface "Literals" as C_com_evolsoft_ec_configuration_strategy_Literals

C_com_evolsoft_ec_configuration_strategy_IECStrategyConfigurationLoader <|-- C_com_evolsoft_ec_configuration_strategy_IDefaultStrategyLoader
@enduml
