@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime

class "ContextHelper" as C_com_evolsoft_ec_runtime_ContextHelper
class "ContextObjectBase" as C_com_evolsoft_ec_runtime_ContextObjectBase
class "DeltaPrinter" as C_com_evolsoft_ec_runtime_DeltaPrinter
class "ECAbstractNatureAction" as C_com_evolsoft_ec_runtime_ECAbstractNatureAction
class "ECApplicationBase" as C_com_evolsoft_ec_runtime_ECApplicationBase
class "ECApplicationConsoleLoader" as C_com_evolsoft_ec_runtime_ECApplicationConsoleLoader
class "ECApplicationContextBase" as C_com_evolsoft_ec_runtime_ECApplicationContextBase
class "ECApplicationEvent" as C_com_evolsoft_ec_runtime_ECApplicationEvent
class "ECApplicationHook" as C_com_evolsoft_ec_runtime_ECApplicationHook
class "ECApplicationManager" as C_com_evolsoft_ec_runtime_ECApplicationManager
class "ECApplicationStub" as C_com_evolsoft_ec_runtime_ECApplicationStub
class "ECBestStatChangedEvent" as C_com_evolsoft_ec_runtime_ECBestStatChangedEvent
class "ECClusterContext" as C_com_evolsoft_ec_runtime_ECClusterContext
class "ECConstant" as C_com_evolsoft_ec_runtime_ECConstant
class "ECContextBindObject" as C_com_evolsoft_ec_runtime_ECContextBindObject
class "ECDescriptorBenchmarks" as C_com_evolsoft_ec_runtime_ECDescriptorBenchmarks
class "ECEnvironment" as C_com_evolsoft_ec_runtime_ECEnvironment
class "ECIndividualChangedEvent" as C_com_evolsoft_ec_runtime_ECIndividualChangedEvent
class "ECLaunchException" as C_com_evolsoft_ec_runtime_ECLaunchException
class "ECPlatform" as C_com_evolsoft_ec_runtime_ECPlatform
class "ECResourceChangeListener" as C_com_evolsoft_ec_runtime_ECResourceChangeListener
class "ECRunnableException" as C_com_evolsoft_ec_runtime_ECRunnableException
class "ECRuntime" as C_com_evolsoft_ec_runtime_ECRuntime
class "ECSpecies" as C_com_evolsoft_ec_runtime_ECSpecies
class "ECSpeciesBase" as C_com_evolsoft_ec_runtime_ECSpeciesBase
class "ECSpeciesWinBuilder" as C_com_evolsoft_ec_runtime_ECSpeciesWinBuilder
class "ECSpeiciesContext" as C_com_evolsoft_ec_runtime_ECSpeiciesContext
class "ECStubStatusChangedEvent" as C_com_evolsoft_ec_runtime_ECStubStatusChangedEvent
class "ECVariableAdvisor" as C_com_evolsoft_ec_runtime_ECVariableAdvisor
class "EngineEventService" as C_com_evolsoft_ec_runtime_EngineEventService
class "ErrorMessges" as C_com_evolsoft_ec_runtime_ErrorMessges
class "EventArgs" as C_com_evolsoft_ec_runtime_EventArgs
class "EvolvingHookManager" as C_com_evolsoft_ec_runtime_EvolvingHookManager
interface "IApplicationManager" as C_com_evolsoft_ec_runtime_IApplicationManager
enum "IClusterStatus" as C_com_evolsoft_ec_runtime_IClusterStatus
interface "IECAppComponent" as C_com_evolsoft_ec_runtime_IECAppComponent
interface "IECAppContextBindable" as C_com_evolsoft_ec_runtime_IECAppContextBindable
interface "IECApplication" as C_com_evolsoft_ec_runtime_IECApplication
interface "IECApplicationBuilder" as C_com_evolsoft_ec_runtime_IECApplicationBuilder
interface "IECApplicationContext" as C_com_evolsoft_ec_runtime_IECApplicationContext
interface "IECApplicationEventListener" as C_com_evolsoft_ec_runtime_IECApplicationEventListener
interface "IECApplicationHookDelegate" as C_com_evolsoft_ec_runtime_IECApplicationHookDelegate
interface "IECApplicationStub" as C_com_evolsoft_ec_runtime_IECApplicationStub
interface "IECClusterBuilder" as C_com_evolsoft_ec_runtime_IECClusterBuilder
interface "IECClusterContext" as C_com_evolsoft_ec_runtime_IECClusterContext
interface "IECComponent" as C_com_evolsoft_ec_runtime_IECComponent
interface "IECContextBase" as C_com_evolsoft_ec_runtime_IECContextBase
interface "IECContextBindable" as C_com_evolsoft_ec_runtime_IECContextBindable
interface "IECContextBindableExt" as C_com_evolsoft_ec_runtime_IECContextBindableExt
interface "IECContextTraceable" as C_com_evolsoft_ec_runtime_IECContextTraceable
interface "IECOperation" as C_com_evolsoft_ec_runtime_IECOperation
interface "IECRuntimeFactory" as C_com_evolsoft_ec_runtime_IECRuntimeFactory
interface "IECRuntimePackage" as C_com_evolsoft_ec_runtime_IECRuntimePackage
interface "IECSpecies" as C_com_evolsoft_ec_runtime_IECSpecies
interface "IECSpeciesContext" as C_com_evolsoft_ec_runtime_IECSpeciesContext
interface "IECSpeciesEvolvingHook" as C_com_evolsoft_ec_runtime_IECSpeciesEvolvingHook
interface "IECSpeciesHookDelegate" as C_com_evolsoft_ec_runtime_IECSpeciesHookDelegate
interface "IECSpeciesWinBuilder" as C_com_evolsoft_ec_runtime_IECSpeciesWinBuilder
interface "IECStubStatusChangedListener" as C_com_evolsoft_ec_runtime_IECStubStatusChangedListener
interface "IECSyncAppComponent" as C_com_evolsoft_ec_runtime_IECSyncAppComponent
interface "IECSyncIdentifiableObject" as C_com_evolsoft_ec_runtime_IECSyncIdentifiableObject
interface "IEECOperationBase" as C_com_evolsoft_ec_runtime_IEECOperationBase
interface "IESyncIdentifiableObject" as C_com_evolsoft_ec_runtime_IESyncIdentifiableObject
interface "IEngineEventMonitor" as C_com_evolsoft_ec_runtime_IEngineEventMonitor
interface "IEvolvingHookManager" as C_com_evolsoft_ec_runtime_IEvolvingHookManager
interface "IFitnessExportPoint" as C_com_evolsoft_ec_runtime_IFitnessExportPoint
interface "IRepairService" as C_com_evolsoft_ec_runtime_IRepairService
interface "ISelectionActionDelegate" as C_com_evolsoft_ec_runtime_ISelectionActionDelegate
class "IllegalTypeException" as C_com_evolsoft_ec_runtime_IllegalTypeException
interface "Literals" as C_com_evolsoft_ec_runtime_Literals
enum "MonitorStatus" as C_com_evolsoft_ec_runtime_MonitorStatus
class "NotInitializedException" as C_com_evolsoft_ec_runtime_NotInitializedException
class "ProblemAdvisor" as C_com_evolsoft_ec_runtime_ProblemAdvisor

C_com_evolsoft_ec_runtime_ECSpeciesWinBuilder <|-- C_com_evolsoft_ec_runtime_ECApplicationConsoleLoader
C_com_evolsoft_ec_runtime_ECApplicationEvent <|-- C_com_evolsoft_ec_runtime_ECBestStatChangedEvent
C_com_evolsoft_ec_runtime_ECApplicationContextBase <|-- C_com_evolsoft_ec_runtime_ECClusterContext
C_com_evolsoft_ec_runtime_ECApplicationEvent <|-- C_com_evolsoft_ec_runtime_ECIndividualChangedEvent
C_com_evolsoft_ec_runtime_ECSpeciesBase <|-- C_com_evolsoft_ec_runtime_ECSpecies
C_com_evolsoft_ec_runtime_ECApplicationBase <|-- C_com_evolsoft_ec_runtime_ECSpeciesBase
C_com_evolsoft_ec_runtime_ECApplicationContextBase <|-- C_com_evolsoft_ec_runtime_ECSpeiciesContext
C_com_evolsoft_ec_runtime_IECAppContextBindable <|-- C_com_evolsoft_ec_runtime_IECAppComponent
C_com_evolsoft_ec_runtime_IECContextTraceable <|-- C_com_evolsoft_ec_runtime_IECApplicationContext
C_com_evolsoft_ec_runtime_IECContextBindable <|-- C_com_evolsoft_ec_runtime_IECApplicationHookDelegate
C_com_evolsoft_ec_runtime_IECApplicationBuilder <|-- C_com_evolsoft_ec_runtime_IECClusterBuilder
C_com_evolsoft_ec_runtime_IECApplicationContext <|-- C_com_evolsoft_ec_runtime_IECClusterContext
C_com_evolsoft_ec_runtime_IECContextBindableExt <|-- C_com_evolsoft_ec_runtime_IECComponent
C_com_evolsoft_ec_runtime_IECContextBindable <|-- C_com_evolsoft_ec_runtime_IECContextBindableExt
C_com_evolsoft_ec_runtime_IECComponent <|-- C_com_evolsoft_ec_runtime_IECOperation
C_com_evolsoft_ec_runtime_IECApplication <|-- C_com_evolsoft_ec_runtime_IECSpecies
C_com_evolsoft_ec_runtime_IECApplicationContext <|-- C_com_evolsoft_ec_runtime_IECSpeciesContext
C_com_evolsoft_ec_runtime_IECApplicationHookDelegate <|-- C_com_evolsoft_ec_runtime_IECSpeciesHookDelegate
C_com_evolsoft_ec_runtime_IECApplicationBuilder <|-- C_com_evolsoft_ec_runtime_IECSpeciesWinBuilder
C_com_evolsoft_ec_runtime_IECAppComponent <|-- C_com_evolsoft_ec_runtime_IECSyncAppComponent
C_com_evolsoft_ec_runtime_IECContextBase <|-- C_com_evolsoft_ec_runtime_IECSyncIdentifiableObject
C_com_evolsoft_ec_runtime_IECComponent <|-- C_com_evolsoft_ec_runtime_IEECOperationBase
C_com_evolsoft_ec_runtime_IECContextBindable <|-- C_com_evolsoft_ec_runtime_ISelectionActionDelegate
C_com_evolsoft_ec_runtime_IECContextBindableExt <|.. C_com_evolsoft_ec_runtime_ContextObjectBase
C_com_evolsoft_ec_runtime_IECApplication <|.. C_com_evolsoft_ec_runtime_ECApplicationBase
C_com_evolsoft_ec_runtime_IECApplicationContext <|.. C_com_evolsoft_ec_runtime_ECApplicationContextBase
C_com_evolsoft_ec_runtime_IECApplicationHookDelegate <|.. C_com_evolsoft_ec_runtime_ECApplicationHook
C_com_evolsoft_ec_runtime_IApplicationManager <|.. C_com_evolsoft_ec_runtime_ECApplicationManager
C_com_evolsoft_ec_runtime_IECApplicationStub <|.. C_com_evolsoft_ec_runtime_ECApplicationStub
C_com_evolsoft_ec_runtime_IECClusterContext <|.. C_com_evolsoft_ec_runtime_ECClusterContext
C_com_evolsoft_ec_runtime_IECContextBindable <|.. C_com_evolsoft_ec_runtime_ECContextBindObject
C_com_evolsoft_ec_runtime_IECSpecies <|.. C_com_evolsoft_ec_runtime_ECSpeciesBase
C_com_evolsoft_ec_runtime_IECSpeciesWinBuilder <|.. C_com_evolsoft_ec_runtime_ECSpeciesWinBuilder
C_com_evolsoft_ec_runtime_IECSpeciesContext <|.. C_com_evolsoft_ec_runtime_ECSpeiciesContext
C_com_evolsoft_ec_runtime_IEngineEventMonitor <|.. C_com_evolsoft_ec_runtime_EngineEventService
C_com_evolsoft_ec_runtime_IEvolvingHookManager <|.. C_com_evolsoft_ec_runtime_EvolvingHookManager
C_com_evolsoft_ec_runtime_ContextHelper --> C_com_evolsoft_ec_runtime_IECSpeciesContext
C_com_evolsoft_ec_runtime_ContextObjectBase --> C_com_evolsoft_ec_runtime_IECSpeciesContext
C_com_evolsoft_ec_runtime_ECAbstractNatureAction --> C_com_evolsoft_ec_runtime_IECApplication
C_com_evolsoft_ec_runtime_ECApplicationBase --> C_com_evolsoft_ec_runtime_IECApplicationStub
C_com_evolsoft_ec_runtime_ECApplicationBase --> C_com_evolsoft_ec_runtime_MonitorStatus
C_com_evolsoft_ec_runtime_ECApplicationContextBase --> C_com_evolsoft_ec_runtime_IECApplication
C_com_evolsoft_ec_runtime_ECApplicationContextBase --> C_com_evolsoft_ec_runtime_IECApplicationHookDelegate
C_com_evolsoft_ec_runtime_ECApplicationEvent --> C_com_evolsoft_ec_runtime_IECApplication
C_com_evolsoft_ec_runtime_ECApplicationEvent --> C_com_evolsoft_ec_runtime_MonitorStatus
C_com_evolsoft_ec_runtime_ECApplicationHook --> C_com_evolsoft_ec_runtime_IECApplication
C_com_evolsoft_ec_runtime_ECApplicationManager --> C_com_evolsoft_ec_runtime_IECApplicationStub
C_com_evolsoft_ec_runtime_ECApplicationManager --> C_com_evolsoft_ec_runtime_IECStubStatusChangedListener
C_com_evolsoft_ec_runtime_ECApplicationStub --> C_com_evolsoft_ec_runtime_ECDescriptorBenchmarks
C_com_evolsoft_ec_runtime_ECApplicationStub --> C_com_evolsoft_ec_runtime_IECApplication
C_com_evolsoft_ec_runtime_ECApplicationStub --> C_com_evolsoft_ec_runtime_IEvolvingHookManager
C_com_evolsoft_ec_runtime_ECApplicationStub --> C_com_evolsoft_ec_runtime_MonitorStatus
C_com_evolsoft_ec_runtime_ECContextBindObject --> C_com_evolsoft_ec_runtime_IECSpeciesContext
C_com_evolsoft_ec_runtime_ECPlatform --> C_com_evolsoft_ec_runtime_ECApplicationManager
C_com_evolsoft_ec_runtime_ECPlatform --> C_com_evolsoft_ec_runtime_EngineEventService
C_com_evolsoft_ec_runtime_ECRuntime --> C_com_evolsoft_ec_runtime_ECEnvironment
C_com_evolsoft_ec_runtime_ECSpeciesBase --> C_com_evolsoft_ec_runtime_IECSpeciesContext
C_com_evolsoft_ec_runtime_ECSpeciesWinBuilder --> C_com_evolsoft_ec_runtime_ECVariableAdvisor
C_com_evolsoft_ec_runtime_ECSpeiciesContext --> C_com_evolsoft_ec_runtime_ContextHelper
C_com_evolsoft_ec_runtime_ECSpeiciesContext --> C_com_evolsoft_ec_runtime_IECSpecies
C_com_evolsoft_ec_runtime_ECSpeiciesContext --> C_com_evolsoft_ec_runtime_IEvolvingHookManager
C_com_evolsoft_ec_runtime_ECStubStatusChangedEvent --> C_com_evolsoft_ec_runtime_IECApplicationStub
@enduml
