@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.monitor.impl

class "ECCFGMonitorFactory" as C_com_evolsoft_ec_configuration_monitor_impl_ECCFGMonitorFactory
class "ECCFGMonitorPackage" as C_com_evolsoft_ec_configuration_monitor_impl_ECCFGMonitorPackage
class "MonitorItemDescriptor" as C_com_evolsoft_ec_configuration_monitor_impl_MonitorItemDescriptor
class "MonitorItemRefDescriptor" as C_com_evolsoft_ec_configuration_monitor_impl_MonitorItemRefDescriptor
class "MonitorItemRefDescriptorManager" as C_com_evolsoft_ec_configuration_monitor_impl_MonitorItemRefDescriptorManager
class "MonitorListenerDescriptor" as C_com_evolsoft_ec_configuration_monitor_impl_MonitorListenerDescriptor
class "MonitorTriggerDescriptor" as C_com_evolsoft_ec_configuration_monitor_impl_MonitorTriggerDescriptor
class "TriggerDetail" as C_com_evolsoft_ec_configuration_monitor_impl_TriggerDetail
class "TriggerDetailList" as C_com_evolsoft_ec_configuration_monitor_impl_TriggerDetailList
class "TriggerType" as C_com_evolsoft_ec_configuration_monitor_impl_TriggerType
class "TriggerTypeList" as C_com_evolsoft_ec_configuration_monitor_impl_TriggerTypeList

@enduml
