@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.ganttChart.viewer

class "ChartItem" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem
class "GanntchartLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanntchartLabelProvider
class "GantchartRender" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
class "GanttChartBuilder" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartBuilder
class "GanttChartPlugin" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin
class "GanttChartViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer
interface "IGanttChartSupportable" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartSupportable
interface "IGanttChartViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer
interface "IGanttChartViewerViewerMananger" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewerViewerMananger
interface "IGanttchartLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
interface "IScheduleBuilderViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer
class "ScheduleBuilderViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer

C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanntchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem
@enduml
