@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.chromosome

enum "ChromosomeType" as C_com_evolsoft_ec_configuration_chromosome_ChromosomeType
interface "IAllocator" as C_com_evolsoft_ec_configuration_chromosome_IAllocator
interface "IChromosomeDescriptor" as C_com_evolsoft_ec_configuration_chromosome_IChromosomeDescriptor
interface "IChromosomeSpec" as C_com_evolsoft_ec_configuration_chromosome_IChromosomeSpec
interface "ISectionChromosomeDescSpec" as C_com_evolsoft_ec_configuration_chromosome_ISectionChromosomeDescSpec
interface "ISectionChromosomeDescriptor" as C_com_evolsoft_ec_configuration_chromosome_ISectionChromosomeDescriptor
interface "ISectionDesc" as C_com_evolsoft_ec_configuration_chromosome_ISectionDesc
interface "ISectionDescSpec" as C_com_evolsoft_ec_configuration_chromosome_ISectionDescSpec
class "IllegalInitorException" as C_com_evolsoft_ec_configuration_chromosome_IllegalInitorException
class "SectionChromosomeDescriptor" as C_com_evolsoft_ec_configuration_chromosome_SectionChromosomeDescriptor

C_com_evolsoft_ec_configuration_chromosome_IChromosomeDescriptor <|-- C_com_evolsoft_ec_configuration_chromosome_ISectionChromosomeDescriptor
C_com_evolsoft_ec_configuration_chromosome_ISectionChromosomeDescriptor <|.. C_com_evolsoft_ec_configuration_chromosome_SectionChromosomeDescriptor
@enduml
