@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.ecoperation

class "ConfigableActionRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ConfigableActionRefDescriptor
class "CustomActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_CustomActionDescriptor
class "ECActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ECActionDescriptor
class "ECActionManager" as C_com_evolsoft_ec_configuration_ecoperation_ECActionManager
class "ECActionRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ECActionRefDescriptor
class "ECActionReferencesDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ECActionReferencesDescriptor
class "ECOperatorRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ECOperatorRefDescriptor
class "ECPActionRefDescriptorBase" as C_com_evolsoft_ec_configuration_ecoperation_ECPActionRefDescriptorBase
interface "IActionRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IActionRefDescriptor
interface "IConfigableECActionRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IConfigableECActionRefDescriptor
interface "ICrossOverActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ICrossOverActionDescriptor
interface "ICustomActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_ICustomActionDescriptor
interface "IECActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor
interface "IECActionDescriptorGroupSpec" as C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptorGroupSpec
interface "IECActionDescriptorSpec" as C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptorSpec
interface "IECActionExecutorDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IECActionExecutorDescriptor
interface "IECActionRefDescriptorManager" as C_com_evolsoft_ec_configuration_ecoperation_IECActionRefDescriptorManager
interface "IECActionRefDescriptorSpec" as C_com_evolsoft_ec_configuration_ecoperation_IECActionRefDescriptorSpec
interface "IECActionRefFactory" as C_com_evolsoft_ec_configuration_ecoperation_IECActionRefFactory
interface "IECOperatorRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IECOperatorRefDescriptor
interface "IECProbabilityPolicy" as C_com_evolsoft_ec_configuration_ecoperation_IECProbabilityPolicy
interface "IMutationActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IMutationActionDescriptor
interface "IParentSelectActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IParentSelectActionDescriptor
interface "IPopulationDescriptorSpec" as C_com_evolsoft_ec_configuration_ecoperation_IPopulationDescriptorSpec
interface "IProbabilityActionRefDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_IProbabilityActionRefDescriptor
class "MutationActionDescriptor" as C_com_evolsoft_ec_configuration_ecoperation_MutationActionDescriptor
class "ParentSelectActionDescritptor" as C_com_evolsoft_ec_configuration_ecoperation_ParentSelectActionDescritptor

C_com_evolsoft_ec_configuration_ecoperation_ECPActionRefDescriptorBase <|-- C_com_evolsoft_ec_configuration_ecoperation_ConfigableActionRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECActionDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_CustomActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECPActionRefDescriptorBase <|-- C_com_evolsoft_ec_configuration_ecoperation_ECOperatorRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IProbabilityActionRefDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_IConfigableECActionRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_ICrossOverActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_ICustomActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionRefDescriptorManager <|-- C_com_evolsoft_ec_configuration_ecoperation_IECActionExecutorDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IProbabilityActionRefDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_IECOperatorRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_IMutationActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IActionRefDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_IProbabilityActionRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECActionDescriptor <|-- C_com_evolsoft_ec_configuration_ecoperation_MutationActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IConfigableECActionRefDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ConfigableActionRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ICustomActionDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_CustomActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ECActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IActionRefDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ECActionRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECActionExecutorDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ECActionReferencesDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IECOperatorRefDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ECOperatorRefDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IProbabilityActionRefDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ECPActionRefDescriptorBase
C_com_evolsoft_ec_configuration_ecoperation_IMutationActionDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_MutationActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_IParentSelectActionDescriptor <|.. C_com_evolsoft_ec_configuration_ecoperation_ParentSelectActionDescritptor
C_com_evolsoft_ec_configuration_ecoperation_ECActionReferencesDescriptor --> C_com_evolsoft_ec_configuration_ecoperation_IECActionExecutorDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECActionReferencesDescriptor --> C_com_evolsoft_ec_configuration_ecoperation_IParentSelectActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECOperatorRefDescriptor --> C_com_evolsoft_ec_configuration_ecoperation_IECActionDescriptor
C_com_evolsoft_ec_configuration_ecoperation_ECOperatorRefDescriptor --> C_com_evolsoft_ec_configuration_ecoperation_IECActionRefDescriptorManager
C_com_evolsoft_ec_configuration_ecoperation_ECPActionRefDescriptorBase --> C_com_evolsoft_ec_configuration_ecoperation_IECActionRefDescriptorManager
@enduml
