@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.pso.configuration.util

class "PSOCFGAdapterFactory" as C_com_evolsoft_ec_pso_configuration_util_PSOCFGAdapterFactory
class "PSOCFGSwitch" as C_com_evolsoft_ec_pso_configuration_util_PSOCFGSwitch

@enduml
