@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.misc

class "ConfigurationElementList" as C_com_evolsoft_core_configuration_misc_ConfigurationElementList
interface "IXMLConfigurationELement" as C_com_evolsoft_core_configuration_misc_IXMLConfigurationELement
class "XMLConfigurationDocument" as C_com_evolsoft_core_configuration_misc_XMLConfigurationDocument
class "XMLConfigurationELement" as C_com_evolsoft_core_configuration_misc_XMLConfigurationELement
class "XMLConfigurationElementReader" as C_com_evolsoft_core_configuration_misc_XMLConfigurationElementReader

C_com_evolsoft_core_configuration_misc_IXMLConfigurationELement <|.. C_com_evolsoft_core_configuration_misc_XMLConfigurationELement
C_com_evolsoft_core_configuration_misc_XMLConfigurationDocument --> C_com_evolsoft_core_configuration_misc_IXMLConfigurationELement
C_com_evolsoft_core_configuration_misc_XMLConfigurationELement --> C_com_evolsoft_core_configuration_misc_IXMLConfigurationELement
C_com_evolsoft_core_configuration_misc_XMLConfigurationElementReader --> C_com_evolsoft_core_configuration_misc_IXMLConfigurationELement
@enduml
