@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.pbil.treeViewer

class "HistgramRender" as C_com_evolsoft_ec_pbil_treeViewer_HistgramRender
class "PBMatrixDataProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixDataProvider
class "PBMatrixLabelProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixLabelProvider
class "PBMatrixTestViewer" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer
class "PBMatrixTraceItem" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTraceItem
class "PBMatrixViewer" as C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer
class "PBVectorsDataProvider" as C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider
class "ProbabilityMatrixViewPart" as C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart
class "PropertyTipper" as C_com_evolsoft_ec_pbil_treeViewer_PropertyTipper

C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTestViewer --> C_com_evolsoft_ec_pbil_treeViewer_PBMatrixTraceItem
C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer --> C_com_evolsoft_ec_pbil_treeViewer_HistgramRender
C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart --> C_com_evolsoft_ec_pbil_treeViewer_PBMatrixViewer
C_com_evolsoft_ec_pbil_treeViewer_ProbabilityMatrixViewPart --> C_com_evolsoft_ec_pbil_treeViewer_PBVectorsDataProvider
@enduml
