@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.service

class "ConfigurableElementLoader" as C_com_evolsoft_core_runtime_service_ConfigurableElementLoader
class "ConfigurableElementManagerBase" as C_com_evolsoft_core_runtime_service_ConfigurableElementManagerBase
class "ConfigurationObjectCustomManager" as C_com_evolsoft_core_runtime_service_ConfigurationObjectCustomManager
class "ConfigurationObjectListManager" as C_com_evolsoft_core_runtime_service_ConfigurationObjectListManager
interface "IConfigurableElementManager" as C_com_evolsoft_core_runtime_service_IConfigurableElementManager
interface "IConfigurationMatch" as C_com_evolsoft_core_runtime_service_IConfigurationMatch
interface "IFilterMatch" as C_com_evolsoft_core_runtime_service_IFilterMatch
interface "IIndexCreateDelegate" as C_com_evolsoft_core_runtime_service_IIndexCreateDelegate
interface "INatureDescriptorFactory" as C_com_evolsoft_core_runtime_service_INatureDescriptorFactory
interface "IService" as C_com_evolsoft_core_runtime_service_IService
class "Index" as C_com_evolsoft_core_runtime_service_Index
class "ServiceBase" as C_com_evolsoft_core_runtime_service_ServiceBase
class "ServiceDescriptor" as C_com_evolsoft_core_runtime_service_ServiceDescriptor
interface "ServiceDescriptorSpec" as C_com_evolsoft_core_runtime_service_ServiceDescriptorSpec
class "ServiceFilter" as C_com_evolsoft_core_runtime_service_ServiceFilter
class "ServiceIdNotFoundException" as C_com_evolsoft_core_runtime_service_ServiceIdNotFoundException
class "ServiceInitializationException" as C_com_evolsoft_core_runtime_service_ServiceInitializationException
class "ServiceManager" as C_com_evolsoft_core_runtime_service_ServiceManager
enum "ServiceStatus" as C_com_evolsoft_core_runtime_service_ServiceStatus
class "StackItem" as C_com_evolsoft_core_runtime_service_StackItem

C_com_evolsoft_core_runtime_service_ConfigurableElementManagerBase <|-- C_com_evolsoft_core_runtime_service_ConfigurableElementLoader
C_com_evolsoft_core_runtime_service_ServiceBase <|-- C_com_evolsoft_core_runtime_service_ConfigurableElementManagerBase
C_com_evolsoft_core_runtime_service_IService <|-- C_com_evolsoft_core_runtime_service_IConfigurableElementManager
C_com_evolsoft_core_runtime_service_ConfigurableElementManagerBase <|-- C_com_evolsoft_core_runtime_service_ServiceFilter
C_com_evolsoft_core_runtime_service_ConfigurableElementManagerBase <|-- C_com_evolsoft_core_runtime_service_ServiceManager
C_com_evolsoft_core_runtime_service_IConfigurableElementManager <|.. C_com_evolsoft_core_runtime_service_ConfigurationObjectListManager
C_com_evolsoft_core_runtime_service_IService <|.. C_com_evolsoft_core_runtime_service_ServiceBase
C_com_evolsoft_core_runtime_service_IConfigurableElementManager <|.. C_com_evolsoft_core_runtime_service_ServiceManager
C_com_evolsoft_core_runtime_service_ServiceBase --> C_com_evolsoft_core_runtime_service_ServiceStatus
C_com_evolsoft_core_runtime_service_ServiceFilter --> C_com_evolsoft_core_runtime_service_ServiceDescriptor
@enduml
