@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor

class "AbstractMonitor" as C_com_evolsoft_ec_runtime_monitor_AbstractMonitor
class "AbstractMonitorItemViewPart" as C_com_evolsoft_ec_runtime_monitor_AbstractMonitorItemViewPart
class "ECMonitorUtils" as C_com_evolsoft_ec_runtime_monitor_ECMonitorUtils
class "ECRTMonitor" as C_com_evolsoft_ec_runtime_monitor_ECRTMonitor
interface "IECRTMonitorFactory" as C_com_evolsoft_ec_runtime_monitor_IECRTMonitorFactory
interface "IECRTMonitorPackage" as C_com_evolsoft_ec_runtime_monitor_IECRTMonitorPackage
interface "IFitnessValueListener" as C_com_evolsoft_ec_runtime_monitor_IFitnessValueListener
interface "IFitnessValueMonitorItem" as C_com_evolsoft_ec_runtime_monitor_IFitnessValueMonitorItem
interface "ILabelRequest" as C_com_evolsoft_ec_runtime_monitor_ILabelRequest
interface "ILabelRequestParser" as C_com_evolsoft_ec_runtime_monitor_ILabelRequestParser
interface "IMonitorActionManager" as C_com_evolsoft_ec_runtime_monitor_IMonitorActionManager
interface "IMonitorChangedListener" as C_com_evolsoft_ec_runtime_monitor_IMonitorChangedListener
interface "IMonitorContext" as C_com_evolsoft_ec_runtime_monitor_IMonitorContext
interface "IMonitorHub" as C_com_evolsoft_ec_runtime_monitor_IMonitorHub
interface "IMonitorItem" as C_com_evolsoft_ec_runtime_monitor_IMonitorItem
interface "IMonitorItemChangeListener" as C_com_evolsoft_ec_runtime_monitor_IMonitorItemChangeListener
interface "IMonitorItemManager" as C_com_evolsoft_ec_runtime_monitor_IMonitorItemManager
interface "IMonitorItemViewer" as C_com_evolsoft_ec_runtime_monitor_IMonitorItemViewer
interface "IMonitorListener" as C_com_evolsoft_ec_runtime_monitor_IMonitorListener
interface "IMonitorTrigger" as C_com_evolsoft_ec_runtime_monitor_IMonitorTrigger
interface "IMontiorChangedEventArgs" as C_com_evolsoft_ec_runtime_monitor_IMontiorChangedEventArgs
interface "IObjectiveMonitorItem" as C_com_evolsoft_ec_runtime_monitor_IObjectiveMonitorItem
interface "IParetoChangedListener" as C_com_evolsoft_ec_runtime_monitor_IParetoChangedListener
interface "IParetoMonitor" as C_com_evolsoft_ec_runtime_monitor_IParetoMonitor
interface "IParetoMonitorItem" as C_com_evolsoft_ec_runtime_monitor_IParetoMonitorItem
interface "IPeriodMonitorPointProvider" as C_com_evolsoft_ec_runtime_monitor_IPeriodMonitorPointProvider
interface "IStatisticMonitorItem" as C_com_evolsoft_ec_runtime_monitor_IStatisticMonitorItem
interface "ITimeSeriesDataListener" as C_com_evolsoft_ec_runtime_monitor_ITimeSeriesDataListener
interface "ITimeSeriesMonitor" as C_com_evolsoft_ec_runtime_monitor_ITimeSeriesMonitor
interface "ITimeTrace" as C_com_evolsoft_ec_runtime_monitor_ITimeTrace
class "LabelRequestEvent" as C_com_evolsoft_ec_runtime_monitor_LabelRequestEvent
interface "Literals" as C_com_evolsoft_ec_runtime_monitor_Literals
class "MonitorAdvisor" as C_com_evolsoft_ec_runtime_monitor_MonitorAdvisor
interface "MonitorChangedListener" as C_com_evolsoft_ec_runtime_monitor_MonitorChangedListener
class "MonitorContext1" as C_com_evolsoft_ec_runtime_monitor_MonitorContext1
class "MonitorItemChangedEvent" as C_com_evolsoft_ec_runtime_monitor_MonitorItemChangedEvent
class "MonitorObject" as C_com_evolsoft_ec_runtime_monitor_MonitorObject
class "MonitorTriggerArgs" as C_com_evolsoft_ec_runtime_monitor_MonitorTriggerArgs
enum "MonitorTriggerType" as C_com_evolsoft_ec_runtime_monitor_MonitorTriggerType
class "OpenObjectiveViewAction" as C_com_evolsoft_ec_runtime_monitor_OpenObjectiveViewAction
class "ParetoDataChangeEvent" as C_com_evolsoft_ec_runtime_monitor_ParetoDataChangeEvent
class "ParetoDataChangedListener" as C_com_evolsoft_ec_runtime_monitor_ParetoDataChangedListener
class "ParetoMonitorLabel" as C_com_evolsoft_ec_runtime_monitor_ParetoMonitorLabel
class "SeriesDataChangeEvent" as C_com_evolsoft_ec_runtime_monitor_SeriesDataChangeEvent
enum "SeriesEventType" as C_com_evolsoft_ec_runtime_monitor_SeriesEventType
class "TimeSeriesDataListener" as C_com_evolsoft_ec_runtime_monitor_TimeSeriesDataListener
class "TimeTraceManager" as C_com_evolsoft_ec_runtime_monitor_TimeTraceManager
class "TraceItem" as C_com_evolsoft_ec_runtime_monitor_TraceItem
class "XYDataSet" as C_com_evolsoft_ec_runtime_monitor_XYDataSet

C_com_evolsoft_ec_runtime_monitor_IStatisticMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_IFitnessValueMonitorItem
C_com_evolsoft_ec_runtime_monitor_IStatisticMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_IObjectiveMonitorItem
C_com_evolsoft_ec_runtime_monitor_IMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_IParetoMonitorItem
C_com_evolsoft_ec_runtime_monitor_IMonitorItem <|-- C_com_evolsoft_ec_runtime_monitor_IStatisticMonitorItem
C_com_evolsoft_ec_runtime_monitor_IMonitorItemChangeListener <|-- C_com_evolsoft_ec_runtime_monitor_ITimeSeriesDataListener
C_com_evolsoft_ec_runtime_monitor_IMonitorItemViewer <|-- C_com_evolsoft_ec_runtime_monitor_ITimeSeriesMonitor
C_com_evolsoft_ec_runtime_monitor_MonitorObject <|-- C_com_evolsoft_ec_runtime_monitor_OpenObjectiveViewAction
C_com_evolsoft_ec_runtime_monitor_MonitorObject <|-- C_com_evolsoft_ec_runtime_monitor_ParetoMonitorLabel
C_com_evolsoft_ec_runtime_monitor_MonitorItemChangedEvent <|-- C_com_evolsoft_ec_runtime_monitor_SeriesDataChangeEvent
C_com_evolsoft_ec_runtime_monitor_IMonitorItemChangeListener <|.. C_com_evolsoft_ec_runtime_monitor_AbstractMonitorItemViewPart
C_com_evolsoft_ec_runtime_monitor_IMonitorItemViewer <|.. C_com_evolsoft_ec_runtime_monitor_AbstractMonitorItemViewPart
C_com_evolsoft_ec_runtime_monitor_IParetoChangedListener <|.. C_com_evolsoft_ec_runtime_monitor_ParetoDataChangedListener
C_com_evolsoft_ec_runtime_monitor_ITimeSeriesDataListener <|.. C_com_evolsoft_ec_runtime_monitor_TimeSeriesDataListener
C_com_evolsoft_ec_runtime_monitor_ITimeTrace <|.. C_com_evolsoft_ec_runtime_monitor_TimeTraceManager
C_com_evolsoft_ec_runtime_monitor_AbstractMonitorItemViewPart --> C_com_evolsoft_ec_runtime_monitor_IMonitorItem
C_com_evolsoft_ec_runtime_monitor_ECMonitorUtils --> C_com_evolsoft_ec_runtime_monitor_ITimeSeriesDataListener
C_com_evolsoft_ec_runtime_monitor_MonitorItemChangedEvent --> C_com_evolsoft_ec_runtime_monitor_IMonitorItem
C_com_evolsoft_ec_runtime_monitor_MonitorTriggerArgs --> C_com_evolsoft_ec_runtime_monitor_MonitorTriggerType
C_com_evolsoft_ec_runtime_monitor_ParetoDataChangeEvent --> C_com_evolsoft_ec_runtime_monitor_SeriesEventType
C_com_evolsoft_ec_runtime_monitor_ParetoDataChangedListener --> C_com_evolsoft_ec_runtime_monitor_MonitorObject
C_com_evolsoft_ec_runtime_monitor_SeriesDataChangeEvent --> C_com_evolsoft_ec_runtime_monitor_SeriesEventType
C_com_evolsoft_ec_runtime_monitor_SeriesDataChangeEvent --> C_com_evolsoft_ec_runtime_monitor_XYDataSet
C_com_evolsoft_ec_runtime_monitor_TimeSeriesDataListener --> C_com_evolsoft_ec_runtime_monitor_MonitorObject
C_com_evolsoft_ec_runtime_monitor_TimeTraceManager --> C_com_evolsoft_ec_runtime_monitor_TraceItem
@enduml
