@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.ecoperation.section

interface "ISectionOperation" as C_com_evolsoft_ec_runtime_ecoperation_section_ISectionOperation
interface "ISectionOperationPolicy" as C_com_evolsoft_ec_runtime_ecoperation_section_ISectionOperationPolicy
class "SectionCrossoverBase" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionCrossoverBase
class "SectionCustomBase" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionCustomBase
class "SectionCutPoint" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionCutPoint
class "SectionMutationBase" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionMutationBase
class "SectionOperationBase" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationBase
class "SectionOperationException" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationException
class "SectionUtils" as C_com_evolsoft_ec_runtime_ecoperation_section_SectionUtils

C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationBase <|-- C_com_evolsoft_ec_runtime_ecoperation_section_SectionCrossoverBase
C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationBase <|-- C_com_evolsoft_ec_runtime_ecoperation_section_SectionCustomBase
C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationBase <|-- C_com_evolsoft_ec_runtime_ecoperation_section_SectionMutationBase
C_com_evolsoft_ec_runtime_ecoperation_section_ISectionOperation <|.. C_com_evolsoft_ec_runtime_ecoperation_section_SectionOperationBase
@enduml
