@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.ganttChart

interface "GTChartBlock" as C_com_evolsoft_ec_toolbox_ganttChart_GTChartBlock
interface "GTDetailRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
interface "GTGroup" as C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
interface "GTItem" as C_com_evolsoft_ec_toolbox_ganttChart_GTItem
interface "GTMarker" as C_com_evolsoft_ec_toolbox_ganttChart_GTMarker
interface "GTMarktableRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow
interface "GTRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTRow
interface "GTRuler" as C_com_evolsoft_ec_toolbox_ganttChart_GTRuler
interface "GTSubGroup" as C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup
interface "GanttChartFactory" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartFactory
interface "GanttChartModel" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
interface "GanttChartPackage" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartPackage
interface "GanttChartable" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable
interface "Literals" as C_com_evolsoft_ec_toolbox_ganttChart_Literals
enum "MarkType" as C_com_evolsoft_ec_toolbox_ganttChart_MarkType
interface "Sortable" as C_com_evolsoft_ec_toolbox_ganttChart_Sortable

C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow
C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTRow
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTRuler
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup
C_com_evolsoft_ec_toolbox_ganttChart_Sortable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable
@enduml
