@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.section.ecoperation

interface "IRecombinationDescriptorSpec" as C_com_evolsoft_ec_configuration_section_ecoperation_IRecombinationDescriptorSpec
interface "ISectionActionDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionDescriptor
interface "ISectionActionRefDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionRefDescriptor
interface "ISectionCrossOverDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionCrossOverDescriptor
interface "ISectionMutationDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionMutationDescriptor
interface "ISectionRecombinationDescriptorGroupSpec" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionRecombinationDescriptorGroupSpec
interface "ISectionRecombinationDescriptorReference" as C_com_evolsoft_ec_configuration_section_ecoperation_ISectionRecombinationDescriptorReference
class "InvalidActionException" as C_com_evolsoft_ec_configuration_section_ecoperation_InvalidActionException
class "Messages" as C_com_evolsoft_ec_configuration_section_ecoperation_Messages
class "SecctionActionRefDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_SecctionActionRefDescriptor
class "SectionRecombinationDescriptor" as C_com_evolsoft_ec_configuration_section_ecoperation_SectionRecombinationDescriptor
class "SectionRecombinationManager" as C_com_evolsoft_ec_configuration_section_ecoperation_SectionRecombinationManager

C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionDescriptor <|-- C_com_evolsoft_ec_configuration_section_ecoperation_ISectionCrossOverDescriptor
C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionDescriptor <|-- C_com_evolsoft_ec_configuration_section_ecoperation_ISectionMutationDescriptor
C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionRefDescriptor <|-- C_com_evolsoft_ec_configuration_section_ecoperation_ISectionRecombinationDescriptorReference
C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionRefDescriptor <|.. C_com_evolsoft_ec_configuration_section_ecoperation_SecctionActionRefDescriptor
C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionDescriptor <|.. C_com_evolsoft_ec_configuration_section_ecoperation_SectionRecombinationDescriptor
C_com_evolsoft_ec_configuration_section_ecoperation_SecctionActionRefDescriptor --> C_com_evolsoft_ec_configuration_section_ecoperation_ISectionActionDescriptor
@enduml
