@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.problem.fjsp.layout

class "KnowledgeBasedRefinementLayout" as C_com_evolsoft_problem_fjsp_layout_KnowledgeBasedRefinementLayout
class "KnowledgeBasedSeqSectionLayout" as C_com_evolsoft_problem_fjsp_layout_KnowledgeBasedSeqSectionLayout
class "OperationBasedGeneLayout" as C_com_evolsoft_problem_fjsp_layout_OperationBasedGeneLayout
class "OperationBasedSectionLayout" as C_com_evolsoft_problem_fjsp_layout_OperationBasedSectionLayout

C_com_evolsoft_problem_fjsp_layout_KnowledgeBasedRefinementLayout --> C_com_evolsoft_problem_fjsp_layout_OperationBasedGeneLayout
C_com_evolsoft_problem_fjsp_layout_KnowledgeBasedSeqSectionLayout --> C_com_evolsoft_problem_fjsp_layout_OperationBasedGeneLayout
@enduml
