@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.problem.objective

class "AbstractMonitorActivator" as C_com_evolsoft_core_runtime_problem_objective_AbstractMonitorActivator
enum "ComparisonResult" as C_com_evolsoft_core_runtime_problem_objective_ComparisonResult
class "DummyObjectiveValue" as C_com_evolsoft_core_runtime_problem_objective_DummyObjectiveValue
class "EvalutionValue" as C_com_evolsoft_core_runtime_problem_objective_EvalutionValue
interface "IEvalutionValue" as C_com_evolsoft_core_runtime_problem_objective_IEvalutionValue
interface "IObjectiveEstimator" as C_com_evolsoft_core_runtime_problem_objective_IObjectiveEstimator
interface "IObjectiveFunction" as C_com_evolsoft_core_runtime_problem_objective_IObjectiveFunction
interface "IObjectiveNotifyListener" as C_com_evolsoft_core_runtime_problem_objective_IObjectiveNotifyListener
interface "IObjectiveValue" as C_com_evolsoft_core_runtime_problem_objective_IObjectiveValue
interface "IQuantitiveFunction" as C_com_evolsoft_core_runtime_problem_objective_IQuantitiveFunction
interface "ISolutionContainer" as C_com_evolsoft_core_runtime_problem_objective_ISolutionContainer
class "ObjeciveFunctionProxy" as C_com_evolsoft_core_runtime_problem_objective_ObjeciveFunctionProxy
class "ObjectiveEstimator" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveEstimator
class "ObjectiveException" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveException
class "ObjectiveFunctionBase" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase
class "ObjectiveFunctionProxy" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionProxy
class "ObjectiveIndicesComparator" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveIndicesComparator
class "ObjectiveNotSupportedException" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveNotSupportedException
class "ObjectiveUtils" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveUtils
class "ObjectiveValue" as C_com_evolsoft_core_runtime_problem_objective_ObjectiveValue
class "StatisticMonitorBase" as C_com_evolsoft_core_runtime_problem_objective_StatisticMonitorBase

C_com_evolsoft_core_runtime_problem_objective_ObjectiveValue <|-- C_com_evolsoft_core_runtime_problem_objective_DummyObjectiveValue
C_com_evolsoft_core_runtime_problem_objective_IQuantitiveFunction <|-- C_com_evolsoft_core_runtime_problem_objective_IObjectiveFunction
C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase <|-- C_com_evolsoft_core_runtime_problem_objective_ObjeciveFunctionProxy
C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase <|-- C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionProxy
C_com_evolsoft_core_runtime_problem_objective_AbstractMonitorActivator <|-- C_com_evolsoft_core_runtime_problem_objective_StatisticMonitorBase
C_com_evolsoft_core_runtime_problem_objective_IEvalutionValue <|.. C_com_evolsoft_core_runtime_problem_objective_EvalutionValue
C_com_evolsoft_core_runtime_problem_objective_IObjectiveEstimator <|.. C_com_evolsoft_core_runtime_problem_objective_ObjectiveEstimator
C_com_evolsoft_core_runtime_problem_objective_IObjectiveFunction <|.. C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase
C_com_evolsoft_core_runtime_problem_objective_IObjectiveValue <|.. C_com_evolsoft_core_runtime_problem_objective_ObjectiveValue
C_com_evolsoft_core_runtime_problem_objective_EvalutionValue --> C_com_evolsoft_core_runtime_problem_objective_ComparisonResult
C_com_evolsoft_core_runtime_problem_objective_EvalutionValue --> C_com_evolsoft_core_runtime_problem_objective_IObjectiveValue
C_com_evolsoft_core_runtime_problem_objective_ObjectiveEstimator --> C_com_evolsoft_core_runtime_problem_objective_IObjectiveFunction
C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase --> C_com_evolsoft_core_runtime_problem_objective_ComparisonResult
C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase --> C_com_evolsoft_core_runtime_problem_objective_ISolutionContainer
C_com_evolsoft_core_runtime_problem_objective_ObjectiveFunctionBase --> C_com_evolsoft_core_runtime_problem_objective_ObjectiveIndicesComparator
C_com_evolsoft_core_runtime_problem_objective_ObjectiveValue --> C_com_evolsoft_core_runtime_problem_objective_IObjectiveFunction
@enduml
