@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.report.internal

class "AbstractReporterBase" as C_com_evolsoft_ec_runtime_report_internal_AbstractReporterBase
class "FitnessValueReporter" as C_com_evolsoft_ec_runtime_report_internal_FitnessValueReporter
interface "IFitnessReporter" as C_com_evolsoft_ec_runtime_report_internal_IFitnessReporter
interface "IParetoListenerManager" as C_com_evolsoft_ec_runtime_report_internal_IParetoListenerManager
interface "IParetoReporter" as C_com_evolsoft_ec_runtime_report_internal_IParetoReporter
interface "IReport" as C_com_evolsoft_ec_runtime_report_internal_IReport
interface "ITimeSeriesListenerManager" as C_com_evolsoft_ec_runtime_report_internal_ITimeSeriesListenerManager
class "MonitorPointMgr" as C_com_evolsoft_ec_runtime_report_internal_MonitorPointMgr
class "ParetoExportException" as C_com_evolsoft_ec_runtime_report_internal_ParetoExportException
class "ParetoListenerManager" as C_com_evolsoft_ec_runtime_report_internal_ParetoListenerManager
class "ParetoReporter" as C_com_evolsoft_ec_runtime_report_internal_ParetoReporter
class "SingleObjectiveReporter" as C_com_evolsoft_ec_runtime_report_internal_SingleObjectiveReporter
class "TimeSeriesEventArgs" as C_com_evolsoft_ec_runtime_report_internal_TimeSeriesEventArgs
class "TimeSeriesListenerManager" as C_com_evolsoft_ec_runtime_report_internal_TimeSeriesListenerManager

C_com_evolsoft_ec_runtime_report_internal_IReport <|-- C_com_evolsoft_ec_runtime_report_internal_IParetoReporter
C_com_evolsoft_ec_runtime_report_internal_AbstractReporterBase <|-- C_com_evolsoft_ec_runtime_report_internal_ParetoReporter
C_com_evolsoft_ec_runtime_report_internal_IReport <|.. C_com_evolsoft_ec_runtime_report_internal_AbstractReporterBase
C_com_evolsoft_ec_runtime_report_internal_IFitnessReporter <|.. C_com_evolsoft_ec_runtime_report_internal_FitnessValueReporter
C_com_evolsoft_ec_runtime_report_internal_IParetoListenerManager <|.. C_com_evolsoft_ec_runtime_report_internal_ParetoListenerManager
C_com_evolsoft_ec_runtime_report_internal_IParetoReporter <|.. C_com_evolsoft_ec_runtime_report_internal_ParetoReporter
C_com_evolsoft_ec_runtime_report_internal_ITimeSeriesListenerManager <|.. C_com_evolsoft_ec_runtime_report_internal_TimeSeriesListenerManager
C_com_evolsoft_ec_runtime_report_internal_AbstractReporterBase --> C_com_evolsoft_ec_runtime_report_internal_MonitorPointMgr
C_com_evolsoft_ec_runtime_report_internal_ParetoReporter --> C_com_evolsoft_ec_runtime_report_internal_IParetoListenerManager
@enduml
