@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.problem.dataprovider

class "Benchmark" as C_com_evolsoft_core_runtime_problem_dataprovider_Benchmark
class "BenchmarkDataReader" as C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkDataReader
class "BenchmarkRepository" as C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository
class "Category" as C_com_evolsoft_core_runtime_problem_dataprovider_Category
class "DataNotFoundException" as C_com_evolsoft_core_runtime_problem_dataprovider_DataNotFoundException
class "DataProviderBase" as C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderBase
class "DataProviderConsoleBase" as C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderConsoleBase
interface "IDataLoader" as C_com_evolsoft_core_runtime_problem_dataprovider_IDataLoader
interface "IDataProvider" as C_com_evolsoft_core_runtime_problem_dataprovider_IDataProvider
class "IllegalFormatException" as C_com_evolsoft_core_runtime_problem_dataprovider_IllegalFormatException
interface "ProviderDesc" as C_com_evolsoft_core_runtime_problem_dataprovider_ProviderDesc
class "RepositoryNotFoundException" as C_com_evolsoft_core_runtime_problem_dataprovider_RepositoryNotFoundException
class "TestCase" as C_com_evolsoft_core_runtime_problem_dataprovider_TestCase

C_com_evolsoft_core_runtime_problem_dataprovider_IDataProvider <|.. C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderBase
C_com_evolsoft_core_runtime_problem_dataprovider_Benchmark --> C_com_evolsoft_core_runtime_problem_dataprovider_Category
C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkDataReader --> C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository
C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkDataReader --> C_com_evolsoft_core_runtime_problem_dataprovider_TestCase
C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository --> C_com_evolsoft_core_runtime_problem_dataprovider_Benchmark
C_com_evolsoft_core_runtime_problem_dataprovider_Category --> C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository
C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderBase --> C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository
C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderBase --> C_com_evolsoft_core_runtime_problem_dataprovider_IDataLoader
C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderBase --> C_com_evolsoft_core_runtime_problem_dataprovider_TestCase
C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderConsoleBase --> C_com_evolsoft_core_runtime_problem_dataprovider_BenchmarkRepository
C_com_evolsoft_core_runtime_problem_dataprovider_DataProviderConsoleBase --> C_com_evolsoft_core_runtime_problem_dataprovider_IDataLoader
@enduml
