@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.msga.gpsiff

class "GPSIFFFitnessService" as C_com_evolsoft_ec_msga_gpsiff_GPSIFFFitnessService

@enduml
