@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor.viewModel

interface "IECMonitorView" as C_com_evolsoft_ec_runtime_monitor_viewModel_IECMonitorView
interface "IMTAbstractGeneValue" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneValue
interface "IMTAbstractGeneration" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneration
interface "IMTAbstractProcessItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem
interface "IMTAbstractViewItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractViewItem
interface "IMTCondition" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTCondition
interface "IMTContainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer
interface "IMTCurGeneration" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTCurGeneration
interface "IMTDecisionValue" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTDecisionValue
interface "IMTECApplication" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTECApplication
interface "IMTECStrategy" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTECStrategy
interface "IMTGeneValue" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTGeneValue
interface "IMTIndividual" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTIndividual
interface "IMTIndividualContrainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTIndividualContrainer
interface "IMTMonitorItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTMonitorItem
interface "IMTMonitorItemContainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTMonitorItemContainer
interface "IMTNextGeneration" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTNextGeneration
interface "IMTObjective" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjective
interface "IMTObjectiveContainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjectiveContainer
interface "IMTObjectives" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjectives
interface "IMTOffsprings" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTOffsprings
interface "IMTPRCDoWhile" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPRCDoWhile
interface "IMTPRCWhile" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPRCWhile
interface "IMTParameter" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTParameter
interface "IMTPopulation" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPopulation
interface "IMTPrimitiveGeneValue" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPrimitiveGeneValue
interface "IMTProcessItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTProcessItem
interface "IMTSpecies" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpecies
interface "IMTSpeciesItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem
interface "IMTSpeciesItemBase" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemBase
interface "IMTSpeciesItemContainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer
interface "IMTTraceItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTTraceItem
interface "IMTTraceItemContainer" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTTraceItemContainer
interface "IMTViewItem" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTViewItem
interface "IMTViewItemDescriptor" as C_com_evolsoft_ec_runtime_monitor_viewModel_IMTViewItemDescriptor
interface "IViewModelFactory" as C_com_evolsoft_ec_runtime_monitor_viewModel_IViewModelFactory
interface "IViewModelPackage" as C_com_evolsoft_ec_runtime_monitor_viewModel_IViewModelPackage
interface "Literals" as C_com_evolsoft_ec_runtime_monitor_viewModel_Literals

C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneValue
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneration
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTCondition
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractViewItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneration <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTCurGeneration
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneValue <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTDecisionValue
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTECApplication
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTECStrategy
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTGeneValue
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTIndividual
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTIndividualContrainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTViewItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTMonitorItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTMonitorItemContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneration <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTNextGeneration
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjective
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjectiveContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTObjectives
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTOffsprings
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPRCDoWhile
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPRCWhile
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTParameter
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPopulation
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractGeneValue <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTPrimitiveGeneValue
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractProcessItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTProcessItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpecies
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemBase <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpecies
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractViewItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemBase <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemBase <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTTraceItem
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTSpeciesItemContainer <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTTraceItemContainer
C_com_evolsoft_ec_runtime_monitor_viewModel_IMTAbstractViewItem <|-- C_com_evolsoft_ec_runtime_monitor_viewModel_IMTViewItem
@enduml
