@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration

class "ECConfigNotDefinedException" as C_com_evolsoft_core_configuration_ECConfigNotDefinedException
class "ECStatus" as C_com_evolsoft_core_configuration_ECStatus
interface "ICommonAttributeSpec" as C_com_evolsoft_core_configuration_ICommonAttributeSpec
interface "ICoreConfigFactory" as C_com_evolsoft_core_configuration_ICoreConfigFactory
interface "ICoreConfigPackage" as C_com_evolsoft_core_configuration_ICoreConfigPackage
interface "IECDataLoaderDescriptor" as C_com_evolsoft_core_configuration_IECDataLoaderDescriptor
interface "IECParameter" as C_com_evolsoft_core_configuration_IECParameter
interface "IECParameterContainer" as C_com_evolsoft_core_configuration_IECParameterContainer
interface "IIdentifiableSpec" as C_com_evolsoft_core_configuration_IIdentifiableSpec
interface "IMarshalable" as C_com_evolsoft_core_configuration_IMarshalable
interface "IPlugInVersionObject" as C_com_evolsoft_core_configuration_IPlugInVersionObject
interface "IPluginConfigurable" as C_com_evolsoft_core_configuration_IPluginConfigurable
interface "IVersionSpec" as C_com_evolsoft_core_configuration_IVersionSpec
interface "Literals" as C_com_evolsoft_core_configuration_Literals
interface "ServiceItemAttribute" as C_com_evolsoft_core_configuration_ServiceItemAttribute

C_com_evolsoft_core_configuration_IIdentifiableSpec <|-- C_com_evolsoft_core_configuration_ICommonAttributeSpec
C_com_evolsoft_core_configuration_IPluginConfigurable <|-- C_com_evolsoft_core_configuration_IECDataLoaderDescriptor
C_com_evolsoft_core_configuration_IPluginConfigurable <|-- C_com_evolsoft_core_configuration_IECParameter
C_com_evolsoft_core_configuration_IPluginConfigurable <|-- C_com_evolsoft_core_configuration_IECParameterContainer
C_com_evolsoft_core_configuration_IPluginConfigurable <|-- C_com_evolsoft_core_configuration_IPlugInVersionObject
C_com_evolsoft_core_configuration_IMarshalable <|-- C_com_evolsoft_core_configuration_IPluginConfigurable
C_com_evolsoft_core_configuration_IIdentifiableSpec <|-- C_com_evolsoft_core_configuration_IVersionSpec
@enduml
