@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.problem.rcpsp.template

class "RCPSPTemplate" as C_com_evolsoft_ec_problem_rcpsp_template_RCPSPTemplate

@enduml
