@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.impl

class "AbstractActiveObjectBase" as C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase
class "Componentbase" as C_com_evolsoft_core_runtime_impl_Componentbase
class "CoreRuntimeFactory" as C_com_evolsoft_core_runtime_impl_CoreRuntimeFactory
class "CoreRuntimePackage" as C_com_evolsoft_core_runtime_impl_CoreRuntimePackage
class "ECProfile" as C_com_evolsoft_core_runtime_impl_ECProfile
class "IdentifiableObject" as C_com_evolsoft_core_runtime_impl_IdentifiableObject
class "LogContext" as C_com_evolsoft_core_runtime_impl_LogContext
class "PredecessorProxy" as C_com_evolsoft_core_runtime_impl_PredecessorProxy
class "SolutionContext" as C_com_evolsoft_core_runtime_impl_SolutionContext
class "VersionObject" as C_com_evolsoft_core_runtime_impl_VersionObject
class "WaitQueue" as C_com_evolsoft_core_runtime_impl_WaitQueue

C_com_evolsoft_core_runtime_impl_IdentifiableObject <|-- C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase
C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase <|-- C_com_evolsoft_core_runtime_impl_Componentbase
C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase <|-- C_com_evolsoft_core_runtime_impl_PredecessorProxy
C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase <|-- C_com_evolsoft_core_runtime_impl_SolutionContext
C_com_evolsoft_core_runtime_impl_IdentifiableObject <|-- C_com_evolsoft_core_runtime_impl_VersionObject
C_com_evolsoft_core_runtime_impl_AbstractActiveObjectBase --> C_com_evolsoft_core_runtime_impl_WaitQueue
C_com_evolsoft_core_runtime_impl_ECProfile --> C_com_evolsoft_core_runtime_impl_LogContext
@enduml
