@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.monitor

interface "IECCFGMonitorFactory" as C_com_evolsoft_ec_configuration_monitor_IECCFGMonitorFactory
interface "IECCFGMonitorPackage" as C_com_evolsoft_ec_configuration_monitor_IECCFGMonitorPackage
interface "IMonitorItemDescriptor" as C_com_evolsoft_ec_configuration_monitor_IMonitorItemDescriptor
interface "IMonitorItemRefDescriptor" as C_com_evolsoft_ec_configuration_monitor_IMonitorItemRefDescriptor
interface "IMonitorItemRefDescriptorManager" as C_com_evolsoft_ec_configuration_monitor_IMonitorItemRefDescriptorManager
interface "IMonitorListenerDescriptor" as C_com_evolsoft_ec_configuration_monitor_IMonitorListenerDescriptor
interface "IMonitorTriggerDescriptor" as C_com_evolsoft_ec_configuration_monitor_IMonitorTriggerDescriptor
interface "ITriggerDetail" as C_com_evolsoft_ec_configuration_monitor_ITriggerDetail
interface "ITriggerDetailList" as C_com_evolsoft_ec_configuration_monitor_ITriggerDetailList
interface "ITriggerType" as C_com_evolsoft_ec_configuration_monitor_ITriggerType
interface "ITriggerTypeList" as C_com_evolsoft_ec_configuration_monitor_ITriggerTypeList
interface "Literals" as C_com_evolsoft_ec_configuration_monitor_Literals

@enduml
