@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.pbil.viewer.refine

class "HistgramLableProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_HistgramLableProviderEx
class "PBMatrixDataProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixDataProviderEx
class "PBMatrixLabelProviderEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixLabelProviderEx
class "PBMatrixTestViewerEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTestViewerEx
class "PBMatrixTraceItemEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx
class "PBMatrixViewerEx" as C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixViewerEx
class "StyleOwnerDrawLabelProvider" as C_com_evolsoft_ec_pbil_viewer_refine_StyleOwnerDrawLabelProvider

C_com_evolsoft_ec_pbil_viewer_refine_StyleOwnerDrawLabelProvider <|-- C_com_evolsoft_ec_pbil_viewer_refine_HistgramLableProviderEx
C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTestViewerEx --> C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx
C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixTraceItemEx --> C_com_evolsoft_ec_pbil_viewer_refine_PBMatrixViewerEx
@enduml
