@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.problem.fjsp.FJSPModel.adapter

class "FJSP2DataProvider" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSP2DataProvider
class "FJSPCSVReader" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSPCSVReader
interface "IFJSP2DataProvider" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IFJSP2DataProvider
class "IdentifiyingIndeices" as C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IdentifiyingIndeices

C_com_evolsoft_problem_fjsp_FJSPModel_adapter_IFJSP2DataProvider <|.. C_com_evolsoft_problem_fjsp_FJSPModel_adapter_FJSP2DataProvider
@enduml
