@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor.trigger

class "FitnessMontiorTrigger" as C_com_evolsoft_ec_runtime_monitor_trigger_FitnessMontiorTrigger
class "MontiorTrigger4Generation" as C_com_evolsoft_ec_runtime_monitor_trigger_MontiorTrigger4Generation
class "MontiorTrigger4Individual" as C_com_evolsoft_ec_runtime_monitor_trigger_MontiorTrigger4Individual
class "ObjectiveMontiorTrigger" as C_com_evolsoft_ec_runtime_monitor_trigger_ObjectiveMontiorTrigger
class "ParetoMonitorTrigger" as C_com_evolsoft_ec_runtime_monitor_trigger_ParetoMonitorTrigger

C_com_evolsoft_ec_runtime_monitor_trigger_MontiorTrigger4Individual <|-- C_com_evolsoft_ec_runtime_monitor_trigger_FitnessMontiorTrigger
C_com_evolsoft_ec_runtime_monitor_trigger_MontiorTrigger4Individual <|-- C_com_evolsoft_ec_runtime_monitor_trigger_ObjectiveMontiorTrigger
C_com_evolsoft_ec_runtime_monitor_trigger_MontiorTrigger4Generation <|-- C_com_evolsoft_ec_runtime_monitor_trigger_ParetoMonitorTrigger
@enduml
