@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.pbil.probability

class "CopyOfProbabilityMatrixBase" as C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase
interface "IMatrixMonitorItem" as C_com_evolsoft_ec_pbil_probability_IMatrixMonitorItem
interface "IProbabilityMatrix" as C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
class "JointProbabilityState" as C_com_evolsoft_ec_pbil_probability_JointProbabilityState
class "MatrixItemInfo" as C_com_evolsoft_ec_pbil_probability_MatrixItemInfo
class "MatrixMonitorItem" as C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem
class "ProbabilityHeader" as C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
class "ProbabilityItem" as C_com_evolsoft_ec_pbil_probability_ProbabilityItem
class "ProbabilityMatrix" as C_com_evolsoft_ec_pbil_probability_ProbabilityMatrix
class "ProbabilityMatrixBase" as C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase
class "ProbabilityVector" as C_com_evolsoft_ec_pbil_probability_ProbabilityVector
class "ProbabilityVectors" as C_com_evolsoft_ec_pbil_probability_ProbabilityVectors
class "ProbalityMatrixArray" as C_com_evolsoft_ec_pbil_probability_ProbalityMatrixArray

C_com_evolsoft_ec_pbil_probability_ProbabilityItem <|-- C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase <|-- C_com_evolsoft_ec_pbil_probability_ProbabilityMatrix
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase
C_com_evolsoft_ec_pbil_probability_IMatrixMonitorItem <|.. C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase
C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix <|.. C_com_evolsoft_ec_pbil_probability_ProbabilityVectors
C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_CopyOfProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_MatrixItemInfo --> C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
C_com_evolsoft_ec_pbil_probability_MatrixMonitorItem --> C_com_evolsoft_ec_pbil_probability_IProbabilityMatrix
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityMatrixBase --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_ProbabilityVector --> C_com_evolsoft_ec_pbil_probability_ProbabilityHeader
C_com_evolsoft_ec_pbil_probability_ProbabilityVector --> C_com_evolsoft_ec_pbil_probability_ProbabilityItem
C_com_evolsoft_ec_pbil_probability_ProbabilityVectors --> C_com_evolsoft_ec_pbil_probability_ProbabilityVector
@enduml
