@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.variables

interface "ECVariableAttribute" as C_com_evolsoft_core_configuration_variables_ECVariableAttribute
class "ECVariableUtils" as C_com_evolsoft_core_configuration_variables_ECVariableUtils
class "EnviromentDescriptor" as C_com_evolsoft_core_configuration_variables_EnviromentDescriptor
interface "IEnviormentDescriptor" as C_com_evolsoft_core_configuration_variables_IEnviormentDescriptor
class "IVaraibleDescriptorSpec" as C_com_evolsoft_core_configuration_variables_IVaraibleDescriptorSpec
interface "IVariableDescriptor" as C_com_evolsoft_core_configuration_variables_IVariableDescriptor
class "VariableDescriptor" as C_com_evolsoft_core_configuration_variables_VariableDescriptor

C_com_evolsoft_core_configuration_variables_IEnviormentDescriptor <|.. C_com_evolsoft_core_configuration_variables_EnviromentDescriptor
C_com_evolsoft_core_configuration_variables_IVariableDescriptor <|.. C_com_evolsoft_core_configuration_variables_VariableDescriptor
C_com_evolsoft_core_configuration_variables_EnviromentDescriptor --> C_com_evolsoft_core_configuration_variables_VariableDescriptor
@enduml
