@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.problem

class "AbstractProblemSolutionConverter" as C_com_evolsoft_core_runtime_problem_AbstractProblemSolutionConverter
class "AbstractSolutionChartProvider" as C_com_evolsoft_core_runtime_problem_AbstractSolutionChartProvider
class "AbstractSolutionConsoleConverter" as C_com_evolsoft_core_runtime_problem_AbstractSolutionConsoleConverter
class "ChartAction" as C_com_evolsoft_core_runtime_problem_ChartAction
class "DataProviderFactory" as C_com_evolsoft_core_runtime_problem_DataProviderFactory
class "DummySolutionChartProvider" as C_com_evolsoft_core_runtime_problem_DummySolutionChartProvider
class "ECProblemUtils" as C_com_evolsoft_core_runtime_problem_ECProblemUtils
interface "IDataEditor" as C_com_evolsoft_core_runtime_problem_IDataEditor
interface "IDataEditorDescriptorMgr" as C_com_evolsoft_core_runtime_problem_IDataEditorDescriptorMgr
interface "IDataEditorFactory" as C_com_evolsoft_core_runtime_problem_IDataEditorFactory
interface "IDataProviderDescriptorMgr" as C_com_evolsoft_core_runtime_problem_IDataProviderDescriptorMgr
interface "IDataProviderFactory" as C_com_evolsoft_core_runtime_problem_IDataProviderFactory
interface "IProblemActivator" as C_com_evolsoft_core_runtime_problem_IProblemActivator
interface "IProblemContext" as C_com_evolsoft_core_runtime_problem_IProblemContext
interface "IProblemDataConfig" as C_com_evolsoft_core_runtime_problem_IProblemDataConfig
interface "IProblemDescriptor" as C_com_evolsoft_core_runtime_problem_IProblemDescriptor
interface "IProblemSolution" as C_com_evolsoft_core_runtime_problem_IProblemSolution
interface "IProblemSolutionVerifier" as C_com_evolsoft_core_runtime_problem_IProblemSolutionVerifier
interface "ISolutionChartProvider" as C_com_evolsoft_core_runtime_problem_ISolutionChartProvider
interface "ISolutionConsoleConverter" as C_com_evolsoft_core_runtime_problem_ISolutionConsoleConverter
interface "ISolutionConverter" as C_com_evolsoft_core_runtime_problem_ISolutionConverter
interface "ISolutionProvider" as C_com_evolsoft_core_runtime_problem_ISolutionProvider
class "InvalidDefintionException" as C_com_evolsoft_core_runtime_problem_InvalidDefintionException
class "ProblemActionBase" as C_com_evolsoft_core_runtime_problem_ProblemActionBase
class "ProblemActivatorBase" as C_com_evolsoft_core_runtime_problem_ProblemActivatorBase
class "ProblemContext" as C_com_evolsoft_core_runtime_problem_ProblemContext
class "ProblemDataConfig" as C_com_evolsoft_core_runtime_problem_ProblemDataConfig
class "ProblemDataEditorBase" as C_com_evolsoft_core_runtime_problem_ProblemDataEditorBase
class "ProblemService" as C_com_evolsoft_core_runtime_problem_ProblemService
class "ProblemSolutionBase" as C_com_evolsoft_core_runtime_problem_ProblemSolutionBase
class "ProblemSolutionVeriferBase" as C_com_evolsoft_core_runtime_problem_ProblemSolutionVeriferBase
class "ShowSolutionHandler" as C_com_evolsoft_core_runtime_problem_ShowSolutionHandler
class "SolutionFileDescriptor" as C_com_evolsoft_core_runtime_problem_SolutionFileDescriptor
class "SolutionMetaDescriptorConverter" as C_com_evolsoft_core_runtime_problem_SolutionMetaDescriptorConverter

C_com_evolsoft_core_runtime_problem_ISolutionConverter <|.. C_com_evolsoft_core_runtime_problem_AbstractProblemSolutionConverter
C_com_evolsoft_core_runtime_problem_ISolutionChartProvider <|.. C_com_evolsoft_core_runtime_problem_AbstractSolutionChartProvider
C_com_evolsoft_core_runtime_problem_ISolutionConsoleConverter <|.. C_com_evolsoft_core_runtime_problem_AbstractSolutionConsoleConverter
C_com_evolsoft_core_runtime_problem_IDataProviderFactory <|.. C_com_evolsoft_core_runtime_problem_DataProviderFactory
C_com_evolsoft_core_runtime_problem_ISolutionChartProvider <|.. C_com_evolsoft_core_runtime_problem_DummySolutionChartProvider
C_com_evolsoft_core_runtime_problem_IProblemActivator <|.. C_com_evolsoft_core_runtime_problem_ProblemActivatorBase
C_com_evolsoft_core_runtime_problem_IProblemContext <|.. C_com_evolsoft_core_runtime_problem_ProblemContext
C_com_evolsoft_core_runtime_problem_IProblemDataConfig <|.. C_com_evolsoft_core_runtime_problem_ProblemDataConfig
C_com_evolsoft_core_runtime_problem_IDataEditor <|.. C_com_evolsoft_core_runtime_problem_ProblemDataEditorBase
C_com_evolsoft_core_runtime_problem_IProblemSolution <|.. C_com_evolsoft_core_runtime_problem_ProblemSolutionBase
C_com_evolsoft_core_runtime_problem_IProblemSolutionVerifier <|.. C_com_evolsoft_core_runtime_problem_ProblemSolutionVeriferBase
C_com_evolsoft_core_runtime_problem_AbstractSolutionChartProvider --> C_com_evolsoft_core_runtime_problem_SolutionFileDescriptor
C_com_evolsoft_core_runtime_problem_ECProblemUtils --> C_com_evolsoft_core_runtime_problem_IProblemSolution
C_com_evolsoft_core_runtime_problem_ECProblemUtils --> C_com_evolsoft_core_runtime_problem_SolutionFileDescriptor
C_com_evolsoft_core_runtime_problem_ProblemActionBase --> C_com_evolsoft_core_runtime_problem_IProblemContext
C_com_evolsoft_core_runtime_problem_ProblemContext --> C_com_evolsoft_core_runtime_problem_IProblemSolutionVerifier
C_com_evolsoft_core_runtime_problem_ProblemSolutionVeriferBase --> C_com_evolsoft_core_runtime_problem_IProblemContext
C_com_evolsoft_core_runtime_problem_SolutionFileDescriptor --> C_com_evolsoft_core_runtime_problem_IProblemDescriptor
C_com_evolsoft_core_runtime_problem_SolutionFileDescriptor --> C_com_evolsoft_core_runtime_problem_IProblemSolution
@enduml
