@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.toolbox.policyTree

interface "Literals" as C_com_evolsoft_ec_toolbox_policyTree_Literals
interface "PTItem" as C_com_evolsoft_ec_toolbox_policyTree_PTItem
interface "PTPolicyTree" as C_com_evolsoft_ec_toolbox_policyTree_PTPolicyTree
interface "PTTreeEdge" as C_com_evolsoft_ec_toolbox_policyTree_PTTreeEdge
interface "PTTreeNode" as C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
interface "PolicyTreeFactory" as C_com_evolsoft_ec_toolbox_policyTree_PolicyTreeFactory
interface "PolicyTreePackage" as C_com_evolsoft_ec_toolbox_policyTree_PolicyTreePackage
class "PolicyTreePlugin" as C_com_evolsoft_ec_toolbox_policyTree_PolicyTreePlugin
class "PTItemImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PTItemImpl
class "PTPolicyTreeImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PTPolicyTreeImpl
class "PTTreeEdgeImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeEdgeImpl
class "PTTreeNodeImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeNodeImpl
class "PolicyTreeFactoryImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PolicyTreeFactoryImpl
class "PolicyTreePackageImpl" as C_com_evolsoft_ec_toolbox_policyTree_impl_PolicyTreePackageImpl
class "FullBiTreeTest" as C_com_evolsoft_ec_toolbox_policyTree_mills_FullBiTreeTest
class "PolicyTreeAdapterFactory" as C_com_evolsoft_ec_toolbox_policyTree_util_PolicyTreeAdapterFactory
class "PolicyTreeSwitch" as C_com_evolsoft_ec_toolbox_policyTree_util_PolicyTreeSwitch
class "NodeFigure" as C_com_evolsoft_ec_toolbox_policyTree_view_NodeFigure
class "PolicyTreeContentProvider" as C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeContentProvider
class "PolicyTreeLabelProvider" as C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeLabelProvider
class "PolicyTreeView" as C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeView
class "TreeLayoutActions" as C_com_evolsoft_ec_toolbox_policyTree_view_TreeLayoutActions
interface "PluginResourceProvider (com.evolsoft.ec.toolbox.policyTree)" as C_org_eclipse_wb_swt_PluginResourceProvider__dup3
class "ResourceManager (com.evolsoft.ec.toolbox.policyTree)" as C_org_eclipse_wb_swt_ResourceManager__dup3
class "SWTResourceManager (com.evolsoft.ec.toolbox.policyTree)" as C_org_eclipse_wb_swt_SWTResourceManager__dup3

C_com_evolsoft_ec_toolbox_policyTree_PTItem <|-- C_com_evolsoft_ec_toolbox_policyTree_PTTreeEdge
C_com_evolsoft_ec_toolbox_policyTree_PTItem <|-- C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
C_com_evolsoft_ec_toolbox_policyTree_impl_PTItemImpl <|-- C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeEdgeImpl
C_com_evolsoft_ec_toolbox_policyTree_impl_PTItemImpl <|-- C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeNodeImpl
C_com_evolsoft_ec_toolbox_policyTree_PTItem <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PTItemImpl
C_com_evolsoft_ec_toolbox_policyTree_PTPolicyTree <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PTPolicyTreeImpl
C_com_evolsoft_ec_toolbox_policyTree_PTTreeEdge <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeEdgeImpl
C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeNodeImpl
C_com_evolsoft_ec_toolbox_policyTree_PolicyTreeFactory <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PolicyTreeFactoryImpl
C_com_evolsoft_ec_toolbox_policyTree_PolicyTreePackage <|.. C_com_evolsoft_ec_toolbox_policyTree_impl_PolicyTreePackageImpl
C_com_evolsoft_ec_toolbox_policyTree_impl_PTItemImpl --> C_com_evolsoft_ec_toolbox_policyTree_PTPolicyTree
C_com_evolsoft_ec_toolbox_policyTree_impl_PTPolicyTreeImpl --> C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeEdgeImpl --> C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeNodeImpl --> C_com_evolsoft_ec_toolbox_policyTree_PTTreeEdge
C_com_evolsoft_ec_toolbox_policyTree_impl_PTTreeNodeImpl --> C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
C_com_evolsoft_ec_toolbox_policyTree_util_PolicyTreeAdapterFactory --> C_com_evolsoft_ec_toolbox_policyTree_PolicyTreePackage
C_com_evolsoft_ec_toolbox_policyTree_util_PolicyTreeSwitch --> C_com_evolsoft_ec_toolbox_policyTree_PolicyTreePackage
C_com_evolsoft_ec_toolbox_policyTree_view_NodeFigure --> C_com_evolsoft_ec_toolbox_policyTree_PTTreeNode
C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeContentProvider --> C_com_evolsoft_ec_toolbox_policyTree_PTPolicyTree
C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeView --> C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeContentProvider
C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeView --> C_com_evolsoft_ec_toolbox_policyTree_view_PolicyTreeLabelProvider
@enduml
