@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.toolbox.GanttChart

class "ColumnLabelProviderEx" as C_com_evolsoft_ec_simulator_ColumnLabelProviderEx
class "SimulationAction" as C_com_evolsoft_ec_simulator_SimulationAction
class "SimulatorDataProvider" as C_com_evolsoft_ec_simulator_SimulatorDataProvider
class "SimulatorViewer" as C_com_evolsoft_ec_simulator_SimulatorViewer
class "SimulatorWindow" as C_com_evolsoft_ec_simulator_SimulatorWindow
class "StyleItem" as C_com_evolsoft_ec_simulator_StyleItem
class "TextStyleRender" as C_com_evolsoft_ec_simulator_TextStyleRender
interface "GTChartBlock" as C_com_evolsoft_ec_toolbox_ganttChart_GTChartBlock
interface "GTDetailRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
interface "GTGroup" as C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
interface "GTItem" as C_com_evolsoft_ec_toolbox_ganttChart_GTItem
interface "GTMarker" as C_com_evolsoft_ec_toolbox_ganttChart_GTMarker
interface "GTMarktableRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow
interface "GTRow" as C_com_evolsoft_ec_toolbox_ganttChart_GTRow
interface "GTRuler" as C_com_evolsoft_ec_toolbox_ganttChart_GTRuler
interface "GTSubGroup" as C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup
interface "GanttChartFactory" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartFactory
interface "GanttChartModel" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
interface "GanttChartPackage" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartPackage
interface "GanttChartable" as C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable
interface "Literals" as C_com_evolsoft_ec_toolbox_ganttChart_Literals
enum "MarkType" as C_com_evolsoft_ec_toolbox_ganttChart_MarkType
interface "Sortable" as C_com_evolsoft_ec_toolbox_ganttChart_Sortable
class "GTDetailRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl
class "GTGroupImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl
class "GTItemImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl
class "GTItemProxy" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemProxy
class "GTMarkerImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarkerImpl
class "GTMarktableRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl
class "GTRowImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl
class "GTRulerImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl
class "GTSubGroupImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl
class "GanttChartFactoryImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartFactoryImpl
class "GanttChartModelImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl
class "GanttChartPackageImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartPackageImpl
class "GanttChartableImpl" as C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl
class "ColumnMetaData" as C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData
class "ColumnViewerToolTipSupportEx" as C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnViewerToolTipSupportEx
class "GTRenderUtils" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GTRenderUtils
class "GanttChartContentProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
class "Ganttchart" as C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
class "GroupSelectionEventArgs" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupSelectionEventArgs
class "GroupTagLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider
class "GroupTagProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
class "HighlightItemChangedEventArgs" as C_com_evolsoft_ec_toolbox_ganttChart_swt_HighlightItemChangedEventArgs
interface "IGTGroupSelectionListener" as C_com_evolsoft_ec_toolbox_ganttChart_swt_IGTGroupSelectionListener
interface "IHighlightItemChangedListener" as C_com_evolsoft_ec_toolbox_ganttChart_swt_IHighlightItemChangedListener
class "LegendCheckTreeViewer" as C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
class "Sorter" as C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter
class "TagItem" as C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
interface "must" as C_com_evolsoft_ec_toolbox_ganttChart_swt_must
class "GanttChartAdapterFactory" as C_com_evolsoft_ec_toolbox_ganttChart_util_GanttChartAdapterFactory
class "GanttChartSwitch" as C_com_evolsoft_ec_toolbox_ganttChart_util_GanttChartSwitch
class "ChartItem" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem
class "GanntchartLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanntchartLabelProvider
class "GantchartRender" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
class "GanttChartBuilder" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartBuilder
class "GanttChartPlugin" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin
class "GanttChartViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer
interface "IGanttChartSupportable" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartSupportable
interface "IGanttChartViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer
interface "IGanttChartViewerViewerMananger" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewerViewerMananger
interface "IGanttchartLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
interface "IScheduleBuilderViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer
class "ScheduleBuilderViewer" as C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer
interface "PluginResourceProvider (com.evolsoft.ec.toolbox.GanttChart)" as C_org_eclipse_wb_swt_PluginResourceProvider__dup2
class "ResourceManager (com.evolsoft.ec.toolbox.GanttChart)" as C_org_eclipse_wb_swt_ResourceManager__dup2
class "SWTResourceManager (com.evolsoft.ec.toolbox.GanttChart)" as C_org_eclipse_wb_swt_SWTResourceManager__dup2

C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow
C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTRow
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTRuler
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup
C_com_evolsoft_ec_toolbox_ganttChart_Sortable <|-- C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl <|-- C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTGroup <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTItem <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTItem <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemProxy
C_com_evolsoft_ec_toolbox_ganttChart_GTMarker <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarkerImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarktableRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTRow <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTRuler <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl
C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartFactory <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartFactoryImpl
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartPackage <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartPackageImpl
C_com_evolsoft_ec_toolbox_ganttChart_GanttChartable <|.. C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartableImpl
C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanntchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer <|.. C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer
C_com_evolsoft_ec_simulator_ColumnLabelProviderEx --> C_com_evolsoft_ec_simulator_SimulatorDataProvider
C_com_evolsoft_ec_simulator_ColumnLabelProviderEx --> C_com_evolsoft_ec_simulator_TextStyleRender
C_com_evolsoft_ec_simulator_SimulatorViewer --> C_com_evolsoft_ec_simulator_SimulatorDataProvider
C_com_evolsoft_ec_simulator_SimulatorViewer --> C_com_evolsoft_ec_simulator_TextStyleRender
C_com_evolsoft_ec_simulator_SimulatorWindow --> C_com_evolsoft_ec_simulator_SimulatorViewer
C_com_evolsoft_ec_simulator_SimulatorWindow --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_simulator_SimulatorWindow --> C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
C_com_evolsoft_ec_simulator_SimulatorWindow --> C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTDetailRowImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTGroupImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTSubGroup
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemProxy --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTItemProxy --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarkerImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTMarktableRow
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTMarkerImpl --> C_com_evolsoft_ec_toolbox_ganttChart_MarkType
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTDetailRow
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRowImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTRulerImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_impl_GTSubGroupImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl --> C_com_evolsoft_ec_toolbox_ganttChart_GTRow
C_com_evolsoft_ec_toolbox_ganttChart_impl_GanttChartModelImpl --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_GTRenderUtils --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupSelectionEventArgs --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_HighlightItemChangedEventArgs --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartModel
C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_must --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_must --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_must --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_GantchartRender
C_com_evolsoft_ec_toolbox_ganttChart_swt_must --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttchartLabelProvider
C_com_evolsoft_ec_toolbox_ganttChart_util_GanttChartAdapterFactory --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartPackage
C_com_evolsoft_ec_toolbox_ganttChart_util_GanttChartSwitch --> C_com_evolsoft_ec_toolbox_ganttChart_GanttChartPackage
C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem --> C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem --> C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanntchartLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_GTItem
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartBuilder --> C_com_evolsoft_ec_toolbox_ganttChart_GTGroup
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartBuilder --> C_com_evolsoft_ec_toolbox_ganttChart_GTRow
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IGanttChartViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartPlugin --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_IScheduleBuilderViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
C_com_evolsoft_ec_toolbox_ganttChart_viewer_GanttChartViewer --> C_com_evolsoft_ec_toolbox_ganttChart_viewer_ChartItem
C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
C_com_evolsoft_ec_toolbox_ganttChart_viewer_ScheduleBuilderViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
@enduml
