@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.eda

class "EDAPlugin" as C_com_evolsoft_ec_eda_EDAPlugin
class "AbstractEDAIndividualService" as C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService
class "ECEDAOptimizator" as C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator
class "EDAStrategy" as C_com_evolsoft_ec_runtime_strategy_EDAStrategy
interface "IEDAOptimizatorDelegate" as C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
interface "IEDAOptimziator" as C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator

C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator <|.. C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator
C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator
C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
@enduml
