@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.toolbox.styles

class "Activator" as C_com_evolsoft_ec_toolbox_styles_Activator
interface "GTStyle" as C_com_evolsoft_ec_toolbox_styles_GTStyle
interface "Literals" as C_com_evolsoft_ec_toolbox_styles_Literals
interface "StyleManager" as C_com_evolsoft_ec_toolbox_styles_StyleManager
interface "StylesFactory" as C_com_evolsoft_ec_toolbox_styles_StylesFactory
interface "StylesPackage" as C_com_evolsoft_ec_toolbox_styles_StylesPackage
class "GTStyleImpl" as C_com_evolsoft_ec_toolbox_styles_impl_GTStyleImpl
class "StyleManagerImpl" as C_com_evolsoft_ec_toolbox_styles_impl_StyleManagerImpl
class "StylesFactoryImpl" as C_com_evolsoft_ec_toolbox_styles_impl_StylesFactoryImpl
class "StylesPackageImpl" as C_com_evolsoft_ec_toolbox_styles_impl_StylesPackageImpl
class "StylesAdapterFactory" as C_com_evolsoft_ec_toolbox_styles_util_StylesAdapterFactory
class "StylesSwitch" as C_com_evolsoft_ec_toolbox_styles_util_StylesSwitch

C_com_evolsoft_ec_toolbox_styles_GTStyle <|.. C_com_evolsoft_ec_toolbox_styles_impl_GTStyleImpl
C_com_evolsoft_ec_toolbox_styles_StyleManager <|.. C_com_evolsoft_ec_toolbox_styles_impl_StyleManagerImpl
C_com_evolsoft_ec_toolbox_styles_StylesFactory <|.. C_com_evolsoft_ec_toolbox_styles_impl_StylesFactoryImpl
C_com_evolsoft_ec_toolbox_styles_StylesPackage <|.. C_com_evolsoft_ec_toolbox_styles_impl_StylesPackageImpl
C_com_evolsoft_ec_toolbox_styles_util_StylesAdapterFactory --> C_com_evolsoft_ec_toolbox_styles_StylesPackage
C_com_evolsoft_ec_toolbox_styles_util_StylesSwitch --> C_com_evolsoft_ec_toolbox_styles_StylesPackage
@enduml
