@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.problem.fjsp2.adapter

class "Activator" as C_com_evolsoft_problem_fjsp2_adapter_Activator
class "BalancingObjective" as C_com_evolsoft_problem_fjsp2_adapter_BalancingObjective
class "FJSP2CSVReader" as C_com_evolsoft_problem_fjsp2_adapter_FJSP2CSVReader
class "FJSP2DataLoader" as C_com_evolsoft_problem_fjsp2_adapter_FJSP2DataLoader
class "FJSP2DataProvider" as C_com_evolsoft_problem_fjsp2_adapter_FJSP2DataProvider
class "FJSP2PlugIn" as C_com_evolsoft_problem_fjsp2_adapter_FJSP2PlugIn
class "FJSPCSVReader" as C_com_evolsoft_problem_fjsp2_adapter_FJSPCSVReader
class "FJSPChartView" as C_com_evolsoft_problem_fjsp2_adapter_FJSPChartView
class "FJSPSolutionChartProvider" as C_com_evolsoft_problem_fjsp2_adapter_FJSPSolutionChartProvider
class "FJSPSolutionXMLConverter" as C_com_evolsoft_problem_fjsp2_adapter_FJSPSolutionXMLConverter
interface "IFJSP2DataProvider" as C_com_evolsoft_problem_fjsp2_adapter_IFJSP2DataProvider
class "MakeSpanObjective" as C_com_evolsoft_problem_fjsp2_adapter_MakeSpanObjective
class "Activator" as C_com_evolsoft_problem_fjsp2_adaptrerBase_Activator
class "FJSP2ScheduleAdapter" as C_com_evolsoft_problem_fjsp2_adaptrerBase_FJSP2ScheduleAdapter
class "AlleleMutation" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_AlleleMutation
class "BroadAssignSearch" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_BroadAssignSearch
class "FJSP2CrossoverBase" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_FJSP2CrossoverBase
interface "FJSP2ECConsant" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_FJSP2ECConsant
class "FJSP2LocalSearch" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_FJSP2LocalSearch
class "FJSP2RDEmigration" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_FJSP2RDEmigration
class "JobBasedInitor" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_JobBasedInitor
class "MixedCrossover" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_MixedCrossover
class "OperationBasedInitor" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_OperationBasedInitor
class "OrderCrossover" as C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_OrderCrossover
enum "ActionType" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_ActionType
class "CPAnalysisAction" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_CPAnalysisAction
class "CPAnalysisWindow" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_CPAnalysisWindow
class "CPEvolutionAction" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_CPEvolutionAction
class "CPEvolutionWindow" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_CPEvolutionWindow
class "CPInspector" as C_com_evolsoft_problem_fjsp2_adaptrerBase_utils_CPInspector

C_com_evolsoft_problem_fjsp2_adapter_IFJSP2DataProvider <|.. C_com_evolsoft_problem_fjsp2_adapter_FJSP2DataProvider
C_com_evolsoft_problem_fjsp2_adaptrerBase_actions_FJSP2LocalSearch --> C_com_evolsoft_problem_fjsp2_adapter_IFJSP2DataProvider
@enduml
