@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.sa

class "Activator" as C_com_evolsoft_ec_sa_Activator
enum "CheckValue" as C_com_evolsoft_ec_sa_algorithm_CheckValue
class "ECDEStrategy" as C_com_evolsoft_ec_sa_algorithm_ECDEStrategy
class "ECSAStrategy" as C_com_evolsoft_ec_sa_algorithm_ECSAStrategy
interface "IDEStrategy" as C_com_evolsoft_ec_sa_algorithm_IDEStrategy
interface "ISAStrategy" as C_com_evolsoft_ec_sa_algorithm_ISAStrategy
interface "ISACFGFactory" as C_com_evolsoft_ec_sa_configuration_ISACFGFactory
interface "ISACFGPackage" as C_com_evolsoft_ec_sa_configuration_ISACFGPackage
interface "ISAConfiguration" as C_com_evolsoft_ec_sa_configuration_ISAConfiguration
interface "ISAConfigurationLoader" as C_com_evolsoft_ec_sa_configuration_ISAConfigurationLoader
interface "Literals" as C_com_evolsoft_ec_sa_configuration_Literals
class "SACFGFactory" as C_com_evolsoft_ec_sa_configuration_impl_SACFGFactory
class "SACFGPackage" as C_com_evolsoft_ec_sa_configuration_impl_SACFGPackage
class "SAConfiguration" as C_com_evolsoft_ec_sa_configuration_impl_SAConfiguration
class "SAConfigurationLoader" as C_com_evolsoft_ec_sa_configuration_impl_SAConfigurationLoader
class "SACFGAdapterFactory" as C_com_evolsoft_ec_sa_configuration_util_SACFGAdapterFactory
class "SACFGSwitch" as C_com_evolsoft_ec_sa_configuration_util_SACFGSwitch
class "SAProfile" as C_com_evolsoft_ec_sa_diagnosis_SAProfile
interface "ISAOptimizator" as C_com_evolsoft_ec_sa_runtime_ISAOptimizator
interface "ISARTFactory" as C_com_evolsoft_ec_sa_runtime_ISARTFactory
interface "ISARTPackage" as C_com_evolsoft_ec_sa_runtime_ISARTPackage
interface "Literals" as C_com_evolsoft_ec_sa_runtime_Literals
class "ECSAOptimizator" as C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizator
class "ECSAOptimizatorCycle" as C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizatorCycle
class "SARTFactory" as C_com_evolsoft_ec_sa_runtime_impl_SARTFactory
class "SARTPackage" as C_com_evolsoft_ec_sa_runtime_impl_SARTPackage
class "SARTAdapterFactory" as C_com_evolsoft_ec_sa_runtime_util_SARTAdapterFactory
class "SARTSwitch" as C_com_evolsoft_ec_sa_runtime_util_SARTSwitch

C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizator <|-- C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizatorCycle
C_com_evolsoft_ec_sa_algorithm_IDEStrategy <|.. C_com_evolsoft_ec_sa_algorithm_ECDEStrategy
C_com_evolsoft_ec_sa_algorithm_ISAStrategy <|.. C_com_evolsoft_ec_sa_algorithm_ECSAStrategy
C_com_evolsoft_ec_sa_configuration_ISACFGFactory <|.. C_com_evolsoft_ec_sa_configuration_impl_SACFGFactory
C_com_evolsoft_ec_sa_configuration_ISACFGPackage <|.. C_com_evolsoft_ec_sa_configuration_impl_SACFGPackage
C_com_evolsoft_ec_sa_configuration_ISAConfiguration <|.. C_com_evolsoft_ec_sa_configuration_impl_SAConfiguration
C_com_evolsoft_ec_sa_configuration_ISAConfigurationLoader <|.. C_com_evolsoft_ec_sa_configuration_impl_SAConfigurationLoader
C_com_evolsoft_ec_sa_runtime_ISAOptimizator <|.. C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizator
C_com_evolsoft_ec_sa_runtime_ISARTFactory <|.. C_com_evolsoft_ec_sa_runtime_impl_SARTFactory
C_com_evolsoft_ec_sa_runtime_ISARTPackage <|.. C_com_evolsoft_ec_sa_runtime_impl_SARTPackage
C_com_evolsoft_ec_sa_algorithm_ECDEStrategy --> C_com_evolsoft_ec_sa_runtime_ISAOptimizator
C_com_evolsoft_ec_sa_algorithm_ECSAStrategy --> C_com_evolsoft_ec_sa_runtime_ISAOptimizator
C_com_evolsoft_ec_sa_configuration_util_SACFGAdapterFactory --> C_com_evolsoft_ec_sa_configuration_ISACFGPackage
C_com_evolsoft_ec_sa_configuration_util_SACFGSwitch --> C_com_evolsoft_ec_sa_configuration_ISACFGPackage
C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizator --> C_com_evolsoft_ec_sa_algorithm_ISAStrategy
C_com_evolsoft_ec_sa_runtime_impl_ECSAOptimizator --> C_com_evolsoft_ec_sa_configuration_ISAConfiguration
C_com_evolsoft_ec_sa_runtime_util_SARTAdapterFactory --> C_com_evolsoft_ec_sa_runtime_ISARTPackage
C_com_evolsoft_ec_sa_runtime_util_SARTSwitch --> C_com_evolsoft_ec_sa_runtime_ISARTPackage
@enduml
