@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.ec.chart

class "AbstractFreeChartView" as C_com_evolsoft_ec_chart_AbstractFreeChartView
class "Activator" as C_com_evolsoft_ec_chart_Activator
class "ECMonitorPlugin" as C_com_evolsoft_ec_chart_ECMonitorPlugin
class "FitnessMonitorView" as C_com_evolsoft_ec_chart_FitnessMonitorView
interface "IChartView" as C_com_evolsoft_ec_chart_IChartView
interface "IGenSeriesDataProvider" as C_com_evolsoft_ec_chart_IGenSeriesDataProvider
class "ObjectiveMonitorView" as C_com_evolsoft_ec_chart_ObjectiveMonitorView
class "ParetoView" as C_com_evolsoft_ec_chart_ParetoView
class "TimeSeriesDataView" as C_com_evolsoft_ec_chart_TimeSeriesDataView
interface "IMonitorItem" as C_com_evolsoft_ec_chart_data_IMonitorItem
interface "IXYSeries" as C_com_evolsoft_ec_chart_data_IXYSeries
class "MonitorItem" as C_com_evolsoft_ec_chart_data_MonitorItem
class "MonitorItemManager" as C_com_evolsoft_ec_chart_data_MonitorItemManager
class "XYSeries" as C_com_evolsoft_ec_chart_data_XYSeries
class "GantChartLabelGenerator" as C_com_evolsoft_ec_chart_ganttchart_GantChartLabelGenerator
interface "ITaskEx" as C_com_evolsoft_ec_chart_ganttchart_ITaskEx
interface "ITaskSerisEx" as C_com_evolsoft_ec_chart_ganttchart_ITaskSerisEx
class "MyGanttRenderer" as C_com_evolsoft_ec_chart_ganttchart_MyGanttRenderer
class "ResearchRelativeDateFormat" as C_com_evolsoft_ec_chart_ganttchart_ResearchRelativeDateFormat
class "TaskEx" as C_com_evolsoft_ec_chart_ganttchart_TaskEx
class "TaskSerisEx" as C_com_evolsoft_ec_chart_ganttchart_TaskSerisEx
interface "IParetoListener" as C_com_evolsoft_ec_chart_pareto_IParetoListener
class "ParetoEntry" as C_com_evolsoft_ec_chart_pareto_ParetoEntry
class "ParetoXYDataSet" as C_com_evolsoft_ec_chart_pareto_ParetoXYDataSet
class "FreeChartFactory" as C_com_evolsoft_ec_chart_support_FreeChartFactory

C_com_evolsoft_ec_chart_TimeSeriesDataView <|-- C_com_evolsoft_ec_chart_FitnessMonitorView
C_com_evolsoft_ec_chart_TimeSeriesDataView <|-- C_com_evolsoft_ec_chart_ObjectiveMonitorView
C_com_evolsoft_ec_chart_TimeSeriesDataView <|-- C_com_evolsoft_ec_chart_ParetoView
C_com_evolsoft_ec_chart_AbstractFreeChartView <|-- C_com_evolsoft_ec_chart_TimeSeriesDataView
C_com_evolsoft_ec_chart_data_IXYSeries <|.. C_com_evolsoft_ec_chart_data_XYSeries
C_com_evolsoft_ec_chart_ganttchart_ITaskEx <|.. C_com_evolsoft_ec_chart_ganttchart_TaskEx
C_com_evolsoft_ec_chart_ganttchart_ITaskSerisEx <|.. C_com_evolsoft_ec_chart_ganttchart_TaskSerisEx
C_com_evolsoft_ec_chart_pareto_IParetoListener <|.. C_com_evolsoft_ec_chart_pareto_ParetoXYDataSet
C_com_evolsoft_ec_chart_TimeSeriesDataView --> C_com_evolsoft_ec_chart_data_MonitorItemManager
C_com_evolsoft_ec_chart_TimeSeriesDataView --> C_com_evolsoft_ec_chart_data_XYSeries
C_com_evolsoft_ec_chart_data_MonitorItem --> C_com_evolsoft_ec_chart_data_XYSeries
C_com_evolsoft_ec_chart_ganttchart_TaskEx --> C_com_evolsoft_ec_chart_ganttchart_ITaskSerisEx
C_com_evolsoft_ec_chart_pareto_ParetoXYDataSet --> C_com_evolsoft_ec_chart_pareto_ParetoEntry
@enduml
