@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.bayesian

class "Activator" as C_com_evolsoft_bayesian_Activator
class "BayNode" as C_com_evolsoft_bayesian_BayNode
class "BayesianNetwork" as C_com_evolsoft_bayesian_BayesianNetwork
interface "Constants" as C_com_evolsoft_bayesian_Constants
class "DefaultSamplingMood" as C_com_evolsoft_bayesian_DefaultSamplingMood
class "EdgeTransProbabilityTable" as C_com_evolsoft_bayesian_EdgeTransProbabilityTable
interface "IBayNodeKey" as C_com_evolsoft_bayesian_IBayNodeKey
interface "IBayesianNetworkSetting" as C_com_evolsoft_bayesian_IBayesianNetworkSetting
interface "IIdentifyDomain" as C_com_evolsoft_bayesian_IIdentifyDomain
interface "IProbabilityCube" as C_com_evolsoft_bayesian_IProbabilityCube
interface "IProbabilityTable" as C_com_evolsoft_bayesian_IProbabilityTable
interface "ISamplingMood" as C_com_evolsoft_bayesian_ISamplingMood
interface "ITournament" as C_com_evolsoft_bayesian_ITournament
class "IdentifyDomain" as C_com_evolsoft_bayesian_IdentifyDomain
class "IllegalNodeException" as C_com_evolsoft_bayesian_IllegalNodeException
class "IllegalVariablesDimension" as C_com_evolsoft_bayesian_IllegalVariablesDimension
class "InvalidPTableException" as C_com_evolsoft_bayesian_InvalidPTableException
class "ProbabilityCube" as C_com_evolsoft_bayesian_ProbabilityCube
class "ProbabilityCubeEx" as C_com_evolsoft_bayesian_ProbabilityCubeEx
class "ProbabilityTable" as C_com_evolsoft_bayesian_ProbabilityTable
class "ProbabilityTableEx" as C_com_evolsoft_bayesian_ProbabilityTableEx
interface "ITransferFunction" as C_com_evolsoft_bayesian_cost_ITransferFunction
interface "ITransferStrategy" as C_com_evolsoft_bayesian_cost_ITransferStrategy
enum "ProbabilityMode" as C_com_evolsoft_bayesian_cost_ProbabilityMode
class "TransferFunction" as C_com_evolsoft_bayesian_cost_TransferFunction
class "TransferStrategy" as C_com_evolsoft_bayesian_cost_TransferStrategy

C_com_evolsoft_bayesian_ITournament <|-- C_com_evolsoft_bayesian_IBayesianNetworkSetting
C_com_evolsoft_bayesian_ISamplingMood <|.. C_com_evolsoft_bayesian_DefaultSamplingMood
C_com_evolsoft_bayesian_IIdentifyDomain <|.. C_com_evolsoft_bayesian_IdentifyDomain
C_com_evolsoft_bayesian_IProbabilityCube <|.. C_com_evolsoft_bayesian_ProbabilityCubeEx
C_com_evolsoft_bayesian_IProbabilityTable <|.. C_com_evolsoft_bayesian_ProbabilityTableEx
C_com_evolsoft_bayesian_cost_ITransferFunction <|.. C_com_evolsoft_bayesian_cost_TransferFunction
C_com_evolsoft_bayesian_cost_ITransferStrategy <|.. C_com_evolsoft_bayesian_cost_TransferStrategy
C_com_evolsoft_bayesian_BayNode --> C_com_evolsoft_bayesian_BayesianNetwork
C_com_evolsoft_bayesian_BayNode --> C_com_evolsoft_bayesian_EdgeTransProbabilityTable
C_com_evolsoft_bayesian_BayNode --> C_com_evolsoft_bayesian_IProbabilityCube
C_com_evolsoft_bayesian_BayNode --> C_com_evolsoft_bayesian_IdentifyDomain
C_com_evolsoft_bayesian_BayesianNetwork --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_BayesianNetwork --> C_com_evolsoft_bayesian_IBayesianNetworkSetting
C_com_evolsoft_bayesian_BayesianNetwork --> C_com_evolsoft_bayesian_ISamplingMood
C_com_evolsoft_bayesian_BayesianNetwork --> C_com_evolsoft_bayesian_cost_ITransferFunction
C_com_evolsoft_bayesian_EdgeTransProbabilityTable --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_ProbabilityCube --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_ProbabilityCube --> C_com_evolsoft_bayesian_ProbabilityTable
C_com_evolsoft_bayesian_ProbabilityCubeEx --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_ProbabilityCubeEx --> C_com_evolsoft_bayesian_ProbabilityTableEx
C_com_evolsoft_bayesian_ProbabilityTable --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_ProbabilityTable --> C_com_evolsoft_bayesian_IBayesianNetworkSetting
C_com_evolsoft_bayesian_ProbabilityTable --> C_com_evolsoft_bayesian_ISamplingMood
C_com_evolsoft_bayesian_ProbabilityTableEx --> C_com_evolsoft_bayesian_BayNode
C_com_evolsoft_bayesian_ProbabilityTableEx --> C_com_evolsoft_bayesian_IBayesianNetworkSetting
C_com_evolsoft_bayesian_ProbabilityTableEx --> C_com_evolsoft_bayesian_ISamplingMood
C_com_evolsoft_bayesian_ProbabilityTableEx --> C_com_evolsoft_bayesian_cost_ITransferFunction
C_com_evolsoft_bayesian_cost_TransferFunction --> C_com_evolsoft_bayesian_cost_ProbabilityMode
C_com_evolsoft_bayesian_cost_TransferStrategy --> C_com_evolsoft_bayesian_cost_ITransferFunction
@enduml
