@startuml
left to right direction
skinparam classAttributeIconSize 0
title Module: com.evolsoft.problem.fjsp2.individualService

class "AbstractFJSPKnowledgeBaseIndividaulService" as C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPKnowledgeBaseIndividaulService
class "AbstractFJSPUDMAIndividualService" as C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPUDMAIndividualService
class "Activator" as C_com_evolsoft_problem_fjsp2_individualservice_Activator
class "CPMLocalSearcher" as C_com_evolsoft_problem_fjsp2_individualservice_CPMLocalSearcher
class "FJSP2JobSGAIndividualService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSP2JobSGAIndividualService
class "FJSPEDAdIndividualService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPEDAdIndividualService
class "FJSPGreedyEDAIndividualService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPGreedyEDAIndividualService
class "FJSPIndividualServiceBase" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPIndividualServiceBase
class "FJSPMarkovBasedIndividualService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPMarkovBasedIndividualService
class "FJSPPrioirtyBasedIndividaulService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPPrioirtyBasedIndividaulService
class "FJSPUDMAJobBasedIService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPUDMAJobBasedIService
class "FJSPUDMAOperationBasedIService" as C_com_evolsoft_problem_fjsp2_individualservice_FJSPUDMAOperationBasedIService
class "PriorityBasedSimModelBuilder" as C_com_evolsoft_problem_fjsp2_individualservice_PriorityBasedSimModelBuilder
class "MachineMutation" as C_com_evolsoft_problem_fjsp2_individualservice_actions_MachineMutation
class "PrioritySwapMutation" as C_com_evolsoft_problem_fjsp2_individualservice_actions_PrioritySwapMutation
class "FJSPShowOptimalIndivdiualService" as C_com_evolsoft_problem_fjsp2_individualservice_optimal_FJSPShowOptimalIndivdiualService
class "MK01DebugData" as C_com_evolsoft_problem_fjsp2_individualservice_optimal_MK01DebugData
class "OptimalSolution" as C_com_evolsoft_problem_fjsp2_individualservice_optimal_OptimalSolution
class "OptimalSolutionHao" as C_com_evolsoft_problem_fjsp2_individualservice_optimal_OptimalSolutionHao

C_com_evolsoft_problem_fjsp2_individualservice_FJSPIndividualServiceBase <|-- C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPKnowledgeBaseIndividaulService
C_com_evolsoft_problem_fjsp2_individualservice_FJSPEDAdIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPUDMAIndividualService
C_com_evolsoft_problem_fjsp2_individualservice_FJSPEDAdIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_FJSPGreedyEDAIndividualService
C_com_evolsoft_problem_fjsp2_individualservice_FJSPEDAdIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_FJSPMarkovBasedIndividualService
C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPKnowledgeBaseIndividaulService <|-- C_com_evolsoft_problem_fjsp2_individualservice_FJSPPrioirtyBasedIndividaulService
C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPUDMAIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_FJSPUDMAJobBasedIService
C_com_evolsoft_problem_fjsp2_individualservice_AbstractFJSPUDMAIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_FJSPUDMAOperationBasedIService
C_com_evolsoft_problem_fjsp2_individualservice_FJSPEDAdIndividualService <|-- C_com_evolsoft_problem_fjsp2_individualservice_optimal_FJSPShowOptimalIndivdiualService
@enduml
