@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.probability1

interface "IMutualInfoMatrix" as C_com_evolsoft_ec_toolbox_probability1_IMutualInfoMatrix
interface "IProbabilityMatrix" as C_com_evolsoft_ec_toolbox_probability1_IProbabilityMatrix
interface "IProbabilityState" as C_com_evolsoft_ec_toolbox_probability1_IProbabilityState
class "ProbabilityHeader" as C_com_evolsoft_ec_toolbox_probability1_ProbabilityHeader
class "ProbabilityItem" as C_com_evolsoft_ec_toolbox_probability1_ProbabilityItem
class "ProbabilityMatrix" as C_com_evolsoft_ec_toolbox_probability1_ProbabilityMatrix
class "ProbabilityVector" as C_com_evolsoft_ec_toolbox_probability1_ProbabilityVector
class "ProbabilityVectors" as C_com_evolsoft_ec_toolbox_probability1_ProbabilityVectors
class "ProbalityMatrixArray" as C_com_evolsoft_ec_toolbox_probability1_ProbalityMatrixArray

C_com_evolsoft_ec_toolbox_probability1_ProbabilityItem <|-- C_com_evolsoft_ec_toolbox_probability1_ProbabilityHeader
C_com_evolsoft_ec_toolbox_probability1_IProbabilityMatrix <|.. C_com_evolsoft_ec_toolbox_probability1_ProbabilityMatrix
C_com_evolsoft_ec_toolbox_probability1_IProbabilityState <|.. C_com_evolsoft_ec_toolbox_probability1_ProbabilityVector
C_com_evolsoft_ec_toolbox_probability1_IProbabilityMatrix <|.. C_com_evolsoft_ec_toolbox_probability1_ProbabilityVectors
C_com_evolsoft_ec_toolbox_probability1_ProbabilityMatrix --> C_com_evolsoft_ec_toolbox_probability1_ProbabilityHeader
C_com_evolsoft_ec_toolbox_probability1_ProbabilityMatrix --> C_com_evolsoft_ec_toolbox_probability1_ProbabilityItem
C_com_evolsoft_ec_toolbox_probability1_ProbabilityVector --> C_com_evolsoft_ec_toolbox_probability1_ProbabilityHeader
C_com_evolsoft_ec_toolbox_probability1_ProbabilityVector --> C_com_evolsoft_ec_toolbox_probability1_ProbabilityItem
C_com_evolsoft_ec_toolbox_probability1_ProbabilityVectors --> C_com_evolsoft_ec_toolbox_probability1_ProbabilityVector
@enduml
