@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.variables

class "AbstractVaraible" as C_com_evolsoft_core_runtime_variables_AbstractVaraible
class "BooleanVariable" as C_com_evolsoft_core_runtime_variables_BooleanVariable
class "DateTimeVariable" as C_com_evolsoft_core_runtime_variables_DateTimeVariable
interface "IVariable" as C_com_evolsoft_core_runtime_variables_IVariable
interface "IVariableChangedEventListener" as C_com_evolsoft_core_runtime_variables_IVariableChangedEventListener
interface "IVariableDomain" as C_com_evolsoft_core_runtime_variables_IVariableDomain
interface "IVariables" as C_com_evolsoft_core_runtime_variables_IVariables
class "IllegalValueException" as C_com_evolsoft_core_runtime_variables_IllegalValueException
class "NumberVaraible" as C_com_evolsoft_core_runtime_variables_NumberVaraible
class "ObjectVaraible" as C_com_evolsoft_core_runtime_variables_ObjectVaraible
class "StringVariable" as C_com_evolsoft_core_runtime_variables_StringVariable
class "VariableAdvisor" as C_com_evolsoft_core_runtime_variables_VariableAdvisor
class "VariableChangedEvent" as C_com_evolsoft_core_runtime_variables_VariableChangedEvent
class "VariableDomainBase" as C_com_evolsoft_core_runtime_variables_VariableDomainBase
class "VariableNotDefinedException" as C_com_evolsoft_core_runtime_variables_VariableNotDefinedException
class "VariableUtils" as C_com_evolsoft_core_runtime_variables_VariableUtils
class "Variables" as C_com_evolsoft_core_runtime_variables_Variables

C_com_evolsoft_core_runtime_variables_AbstractVaraible <|-- C_com_evolsoft_core_runtime_variables_BooleanVariable
C_com_evolsoft_core_runtime_variables_AbstractVaraible <|-- C_com_evolsoft_core_runtime_variables_DateTimeVariable
C_com_evolsoft_core_runtime_variables_AbstractVaraible <|-- C_com_evolsoft_core_runtime_variables_NumberVaraible
C_com_evolsoft_core_runtime_variables_AbstractVaraible <|-- C_com_evolsoft_core_runtime_variables_ObjectVaraible
C_com_evolsoft_core_runtime_variables_AbstractVaraible <|-- C_com_evolsoft_core_runtime_variables_StringVariable
C_com_evolsoft_core_runtime_variables_IVariable <|.. C_com_evolsoft_core_runtime_variables_AbstractVaraible
C_com_evolsoft_core_runtime_variables_IVariableDomain <|.. C_com_evolsoft_core_runtime_variables_VariableDomainBase
C_com_evolsoft_core_runtime_variables_IVariables <|.. C_com_evolsoft_core_runtime_variables_Variables
C_com_evolsoft_core_runtime_variables_AbstractVaraible --> C_com_evolsoft_core_runtime_variables_IVariables
C_com_evolsoft_core_runtime_variables_VariableAdvisor --> C_com_evolsoft_core_runtime_variables_IVariables
C_com_evolsoft_core_runtime_variables_VariableChangedEvent --> C_com_evolsoft_core_runtime_variables_IVariable
@enduml
