@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.population

class "CopyOfGeneration" as C_com_evolsoft_ec_runtime_population_CopyOfGeneration
class "DecodeServiceNotSupported" as C_com_evolsoft_ec_runtime_population_DecodeServiceNotSupported
class "Generation" as C_com_evolsoft_ec_runtime_population_Generation
class "GenerationAddArgs" as C_com_evolsoft_ec_runtime_population_GenerationAddArgs
class "GenerationChangedEventHub" as C_com_evolsoft_ec_runtime_population_GenerationChangedEventHub
class "GenerationFactory" as C_com_evolsoft_ec_runtime_population_GenerationFactory
class "GenerationInitializedException" as C_com_evolsoft_ec_runtime_population_GenerationInitializedException
interface "ICheckinDelegate" as C_com_evolsoft_ec_runtime_population_ICheckinDelegate
interface "ICheckoutDelegate" as C_com_evolsoft_ec_runtime_population_ICheckoutDelegate
interface "IGenSelector" as C_com_evolsoft_ec_runtime_population_IGenSelector
interface "IGeneration" as C_com_evolsoft_ec_runtime_population_IGeneration
interface "IGenerationChangedDelegate" as C_com_evolsoft_ec_runtime_population_IGenerationChangedDelegate
interface "IIndividualContainer" as C_com_evolsoft_ec_runtime_population_IIndividualContainer
interface "IOffsprings" as C_com_evolsoft_ec_runtime_population_IOffsprings
interface "IPopulation" as C_com_evolsoft_ec_runtime_population_IPopulation
interface "IPopulationArchive" as C_com_evolsoft_ec_runtime_population_IPopulationArchive
interface "IPopulationContext" as C_com_evolsoft_ec_runtime_population_IPopulationContext
interface "IPopulationPolicy" as C_com_evolsoft_ec_runtime_population_IPopulationPolicy
interface "IVersionable" as C_com_evolsoft_ec_runtime_population_IVersionable
class "IndividualContainer" as C_com_evolsoft_ec_runtime_population_IndividualContainer
class "MatingPool" as C_com_evolsoft_ec_runtime_population_MatingPool
class "Offsprings" as C_com_evolsoft_ec_runtime_population_Offsprings
class "Population" as C_com_evolsoft_ec_runtime_population_Population
class "PopulationAdvisor" as C_com_evolsoft_ec_runtime_population_PopulationAdvisor
class "PopulationArchive" as C_com_evolsoft_ec_runtime_population_PopulationArchive
class "PopulationContext" as C_com_evolsoft_ec_runtime_population_PopulationContext
class "PopulationPolicy" as C_com_evolsoft_ec_runtime_population_PopulationPolicy
class "Populationbase" as C_com_evolsoft_ec_runtime_population_Populationbase
class "SectionChromosomeVistor" as C_com_evolsoft_ec_runtime_population_SectionChromosomeVistor

C_com_evolsoft_ec_runtime_population_IIndividualContainer <|-- C_com_evolsoft_ec_runtime_population_IOffsprings
C_com_evolsoft_ec_runtime_population_IndividualContainer <|-- C_com_evolsoft_ec_runtime_population_Offsprings
C_com_evolsoft_ec_runtime_population_Populationbase <|-- C_com_evolsoft_ec_runtime_population_Population
C_com_evolsoft_ec_runtime_population_IGeneration <|.. C_com_evolsoft_ec_runtime_population_CopyOfGeneration
C_com_evolsoft_ec_runtime_population_IGeneration <|.. C_com_evolsoft_ec_runtime_population_Generation
C_com_evolsoft_ec_runtime_population_IGenerationChangedDelegate <|.. C_com_evolsoft_ec_runtime_population_GenerationChangedEventHub
C_com_evolsoft_ec_runtime_population_IIndividualContainer <|.. C_com_evolsoft_ec_runtime_population_IndividualContainer
C_com_evolsoft_ec_runtime_population_IOffsprings <|.. C_com_evolsoft_ec_runtime_population_Offsprings
C_com_evolsoft_ec_runtime_population_IVersionable <|.. C_com_evolsoft_ec_runtime_population_Population
C_com_evolsoft_ec_runtime_population_IPopulationArchive <|.. C_com_evolsoft_ec_runtime_population_PopulationArchive
C_com_evolsoft_ec_runtime_population_IPopulationContext <|.. C_com_evolsoft_ec_runtime_population_PopulationContext
C_com_evolsoft_ec_runtime_population_IPopulationPolicy <|.. C_com_evolsoft_ec_runtime_population_PopulationPolicy
C_com_evolsoft_ec_runtime_population_IPopulation <|.. C_com_evolsoft_ec_runtime_population_Populationbase
C_com_evolsoft_ec_runtime_population_CopyOfGeneration --> C_com_evolsoft_ec_runtime_population_IPopulation
C_com_evolsoft_ec_runtime_population_Generation --> C_com_evolsoft_ec_runtime_population_IPopulation
C_com_evolsoft_ec_runtime_population_PopulationAdvisor --> C_com_evolsoft_ec_runtime_population_PopulationContext
C_com_evolsoft_ec_runtime_population_PopulationContext --> C_com_evolsoft_ec_runtime_population_GenerationFactory
C_com_evolsoft_ec_runtime_population_PopulationContext --> C_com_evolsoft_ec_runtime_population_IPopulation
C_com_evolsoft_ec_runtime_population_PopulationContext --> C_com_evolsoft_ec_runtime_population_IPopulationPolicy
C_com_evolsoft_ec_runtime_population_Populationbase --> C_com_evolsoft_ec_runtime_population_IGeneration
C_com_evolsoft_ec_runtime_population_Populationbase --> C_com_evolsoft_ec_runtime_population_IGenerationChangedDelegate
C_com_evolsoft_ec_runtime_population_Populationbase --> C_com_evolsoft_ec_runtime_population_IOffsprings
C_com_evolsoft_ec_runtime_population_Populationbase --> C_com_evolsoft_ec_runtime_population_IPopulationArchive
C_com_evolsoft_ec_runtime_population_Populationbase --> C_com_evolsoft_ec_runtime_population_IPopulationContext
@enduml
