@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.listgenetype.initor

class "GeneDomainInfo" as C_com_evolsoft_ec_runtime_listgenetype_initor_GeneDomainInfo
interface "IGroupSectionInitor" as C_com_evolsoft_ec_runtime_listgenetype_initor_IGroupSectionInitor
interface "ISectionGeneValueInitor" as C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionGeneValueInitor
interface "ISectionInitor" as C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionInitor
class "NotSupportableException" as C_com_evolsoft_ec_runtime_listgenetype_initor_NotSupportableException
class "SectionInitorBase" as C_com_evolsoft_ec_runtime_listgenetype_initor_SectionInitorBase
class "SectionNumberInitorBase" as C_com_evolsoft_ec_runtime_listgenetype_initor_SectionNumberInitorBase

C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionInitor <|-- C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionGeneValueInitor
C_com_evolsoft_ec_runtime_listgenetype_initor_SectionInitorBase <|-- C_com_evolsoft_ec_runtime_listgenetype_initor_SectionNumberInitorBase
C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionInitor <|.. C_com_evolsoft_ec_runtime_listgenetype_initor_SectionInitorBase
C_com_evolsoft_ec_runtime_listgenetype_initor_ISectionGeneValueInitor <|.. C_com_evolsoft_ec_runtime_listgenetype_initor_SectionNumberInitorBase
@enduml
