@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.page.control

class "ObjectiveViewSection" as C_com_evolsoft_ec_ui_page_control_ObjectiveViewSection

@enduml
