@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.problem.rcpsp.model

interface "ActivityConfiguration" as C_com_evolsoft_ec_problem_rcpsp_model_ActivityConfiguration
class "ActivityConfigurationImpl" as C_com_evolsoft_ec_problem_rcpsp_model_ActivityConfigurationImpl
class "ActivityResourceManager" as C_com_evolsoft_ec_problem_rcpsp_model_ActivityResourceManager
interface "IRCPSPActivityDecision" as C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPActivityDecision
interface "IRCPSPDataProvider" as C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPDataProvider
interface "IRCPSPModel" as C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPModel
interface "IRCPSPScheudling" as C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPScheudling
class "RCPSPDataProvider" as C_com_evolsoft_ec_problem_rcpsp_model_RCPSPDataProvider
class "RCPSPModel" as C_com_evolsoft_ec_problem_rcpsp_model_RCPSPModel
class "RCPSPScheudlingAdapter" as C_com_evolsoft_ec_problem_rcpsp_model_RCPSPScheudlingAdapter
class "RCPSPSolutionXMLConverter" as C_com_evolsoft_ec_problem_rcpsp_model_RCPSPSolutionXMLConverter

C_com_evolsoft_ec_problem_rcpsp_model_ActivityConfiguration <|.. C_com_evolsoft_ec_problem_rcpsp_model_ActivityConfigurationImpl
C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPDataProvider <|.. C_com_evolsoft_ec_problem_rcpsp_model_RCPSPDataProvider
C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPModel <|.. C_com_evolsoft_ec_problem_rcpsp_model_RCPSPModel
C_com_evolsoft_ec_problem_rcpsp_model_RCPSPScheudlingAdapter --> C_com_evolsoft_ec_problem_rcpsp_model_IRCPSPModel
@enduml
