@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.wizards.provider

class "ECTemplateContentProvider" as C_com_evolsoft_ec_ui_wizards_provider_ECTemplateContentProvider
class "ECTemplateLabelProvider" as C_com_evolsoft_ec_ui_wizards_provider_ECTemplateLabelProvider
class "SolutionCategoryItem" as C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
class "SolutionTemplateItem" as C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem

C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem <|-- C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
C_com_evolsoft_ec_ui_wizards_provider_ECTemplateContentProvider --> C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
C_com_evolsoft_ec_ui_wizards_provider_SolutionTemplateItem --> C_com_evolsoft_ec_ui_wizards_provider_SolutionCategoryItem
@enduml
