@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.pbil.matrixModel

class "PBMatrixModelRoot" as C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot
class "PBMatrixTraceModel" as C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
class "PBProbabilityCDFList" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
class "PBProbabilityCDFVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector
class "PBProbabilityPMFList" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
class "PBProbabilityPMFVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
class "PBProbabilityVector" as C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector

C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector <|-- C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityVector <|-- C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixModelRoot --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFVector --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityCDFList
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList --> C_com_evolsoft_ec_pbil_matrixModel_PBMatrixTraceModel
C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFVector --> C_com_evolsoft_ec_pbil_matrixModel_PBProbabilityPMFList
@enduml
