@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.problem

interface "IObjectiveFunctionDescriptor" as C_com_evolsoft_core_configuration_problem_IObjectiveFunctionDescriptor
interface "IObjectiveFunctionDescriptorSpec" as C_com_evolsoft_core_configuration_problem_IObjectiveFunctionDescriptorSpec
interface "IObjectiveReferenceDescriptor" as C_com_evolsoft_core_configuration_problem_IObjectiveReferenceDescriptor
interface "IObjectiveReferenceDescriptorSpec" as C_com_evolsoft_core_configuration_problem_IObjectiveReferenceDescriptorSpec
interface "IProblemDescriptorSpec" as C_com_evolsoft_core_configuration_problem_IProblemDescriptorSpec
interface "IProblemReferenceDescriptor" as C_com_evolsoft_core_configuration_problem_IProblemReferenceDescriptor
class "ObjectiveDefService" as C_com_evolsoft_core_configuration_problem_ObjectiveDefService
class "ObjectiveFunctionDescriptor" as C_com_evolsoft_core_configuration_problem_ObjectiveFunctionDescriptor
class "ObjectiveReferenceDescriptor" as C_com_evolsoft_core_configuration_problem_ObjectiveReferenceDescriptor
class "ProblemDescriptor" as C_com_evolsoft_core_configuration_problem_ProblemDescriptor
class "ProblemObjectiveFunctionDescriptor" as C_com_evolsoft_core_configuration_problem_ProblemObjectiveFunctionDescriptor
class "ProblemReferenceDescriptor" as C_com_evolsoft_core_configuration_problem_ProblemReferenceDescriptor

C_com_evolsoft_core_configuration_problem_IObjectiveFunctionDescriptor <|.. C_com_evolsoft_core_configuration_problem_ObjectiveFunctionDescriptor
C_com_evolsoft_core_configuration_problem_IObjectiveReferenceDescriptor <|.. C_com_evolsoft_core_configuration_problem_ObjectiveReferenceDescriptor
C_com_evolsoft_core_configuration_problem_IProblemReferenceDescriptor <|.. C_com_evolsoft_core_configuration_problem_ProblemReferenceDescriptor
C_com_evolsoft_core_configuration_problem_ObjectiveReferenceDescriptor --> C_com_evolsoft_core_configuration_problem_IObjectiveFunctionDescriptor
C_com_evolsoft_core_configuration_problem_ProblemObjectiveFunctionDescriptor --> C_com_evolsoft_core_configuration_problem_IObjectiveFunctionDescriptor
@enduml
