@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.probability

class "BiMapJointProbabilityStateMatrix" as C_com_evolsoft_ec_toolbox_probability_BiMapJointProbabilityStateMatrix
class "BiVectorJointProbabilityStateMatrix" as C_com_evolsoft_ec_toolbox_probability_BiVectorJointProbabilityStateMatrix
class "IDSorter" as C_com_evolsoft_ec_toolbox_probability_IDSorter
class "IDSorter (com.evolsoft.ec.toolbox.mrf)" as C_com_evolsoft_ec_toolbox_probability_IDSorter__dup2
interface "IProbabilityState" as C_com_evolsoft_ec_toolbox_probability_IProbabilityState
interface "IPromisingDataSet" as C_com_evolsoft_ec_toolbox_probability_IPromisingDataSet
interface "IValueAccessor" as C_com_evolsoft_ec_toolbox_probability_IValueAccessor
class "IllegalDomainException" as C_com_evolsoft_ec_toolbox_probability_IllegalDomainException
class "MapJointProbabilityState" as C_com_evolsoft_ec_toolbox_probability_MapJointProbabilityState
class "MutualInforMatrix" as C_com_evolsoft_ec_toolbox_probability_MutualInforMatrix
class "NeightbourSorter" as C_com_evolsoft_ec_toolbox_probability_NeightbourSorter
class "ProbabilityState" as C_com_evolsoft_ec_toolbox_probability_ProbabilityState
class "VectorJointProbabilityState" as C_com_evolsoft_ec_toolbox_probability_VectorJointProbabilityState

C_com_evolsoft_ec_toolbox_probability_IProbabilityState <|.. C_com_evolsoft_ec_toolbox_probability_ProbabilityState
C_com_evolsoft_ec_toolbox_probability_BiMapJointProbabilityStateMatrix --> C_com_evolsoft_ec_toolbox_probability_MapJointProbabilityState
C_com_evolsoft_ec_toolbox_probability_BiMapJointProbabilityStateMatrix --> C_com_evolsoft_ec_toolbox_probability_ProbabilityState
C_com_evolsoft_ec_toolbox_probability_BiVectorJointProbabilityStateMatrix --> C_com_evolsoft_ec_toolbox_probability_NeightbourSorter
C_com_evolsoft_ec_toolbox_probability_BiVectorJointProbabilityStateMatrix --> C_com_evolsoft_ec_toolbox_probability_ProbabilityState
C_com_evolsoft_ec_toolbox_probability_BiVectorJointProbabilityStateMatrix --> C_com_evolsoft_ec_toolbox_probability_VectorJointProbabilityState
C_com_evolsoft_ec_toolbox_probability_NeightbourSorter --> C_com_evolsoft_ec_toolbox_probability_ProbabilityState
C_com_evolsoft_ec_toolbox_probability_NeightbourSorter --> C_com_evolsoft_ec_toolbox_probability_VectorJointProbabilityState
@enduml
