@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.monitorEditor.lableProvider

class "AgeColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_AgeColumnLabelProvider
class "BenchmarkContentProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkContentProvider
class "BenchmarkLabelViewProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_BenchmarkLabelViewProvider
class "ECAppContentProviderBase" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppContentProviderBase
class "ECAppPartitionContentProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
class "FitnessColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_FitnessColumnLabelProvider
class "GeneValueColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_GeneValueColumnLabelProvider
class "ObjectiveColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ObjectiveColumnLabelProvider
class "SequenceColumnLabelProvider" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_SequenceColumnLabelProvider
enum "SortItemType" as C_com_evolsoft_ec_ui_monitorEditor_lableProvider_SortItemType

C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppContentProviderBase <|-- C_com_evolsoft_ec_ui_monitorEditor_lableProvider_ECAppPartitionContentProvider
@enduml
