@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.notation.figure.tree

class "AnimatingLayer" as C_com_evolsoft_ec_toolbox_notation_figure_tree_AnimatingLayer
class "Animation" as C_com_evolsoft_ec_toolbox_notation_figure_tree_Animation
class "BranchLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout
class "FoldedPageBorder" as C_com_evolsoft_ec_toolbox_notation_figure_tree_FoldedPageBorder
class "HangingLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout
class "NormalLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout
class "PageNode" as C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
class "PlusMinus" as C_com_evolsoft_ec_toolbox_notation_figure_tree_PlusMinus
class "TreeBranch" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
class "TreeFigure" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure
class "TreeLayout" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeLayout
class "TreeRoot" as C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot

C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout
C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch <|-- C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot
C_com_evolsoft_ec_toolbox_notation_figure_tree_BranchLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_HangingLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_NormalLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure --> C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeFigure --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeLayout --> C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeBranch
C_com_evolsoft_ec_toolbox_notation_figure_tree_TreeRoot --> C_com_evolsoft_ec_toolbox_notation_figure_tree_PageNode
@enduml
