@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.remoteservice

interface "IRemoteSolutionConverter" as C_com_evolsoft_core_runtime_remoteservice_IRemoteSolutionConverter
interface "ISolutionRemoteConverterDescriptor" as C_com_evolsoft_core_runtime_remoteservice_ISolutionRemoteConverterDescriptor
class "RemoteConverterDescriptor" as C_com_evolsoft_core_runtime_remoteservice_RemoteConverterDescriptor
class "SolutionRemoteConvertService" as C_com_evolsoft_core_runtime_remoteservice_SolutionRemoteConvertService

C_com_evolsoft_core_runtime_remoteservice_ISolutionRemoteConverterDescriptor <|.. C_com_evolsoft_core_runtime_remoteservice_RemoteConverterDescriptor
C_com_evolsoft_core_runtime_remoteservice_RemoteConverterDescriptor --> C_com_evolsoft_core_runtime_remoteservice_IRemoteSolutionConverter
@enduml
