@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.section

class "ByteSectionDescriptor" as C_com_evolsoft_ec_configuration_section_ByteSectionDescriptor
class "DoubleSectionDescriptor" as C_com_evolsoft_ec_configuration_section_DoubleSectionDescriptor
class "FloatSectionDescriptor" as C_com_evolsoft_ec_configuration_section_FloatSectionDescriptor
interface "IRule" as C_com_evolsoft_ec_configuration_section_IRule
class "IRuleInValidException" as C_com_evolsoft_ec_configuration_section_IRuleInValidException
interface "ISectionRule" as C_com_evolsoft_ec_configuration_section_ISectionRule
class "IntSectionDescriptor" as C_com_evolsoft_ec_configuration_section_IntSectionDescriptor
class "LongSectionDescriptor" as C_com_evolsoft_ec_configuration_section_LongSectionDescriptor
class "NumberSectionDescriptor" as C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor
class "ObjectSectionDescriptor" as C_com_evolsoft_ec_configuration_section_ObjectSectionDescriptor
class "SectionDescriptorBase" as C_com_evolsoft_ec_configuration_section_SectionDescriptorBase
class "SectionInitorDescriptor" as C_com_evolsoft_ec_configuration_section_SectionInitorDescriptor
class "SectionInitorService" as C_com_evolsoft_ec_configuration_section_SectionInitorService
class "ShortSectionDescriptor" as C_com_evolsoft_ec_configuration_section_ShortSectionDescriptor
class "StringSectionDescriptor" as C_com_evolsoft_ec_configuration_section_StringSectionDescriptor

C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_ByteSectionDescriptor
C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_DoubleSectionDescriptor
C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_FloatSectionDescriptor
C_com_evolsoft_ec_configuration_section_IRule <|-- C_com_evolsoft_ec_configuration_section_ISectionRule
C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_IntSectionDescriptor
C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_LongSectionDescriptor
C_com_evolsoft_ec_configuration_section_SectionDescriptorBase <|-- C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor
C_com_evolsoft_ec_configuration_section_SectionDescriptorBase <|-- C_com_evolsoft_ec_configuration_section_ObjectSectionDescriptor
C_com_evolsoft_ec_configuration_section_NumberSectionDescriptor <|-- C_com_evolsoft_ec_configuration_section_ShortSectionDescriptor
C_com_evolsoft_ec_configuration_section_SectionDescriptorBase <|-- C_com_evolsoft_ec_configuration_section_StringSectionDescriptor
C_com_evolsoft_ec_configuration_section_IRuleInValidException --> C_com_evolsoft_ec_configuration_section_ISectionRule
C_com_evolsoft_ec_configuration_section_SectionDescriptorBase --> C_com_evolsoft_ec_configuration_section_ISectionRule
@enduml
