@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.metadata.impl

class "ConfigMetadataFactoryImpl" as C_com_evolsoft_core_configuration_metadata_impl_ConfigMetadataFactoryImpl
class "ConfigMetadataPackageImpl" as C_com_evolsoft_core_configuration_metadata_impl_ConfigMetadataPackageImpl
class "ECConfigException" as C_com_evolsoft_core_configuration_metadata_impl_ECConfigException
class "EStringServiceItemAttributeImpl" as C_com_evolsoft_core_configuration_metadata_impl_EStringServiceItemAttributeImpl
class "EStringServiceItemImpl" as C_com_evolsoft_core_configuration_metadata_impl_EStringServiceItemImpl
class "ServiceItemAttributeImpl" as C_com_evolsoft_core_configuration_metadata_impl_ServiceItemAttributeImpl
class "ServiceItemImpl" as C_com_evolsoft_core_configuration_metadata_impl_ServiceItemImpl
class "ServiceMetaDataImpl" as C_com_evolsoft_core_configuration_metadata_impl_ServiceMetaDataImpl

@enduml
