@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.monitorEditor

class "AbstractECStubViewPage" as C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage
class "DashboradPage" as C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
class "ECTextEditor" as C_com_evolsoft_ec_ui_monitorEditor_ECTextEditor
class "GeneValueTracePage" as C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
class "GeneValueViewerSorter" as C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
interface "IECApplicationMonitorProvider" as C_com_evolsoft_ec_ui_monitorEditor_IECApplicationMonitorProvider
class "MonitorEditor" as C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor
class "MonitorPartInput" as C_com_evolsoft_ec_ui_monitorEditor_MonitorPartInput
class "RunAction" as C_com_evolsoft_ec_ui_monitorEditor_RunAction
class "TreeViewEx" as C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx
interface "that" as C_com_evolsoft_ec_ui_monitorEditor_that

C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage <|-- C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_AbstractECStubViewPage <|-- C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_DashboradPage --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_MonitorEditor --> C_com_evolsoft_ec_ui_monitorEditor_RunAction
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_RunAction --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_TreeViewEx --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueViewerSorter
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_DashboradPage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_GeneValueTracePage
C_com_evolsoft_ec_ui_monitorEditor_that --> C_com_evolsoft_ec_ui_monitorEditor_RunAction
@enduml
