@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.strategy

class "AbstractECStrategy" as C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy
class "AbstractEDAIndividualService" as C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService
class "ECEDAOptimizator" as C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator
class "ECOperatorManager" as C_com_evolsoft_ec_runtime_strategy_ECOperatorManager
class "ECOptimizatorBase" as C_com_evolsoft_ec_runtime_strategy_ECOptimizatorBase
class "EDAStrategy" as C_com_evolsoft_ec_runtime_strategy_EDAStrategy
interface "IECOperatorManager" as C_com_evolsoft_ec_runtime_strategy_IECOperatorManager
interface "IECOptimizator" as C_com_evolsoft_ec_runtime_strategy_IECOptimizator
interface "IECStrategy" as C_com_evolsoft_ec_runtime_strategy_IECStrategy
interface "IEDAOptimizatorDelegate" as C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
interface "IEDAOptimziator" as C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator
interface "IEDAStrategy" as C_com_evolsoft_ec_runtime_strategy_IEDAStrategy
interface "IGAOptimizator" as C_com_evolsoft_ec_runtime_strategy_IGAOptimizator
class "ProducingStrategy" as C_com_evolsoft_ec_runtime_strategy_ProducingStrategy
class "SearchingStrategy" as C_com_evolsoft_ec_runtime_strategy_SearchingStrategy

C_com_evolsoft_ec_runtime_strategy_ECOptimizatorBase <|-- C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator
C_com_evolsoft_ec_runtime_strategy_SearchingStrategy <|-- C_com_evolsoft_ec_runtime_strategy_EDAStrategy
C_com_evolsoft_ec_runtime_strategy_IECOptimizator <|-- C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator
C_com_evolsoft_ec_runtime_strategy_IECStrategy <|-- C_com_evolsoft_ec_runtime_strategy_IEDAStrategy
C_com_evolsoft_ec_runtime_strategy_IECOptimizator <|-- C_com_evolsoft_ec_runtime_strategy_IGAOptimizator
C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy <|-- C_com_evolsoft_ec_runtime_strategy_ProducingStrategy
C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy <|-- C_com_evolsoft_ec_runtime_strategy_SearchingStrategy
C_com_evolsoft_ec_runtime_strategy_IECStrategy <|.. C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy
C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator <|.. C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator
C_com_evolsoft_ec_runtime_strategy_IECOperatorManager <|.. C_com_evolsoft_ec_runtime_strategy_ECOperatorManager
C_com_evolsoft_ec_runtime_strategy_IECOptimizator <|.. C_com_evolsoft_ec_runtime_strategy_ECOptimizatorBase
C_com_evolsoft_ec_runtime_strategy_IEDAStrategy <|.. C_com_evolsoft_ec_runtime_strategy_EDAStrategy
C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy --> C_com_evolsoft_ec_runtime_strategy_IECOperatorManager
C_com_evolsoft_ec_runtime_strategy_AbstractECStrategy --> C_com_evolsoft_ec_runtime_strategy_IECOptimizator
C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimziator
C_com_evolsoft_ec_runtime_strategy_AbstractEDAIndividualService --> C_com_evolsoft_ec_runtime_strategy_IEDAStrategy
C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator --> C_com_evolsoft_ec_runtime_strategy_IEDAOptimizatorDelegate
C_com_evolsoft_ec_runtime_strategy_ECEDAOptimizator --> C_com_evolsoft_ec_runtime_strategy_IEDAStrategy
C_com_evolsoft_ec_runtime_strategy_ECOptimizatorBase --> C_com_evolsoft_ec_runtime_strategy_IECOperatorManager
C_com_evolsoft_ec_runtime_strategy_ECOptimizatorBase --> C_com_evolsoft_ec_runtime_strategy_IECStrategy
@enduml
