@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.selection

enum "ECSelectionType" as C_com_evolsoft_ec_runtime_selection_ECSelectionType
interface "IGenPickupService" as C_com_evolsoft_ec_runtime_selection_IGenPickupService
interface "IPickupService" as C_com_evolsoft_ec_runtime_selection_IPickupService
class "RecombinationPickupServiceBase" as C_com_evolsoft_ec_runtime_selection_RecombinationPickupServiceBase
class "RouletteWheelPickUpService" as C_com_evolsoft_ec_runtime_selection_RouletteWheelPickUpService
class "RouletteWheelSelector" as C_com_evolsoft_ec_runtime_selection_RouletteWheelSelector
class "TournamentPickupService" as C_com_evolsoft_ec_runtime_selection_TournamentPickupService
class "WheelItem" as C_com_evolsoft_ec_runtime_selection_WheelItem

C_com_evolsoft_ec_runtime_selection_RecombinationPickupServiceBase <|-- C_com_evolsoft_ec_runtime_selection_RouletteWheelPickUpService
C_com_evolsoft_ec_runtime_selection_RecombinationPickupServiceBase <|-- C_com_evolsoft_ec_runtime_selection_TournamentPickupService
C_com_evolsoft_ec_runtime_selection_IPickupService <|.. C_com_evolsoft_ec_runtime_selection_RecombinationPickupServiceBase
@enduml
