@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.chromosome

class "ChromosomeBase" as C_com_evolsoft_ec_runtime_chromosome_ChromosomeBase
class "ChromosomeFactoryBase" as C_com_evolsoft_ec_runtime_chromosome_ChromosomeFactoryBase
class "GeneLayoutBase" as C_com_evolsoft_ec_runtime_chromosome_GeneLayoutBase
class "GraphChromosomeBase" as C_com_evolsoft_ec_runtime_chromosome_GraphChromosomeBase
interface "IChromosome" as C_com_evolsoft_ec_runtime_chromosome_IChromosome
interface "IChromosomeFactory" as C_com_evolsoft_ec_runtime_chromosome_IChromosomeFactory
interface "IChromsomeLayout" as C_com_evolsoft_ec_runtime_chromosome_IChromsomeLayout
interface "ISectionChromoInitor" as C_com_evolsoft_ec_runtime_chromosome_ISectionChromoInitor
interface "ISectionChromosome" as C_com_evolsoft_ec_runtime_chromosome_ISectionChromosome
class "SectionChromoInitorBase" as C_com_evolsoft_ec_runtime_chromosome_SectionChromoInitorBase
class "SectionChromosomeBase" as C_com_evolsoft_ec_runtime_chromosome_SectionChromosomeBase
class "SectionChromosomeFactory" as C_com_evolsoft_ec_runtime_chromosome_SectionChromosomeFactory
class "SectionLayoutBase" as C_com_evolsoft_ec_runtime_chromosome_SectionLayoutBase
class "TreeChromosomeBase" as C_com_evolsoft_ec_runtime_chromosome_TreeChromosomeBase

C_com_evolsoft_ec_runtime_chromosome_ChromosomeBase <|-- C_com_evolsoft_ec_runtime_chromosome_GraphChromosomeBase
C_com_evolsoft_ec_runtime_chromosome_IChromosome <|-- C_com_evolsoft_ec_runtime_chromosome_ISectionChromosome
C_com_evolsoft_ec_runtime_chromosome_ChromosomeBase <|-- C_com_evolsoft_ec_runtime_chromosome_SectionChromosomeBase
C_com_evolsoft_ec_runtime_chromosome_ChromosomeFactoryBase <|-- C_com_evolsoft_ec_runtime_chromosome_SectionChromosomeFactory
C_com_evolsoft_ec_runtime_chromosome_ChromosomeBase <|-- C_com_evolsoft_ec_runtime_chromosome_TreeChromosomeBase
C_com_evolsoft_ec_runtime_chromosome_IChromosome <|.. C_com_evolsoft_ec_runtime_chromosome_ChromosomeBase
C_com_evolsoft_ec_runtime_chromosome_IChromosomeFactory <|.. C_com_evolsoft_ec_runtime_chromosome_ChromosomeFactoryBase
C_com_evolsoft_ec_runtime_chromosome_ISectionChromoInitor <|.. C_com_evolsoft_ec_runtime_chromosome_SectionChromoInitorBase
C_com_evolsoft_ec_runtime_chromosome_ISectionChromosome <|.. C_com_evolsoft_ec_runtime_chromosome_SectionChromosomeBase
@enduml
