@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.assmnt.model

interface "IAssmntModel" as C_com_evolsoft_assmnt_model_IAssmntModel
interface "IIdentifable" as C_com_evolsoft_assmnt_model_IIdentifable
interface "IPredValueDomain" as C_com_evolsoft_assmnt_model_IPredValueDomain
interface "IPredicateDescriptor" as C_com_evolsoft_assmnt_model_IPredicateDescriptor

C_com_evolsoft_assmnt_model_IIdentifable <|-- C_com_evolsoft_assmnt_model_IPredicateDescriptor
@enduml
