@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.impl

class "ConfigIdentifiableObjectEx" as C_com_evolsoft_core_configuration_impl_ConfigIdentifiableObjectEx
class "ConfigVersionObejctEx" as C_com_evolsoft_core_configuration_impl_ConfigVersionObejctEx
class "CoreConfigFactory" as C_com_evolsoft_core_configuration_impl_CoreConfigFactory
class "CoreConfigPackage" as C_com_evolsoft_core_configuration_impl_CoreConfigPackage
class "ECDataLoaderDescriptor" as C_com_evolsoft_core_configuration_impl_ECDataLoaderDescriptor
class "ECParameter" as C_com_evolsoft_core_configuration_impl_ECParameter
class "ECParameterContainer" as C_com_evolsoft_core_configuration_impl_ECParameterContainer
class "EStringToECParameter" as C_com_evolsoft_core_configuration_impl_EStringToECParameter
class "PlugInConfigurableObject" as C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject
class "PlugInVersionObject" as C_com_evolsoft_core_configuration_impl_PlugInVersionObject
class "RefPath" as C_com_evolsoft_core_configuration_impl_RefPath

C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject <|-- C_com_evolsoft_core_configuration_impl_ConfigIdentifiableObjectEx
C_com_evolsoft_core_configuration_impl_ConfigIdentifiableObjectEx <|-- C_com_evolsoft_core_configuration_impl_ConfigVersionObejctEx
C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject <|-- C_com_evolsoft_core_configuration_impl_ECDataLoaderDescriptor
C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject <|-- C_com_evolsoft_core_configuration_impl_ECParameter
C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject <|-- C_com_evolsoft_core_configuration_impl_ECParameterContainer
C_com_evolsoft_core_configuration_impl_PlugInConfigurableObject <|-- C_com_evolsoft_core_configuration_impl_PlugInVersionObject
@enduml
