@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor.util

class "ECRTMonitorAdapterFactory" as C_com_evolsoft_ec_runtime_monitor_util_ECRTMonitorAdapterFactory
class "ECRTMonitorSwitch" as C_com_evolsoft_ec_runtime_monitor_util_ECRTMonitorSwitch

@enduml
