@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.msga.tool

class "ECMultiObjectivePlugin" as C_com_evolsoft_ec_msga_tool_ECMultiObjectivePlugin

@enduml
