@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.configuration.apporach

interface "IComponentConfig" as C_com_evolsoft_core_configuration_apporach_IComponentConfig
interface "IComponentConfigMgr" as C_com_evolsoft_core_configuration_apporach_IComponentConfigMgr
interface "IComponentProperty" as C_com_evolsoft_core_configuration_apporach_IComponentProperty
interface "ISolutionDescriptor" as C_com_evolsoft_core_configuration_apporach_ISolutionDescriptor
interface "ISolutionTemplate" as C_com_evolsoft_core_configuration_apporach_ISolutionTemplate
class "InternalParameters" as C_com_evolsoft_core_configuration_apporach_InternalParameters
class "Paramter" as C_com_evolsoft_core_configuration_apporach_Paramter
class "SolutionDescriptorBase" as C_com_evolsoft_core_configuration_apporach_SolutionDescriptorBase

C_com_evolsoft_core_configuration_apporach_ISolutionDescriptor <|.. C_com_evolsoft_core_configuration_apporach_SolutionDescriptorBase
@enduml
