@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evosoft.assmnt.encoding

class "LocusbasedEncodingService" as C_com_evosoft_assmnt_encoding_LocusbasedEncodingService
class "LocusbasedLayout" as C_com_evosoft_assmnt_encoding_LocusbasedLayout
class "PredicateDecisionItem" as C_com_evosoft_assmnt_encoding_PredicateDecisionItem

C_com_evosoft_assmnt_encoding_LocusbasedEncodingService --> C_com_evosoft_assmnt_encoding_LocusbasedLayout
@enduml
