@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.problem.rcpsp.uncertainModel

interface "IScenario" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IScenario
interface "IUncertainRCPSPModel" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPModel
interface "IUncertainRCPSPScheudling" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPScheudling
interface "IUncertaintRCPSPDataProvider" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertaintRCPSPDataProvider
class "RCPSPScheudlingAdapter" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_RCPSPScheudlingAdapter
class "Scenario" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_Scenario
class "ScenarioManager" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_ScenarioManager
class "ScenarioReader" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_ScenarioReader
class "UncertainRCPSPDataProvider" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPDataProvider
class "UncertainRCPSPModel" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPModel
class "UncertainRCPSPScheduling" as C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPScheduling

C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IScenario <|.. C_com_evolsoft_ec_problem_rcpsp_uncertainModel_Scenario
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertaintRCPSPDataProvider <|.. C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPDataProvider
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPModel <|.. C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPModel
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPScheudling <|.. C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPScheduling
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_RCPSPScheudlingAdapter --> C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPModel
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_ScenarioManager --> C_com_evolsoft_ec_problem_rcpsp_uncertainModel_IUncertainRCPSPModel
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_ScenarioReader --> C_com_evolsoft_ec_problem_rcpsp_uncertainModel_Scenario
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPModel --> C_com_evolsoft_ec_problem_rcpsp_uncertainModel_ScenarioManager
C_com_evolsoft_ec_problem_rcpsp_uncertainModel_UncertainRCPSPScheduling --> C_com_evolsoft_ec_problem_rcpsp_uncertainModel_Scenario
@enduml
