@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.core.runtime.problem.nature

class "AbstractNatureAction" as C_com_evolsoft_core_runtime_problem_nature_AbstractNatureAction
class "AbstractProblemNatureTrigger" as C_com_evolsoft_core_runtime_problem_nature_AbstractProblemNatureTrigger
interface "INatureAction" as C_com_evolsoft_core_runtime_problem_nature_INatureAction
interface "INatureActionDescriptor" as C_com_evolsoft_core_runtime_problem_nature_INatureActionDescriptor
interface "IProblemNatureDescriptor" as C_com_evolsoft_core_runtime_problem_nature_IProblemNatureDescriptor
interface "IProblemNatureDescriptorSpec" as C_com_evolsoft_core_runtime_problem_nature_IProblemNatureDescriptorSpec
interface "IProblemNatureExtDescriptorSpec" as C_com_evolsoft_core_runtime_problem_nature_IProblemNatureExtDescriptorSpec
interface "IProblemNatureTrigger" as C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTrigger
interface "IProblemNatureTriggerDescriptor" as C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTriggerDescriptor
class "NatureActionDescriptor" as C_com_evolsoft_core_runtime_problem_nature_NatureActionDescriptor
class "ProblemNatureDescriptor" as C_com_evolsoft_core_runtime_problem_nature_ProblemNatureDescriptor
class "ProblemNatureExtesionRefDescriptor" as C_com_evolsoft_core_runtime_problem_nature_ProblemNatureExtesionRefDescriptor
class "ProblemNatureTriggerEvent" as C_com_evolsoft_core_runtime_problem_nature_ProblemNatureTriggerEvent
enum "TriggerScope" as C_com_evolsoft_core_runtime_problem_nature_TriggerScope

C_com_evolsoft_core_runtime_problem_nature_INatureAction <|.. C_com_evolsoft_core_runtime_problem_nature_AbstractNatureAction
C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTrigger <|.. C_com_evolsoft_core_runtime_problem_nature_AbstractProblemNatureTrigger
C_com_evolsoft_core_runtime_problem_nature_INatureActionDescriptor <|.. C_com_evolsoft_core_runtime_problem_nature_NatureActionDescriptor
C_com_evolsoft_core_runtime_problem_nature_IProblemNatureDescriptor <|.. C_com_evolsoft_core_runtime_problem_nature_ProblemNatureDescriptor
C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTriggerDescriptor <|.. C_com_evolsoft_core_runtime_problem_nature_ProblemNatureExtesionRefDescriptor
C_com_evolsoft_core_runtime_problem_nature_ProblemNatureDescriptor --> C_com_evolsoft_core_runtime_problem_nature_INatureAction
C_com_evolsoft_core_runtime_problem_nature_ProblemNatureDescriptor --> C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTrigger
C_com_evolsoft_core_runtime_problem_nature_ProblemNatureDescriptor --> C_com_evolsoft_core_runtime_problem_nature_TriggerScope
C_com_evolsoft_core_runtime_problem_nature_ProblemNatureExtesionRefDescriptor --> C_com_evolsoft_core_runtime_problem_nature_IProblemNatureTrigger
@enduml
