@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: org.eclipse.jface.snippets.viewers

class "ExampleLabelProvider" as C_org_eclipse_jface_snippets_viewers_ExampleLabelProvider
class "FileSystemContentProvider" as C_org_eclipse_jface_snippets_viewers_FileSystemContentProvider
class "LineEntry" as C_org_eclipse_jface_snippets_viewers_LineEntry
class "MyContentProvider" as C_org_eclipse_jface_snippets_viewers_MyContentProvider
class "MyContentProvider (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyContentProvider__dup2
class "MyContentProvider (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyContentProvider__dup3
class "MyContentProvider (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyContentProvider__dup4
class "MyContentProvider (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyContentProvider__dup5
class "MyLabelProvider" as C_org_eclipse_jface_snippets_viewers_MyLabelProvider
class "MyLabelProvider (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyLabelProvider__dup2
class "MyModel" as C_org_eclipse_jface_snippets_viewers_MyModel
class "MyModel (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyModel__dup2
class "MyModel (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyModel__dup3
class "MyModel (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyModel__dup4
class "MyModel (com.evolsoft.ec.ui.simulation)" as C_org_eclipse_jface_snippets_viewers_MyModel__dup5
class "OptimizedIndexSearcher" as C_org_eclipse_jface_snippets_viewers_OptimizedIndexSearcher
class "Snippet005TreeCustomMenu" as C_org_eclipse_jface_snippets_viewers_Snippet005TreeCustomMenu
class "Snippet006TableMultiLineCells" as C_org_eclipse_jface_snippets_viewers_Snippet006TableMultiLineCells
class "Snippet026TreeViewerTabEditing" as C_org_eclipse_jface_snippets_viewers_Snippet026TreeViewerTabEditing
class "Snippet041TableViewerAlternatingColors" as C_org_eclipse_jface_snippets_viewers_Snippet041TableViewerAlternatingColors
class "Snippet045TableViewerFillFromBackgroundThread" as C_org_eclipse_jface_snippets_viewers_Snippet045TableViewerFillFromBackgroundThread
class "Snippet046UpdateViewerFromBackgroundThread" as C_org_eclipse_jface_snippets_viewers_Snippet046UpdateViewerFromBackgroundThread
class "Snippet049StyledCellLabelProvider" as C_org_eclipse_jface_snippets_viewers_Snippet049StyledCellLabelProvider
class "TextLayoutStyleColor" as C_org_eclipse_jface_snippets_viewers_TextLayoutStyleColor

C_org_eclipse_jface_snippets_viewers_Snippet006TableMultiLineCells --> C_org_eclipse_jface_snippets_viewers_LineEntry
@enduml
