@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.problem.fjsp.FJSPModel.impl

class "AbstractResourceImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_AbstractResourceImpl
class "AbstractResourceImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_AbstractResourceImpl__dup2
class "FJSPModelFactoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelFactoryImpl
class "FJSPModelFactoryImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelFactoryImpl__dup2
class "FJSPModelImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelImpl
class "FJSPModelImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelImpl__dup2
class "FJSPModelPackageImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_FJSPModelPackageImpl
class "IdentifyingImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_IdentifyingImpl
class "IdentifyingImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_IdentifyingImpl__dup2
class "MachineImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineImpl
class "MachineImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineImpl__dup2
class "MachineItemImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineItemImpl
class "MachineItemImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineItemImpl__dup2
class "MachineManagerImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineManagerImpl
class "MachineManagerImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachineManagerImpl__dup2
class "MachiningConfigurationImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachiningConfigurationImpl
class "MachiningConfigurationImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_MachiningConfigurationImpl__dup2
class "ManufactureFactoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ManufactureFactoryImpl
class "ManufactureFactoryImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ManufactureFactoryImpl__dup2
class "OperationImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_OperationImpl
class "OperationImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_OperationImpl__dup2
class "ProductCategoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductCategoryImpl
class "ProductCategoryImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductCategoryImpl__dup2
class "ProductImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductImpl
class "ProductImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ProductImpl__dup2
class "ResourceCategoryImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceCategoryImpl
class "ResourceCategoryImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceCategoryImpl__dup2
class "ResourceConstrainImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceConstrainImpl
class "ResourceConstrainImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceConstrainImpl__dup2
class "ResourceImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceImpl
class "ResourceImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceImpl__dup2
class "ResourceItemImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceItemImpl
class "ResourceItemImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceItemImpl__dup2
class "ResourceManagerImpl" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceManagerImpl
class "ResourceManagerImpl (com.evolsoft.problem.fjsp2.model)" as C_com_evolsoft_problem_fjsp_FJSPModel_impl_ResourceManagerImpl__dup2

@enduml
