@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.runtime.monitor.statistic

interface "IStatisticItemManager" as C_com_evolsoft_ec_runtime_monitor_statistic_IStatisticItemManager
interface "ITracePolicy" as C_com_evolsoft_ec_runtime_monitor_statistic_ITracePolicy
class "ObjectiveStatist" as C_com_evolsoft_ec_runtime_monitor_statistic_ObjectiveStatist
class "StatisticItemManager" as C_com_evolsoft_ec_runtime_monitor_statistic_StatisticItemManager
class "StatisticTraceItem" as C_com_evolsoft_ec_runtime_monitor_statistic_StatisticTraceItem
enum "TraceLevel" as C_com_evolsoft_ec_runtime_monitor_statistic_TraceLevel
class "TracePolicy" as C_com_evolsoft_ec_runtime_monitor_statistic_TracePolicy

C_com_evolsoft_ec_runtime_monitor_statistic_IStatisticItemManager <|.. C_com_evolsoft_ec_runtime_monitor_statistic_StatisticItemManager
C_com_evolsoft_ec_runtime_monitor_statistic_ITracePolicy <|.. C_com_evolsoft_ec_runtime_monitor_statistic_TracePolicy
C_com_evolsoft_ec_runtime_monitor_statistic_StatisticItemManager --> C_com_evolsoft_ec_runtime_monitor_statistic_ITracePolicy
C_com_evolsoft_ec_runtime_monitor_statistic_StatisticItemManager --> C_com_evolsoft_ec_runtime_monitor_statistic_StatisticTraceItem
C_com_evolsoft_ec_runtime_monitor_statistic_StatisticTraceItem --> C_com_evolsoft_ec_runtime_monitor_statistic_ITracePolicy
C_com_evolsoft_ec_runtime_monitor_statistic_TracePolicy --> C_com_evolsoft_ec_runtime_monitor_statistic_TraceLevel
@enduml
