@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.configuration.population

class "GenerationDescriptor" as C_com_evolsoft_ec_configuration_population_GenerationDescriptor
class "GenerationPickupActionDescriptor" as C_com_evolsoft_ec_configuration_population_GenerationPickupActionDescriptor
class "GenerationPickupService" as C_com_evolsoft_ec_configuration_population_GenerationPickupService
interface "IFitnessActionDescriptor" as C_com_evolsoft_ec_configuration_population_IFitnessActionDescriptor
interface "IFitnessServiceDescriptorSpec" as C_com_evolsoft_ec_configuration_population_IFitnessServiceDescriptorSpec
interface "IGenerationDescriptor" as C_com_evolsoft_ec_configuration_population_IGenerationDescriptor
interface "IGenerationDescriptorSpec" as C_com_evolsoft_ec_configuration_population_IGenerationDescriptorSpec
interface "IGenerationPickupActionDescriptor" as C_com_evolsoft_ec_configuration_population_IGenerationPickupActionDescriptor
interface "IPopulationDescriptor" as C_com_evolsoft_ec_configuration_population_IPopulationDescriptor
interface "IPopulationDescriptorSpec" as C_com_evolsoft_ec_configuration_population_IPopulationDescriptorSpec
class "ParentSelectService" as C_com_evolsoft_ec_configuration_population_ParentSelectService
class "PopulationDescriptor" as C_com_evolsoft_ec_configuration_population_PopulationDescriptor

C_com_evolsoft_ec_configuration_population_IGenerationDescriptor <|.. C_com_evolsoft_ec_configuration_population_GenerationDescriptor
C_com_evolsoft_ec_configuration_population_IGenerationPickupActionDescriptor <|.. C_com_evolsoft_ec_configuration_population_GenerationPickupActionDescriptor
C_com_evolsoft_ec_configuration_population_IPopulationDescriptor <|.. C_com_evolsoft_ec_configuration_population_PopulationDescriptor
@enduml
