@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.toolbox.ganttChart.swt

class "ColumnMetaData" as C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData
class "ColumnViewerToolTipSupportEx" as C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnViewerToolTipSupportEx
class "GTRenderUtils" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GTRenderUtils
class "GanttChartContentProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
class "Ganttchart" as C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart
class "GroupSelectionEventArgs" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupSelectionEventArgs
class "GroupTagLabelProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider
class "GroupTagProvider" as C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
class "HighlightItemChangedEventArgs" as C_com_evolsoft_ec_toolbox_ganttChart_swt_HighlightItemChangedEventArgs
interface "IGTGroupSelectionListener" as C_com_evolsoft_ec_toolbox_ganttChart_swt_IGTGroupSelectionListener
interface "IHighlightItemChangedListener" as C_com_evolsoft_ec_toolbox_ganttChart_swt_IHighlightItemChangedListener
class "LegendCheckTreeViewer" as C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer
class "Sorter" as C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter
class "TagItem" as C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
interface "must" as C_com_evolsoft_ec_toolbox_ganttChart_swt_must

C_com_evolsoft_ec_toolbox_ganttChart_swt_ColumnMetaData --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_Ganttchart --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagLabelProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_LegendCheckTreeViewer --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_Sorter --> C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem
C_com_evolsoft_ec_toolbox_ganttChart_swt_TagItem --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GroupTagProvider
C_com_evolsoft_ec_toolbox_ganttChart_swt_must --> C_com_evolsoft_ec_toolbox_ganttChart_swt_GanttChartContentProvider
@enduml
