@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.problem.fjsp.dispatching

class "AbstractDispatchRuleBuilder" as C_com_evolsoft_problem_fjsp_dispatching_AbstractDispatchRuleBuilder
class "AbstractPrioirtyBasedBuilderBase" as C_com_evolsoft_problem_fjsp_dispatching_AbstractPrioirtyBasedBuilderBase
class "DispatchRule" as C_com_evolsoft_problem_fjsp_dispatching_DispatchRule
class "DispatchRuleMutation" as C_com_evolsoft_problem_fjsp_dispatching_DispatchRuleMutation
interface "IDispatchRuleBuilder" as C_com_evolsoft_problem_fjsp_dispatching_IDispatchRuleBuilder
interface "IDispathComparator" as C_com_evolsoft_problem_fjsp_dispatching_IDispathComparator
interface "IPriorityBasedBuilder" as C_com_evolsoft_problem_fjsp_dispatching_IPriorityBasedBuilder
class "PriorityBasedBuilder" as C_com_evolsoft_problem_fjsp_dispatching_PriorityBasedBuilder
class "Selection" as C_com_evolsoft_problem_fjsp_dispatching_Selection

C_com_evolsoft_problem_fjsp_dispatching_AbstractPrioirtyBasedBuilderBase <|-- C_com_evolsoft_problem_fjsp_dispatching_AbstractDispatchRuleBuilder
C_com_evolsoft_problem_fjsp_dispatching_IPriorityBasedBuilder <|-- C_com_evolsoft_problem_fjsp_dispatching_IDispatchRuleBuilder
C_com_evolsoft_problem_fjsp_dispatching_AbstractPrioirtyBasedBuilderBase <|-- C_com_evolsoft_problem_fjsp_dispatching_PriorityBasedBuilder
C_com_evolsoft_problem_fjsp_dispatching_IDispatchRuleBuilder <|.. C_com_evolsoft_problem_fjsp_dispatching_AbstractDispatchRuleBuilder
C_com_evolsoft_problem_fjsp_dispatching_IPriorityBasedBuilder <|.. C_com_evolsoft_problem_fjsp_dispatching_PriorityBasedBuilder
@enduml
