@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: com.evolsoft.ec.ui.page.actions

class "ECExtensionAction" as C_com_evolsoft_ec_ui_page_actions_ECExtensionAction

@enduml
