@startuml
left to right direction
skinparam classAttributeIconSize 0
title Package: ec.evolsoft.ec.solutionviewer

class "ChartViewPage" as C_ec_evolsoft_ec_solutionviewer_ChartViewPage
class "ShowSolutionHandler" as C_ec_evolsoft_ec_solutionviewer_ShowSolutionHandler
class "SolutionChartEditor" as C_ec_evolsoft_ec_solutionviewer_SolutionChartEditor
class "SolutionFileEditorInput" as C_ec_evolsoft_ec_solutionviewer_SolutionFileEditorInput
class "SolutionViewerPlugin" as C_ec_evolsoft_ec_solutionviewer_SolutionViewerPlugin

@enduml
